### ISSUE TITLE
Getting the quadrilaterals from a PopplerAnnotTextMarkup object

### ISSUE THREAD

**Issue by philgooch** [ruby-gnome/ruby-gnome#1024]
Would it be possible to extend the bindings so that the `poppler_annot_text_markup_get_quadrilaterals` method is exposed for `PopplerAnnotTextMarkup` objects that are retrieved from `AnnotationMapping` objects on the `Page`?

https://people.freedesktop.org/~ajohnson/docs/poppler-glib/PopplerAnnot.html#poppler-annot-text-markup-get-quadrilaterals

(which probably is derived from https://people.freedesktop.org/~aacid/docs/qt4/classPoppler_1_1HighlightAnnotation.html)

Alternatively, if you can provide some pointers, I can have a go myself and make a pull request. Thanks!

**Comment by kou** [comment]
Yes. It's possible.

If we migrate our Poppler bindings to GObject Introspection based bindings, it'll be available.

Recently, we migrate our ATK bindings to GObject Introspection based bindings. `atk/` is GObject Introspection based bindings. `atk-no-gi/` is our old handwriting bindings. They will help you.

**Comment by cedlemo** [comment]
@philgooch , I don't know how you progressed so far, but you can see an exemple here #1030 .

**Comment by kou** [comment]
Migrated.
