### ISSUE TITLE
Windows support - would it be possible to add a link or subsection for ruby-gnome on windows, on the main readme?

### ISSUE THREAD

**Issue by ghost** [ruby-gnome/ruby-gnome#1043]
Hello ruby-gnome maintainers,

I am writing this right now from my laptop; win10 is on it. The keyboard is a bit small so please excuse any typos... :)

I have just installed ruby-2.4.1 etc... and now I would like to install ruby.gnome.

I remember I did this many years ago and it worked (on windows), but right now I am not sure what I did... the main readme also gives no pointers to this right now - which brings me to my suggestion.

Could the main readme please add a short paragraph or subsections about windows? E. g. where to get it... I think there once was a .exe file... I will look for it when I am at home again ... the small keyboard on this laptop is killing me right now sorry.

**Comment by kou** [comment]
Just run `gem install gtk3`. No .exe is needed now.
