### ISSUE TITLE
poppler-page-find-text-with-options(text,option)

### ISSUE THREAD

**Issue by RonLeapYearBoy** [ruby-gnome/ruby-gnome#1061]
**Ruby Bindings do not appear to have been written for this function.**

https://developer.gnome.org/poppler/unstable/PopplerPage.html#poppler-page-find-text-with-options https://developer.gnome.org/poppler/unstable/poppler-poppler.html#PopplerFindFlags
https://people.freedesktop.org/~ajohnson/docs/poppler-glib/PopplerPage.html#poppler-page-find-text-with-options

There does dont appear to be any ruby bindings for this Poppler function.  For
example, notice that a search for 'man' will also find the 'man' in 'human' and 'many'.   The default
search searches for a word either a whole word or a substring within the text.    The  find_text just uses the default setting 
Find With Options: PopplerFindFlags    
      ->https://lazka.github.io/pgi-docs/Poppler-0.18/flags.html#Poppler.FindFlags
   
POPPLER_FIND_DEFAULT            0
   POPPLER_FIND_CASE_SENSITIVE     1
   POPPLER_FIND_BACKWARDS          2
   POPPLER_FIND_WHOLE_WORDS_ONLY   4 

![search-results-for-man](https://user-images.githubusercontent.com/1864766/28240096-bb9692b2-6948-11e7-93d8-b873c3b536f2.png)

**Comment by cedlemo** [comment]
@kou, I plan to update the poppler module to ist GObject-Introspection form. Maybe it could solve this problem.

**Comment by kou** [comment]
Great!

**Comment by cedlemo** [comment]
@kou, @RonLeapYearBoy 

with poppler based on GObjectIntrospection, I have this : 

```
irb -r poppler
irb(main):001:0> Poppler::Page.methods.grep(/find/)
=> []
irb(main):002:0> Poppler::Page.instance_methods.grep(/find/)
=> [:find_text, :find_text_with_options]
irb(main):003:0> 
```

**Comment by kou** [comment]
It seems that we should provide `find_text(text, options=nil)` method for easy to use.

**Comment by kou** [comment]
Done.
