### ISSUE TITLE
Minor compile/installation issue - hardcoded path to /usr/bin/mkdir ?

### ISSUE THREAD

**Issue by ghost** [ruby-gnome/ruby-gnome#1077]
Hello.

When trying to compile ruby-gnome2, I get this:

    Doing system 
        make install
    now in /Depot/jj/rubygnome2-3.1.6/cairo-gobject.

(cd ext/cairo-gobject && make install)
make[1]: Entering directory '/Depot/jj/rubygnome2-3.1.6/cairo-gobject/ext/cairo-gobject'
make[1]: /usr/bin/mkdir: Command not found
make[1]: *** [Makefile:199: .sitearchdir.time] Error 127
make[1]: Leaving directory '/Depot/jj/rubygnome2-3.1.6/cairo-gobject/ext/cairo-gobject'
make: *** [Makefile:6: install] Error 2

I believe that the path to /usr/bin/mkdir is hardcoded. On my system, mkdir itself can be found as a symlink towards /System/Executables/mkdir which in itself points towards /Programs/Coreutils/8.27/bin/mkdir

It is not any big issue; I simply symlinked from /System/Executables/mkdir into /usr/bin/mkdir for the time being, with the "make" and "make install step" working now. But I also wondered that perhaps the installation script could try to dynamically check for the location of mkdir? It is in my PATH variable so it works if it is not hardcoded.

**Comment by kou** [comment]
I think that it's a `mkmf.rb` related thing rather than Ruby-GNOME2 related thing.

How to install your Ruby? How to install Ruby-GNOME2?
https://github.com/ruby-gnome2/ruby-gnome2#advanced-installation ?
