### ISSUE TITLE
Emojis stopped working in Pango 3.1.9+

### ISSUE THREAD

**Issue by andymeneely** [ruby-gnome/ruby-gnome#1111]
Starting in pango 3.1.9, my emojis don't show up properly. I usually see this warning when the font doesn't exist on my system, but I've never seen just "emoji" as a font before.

Here's a test case:
```ruby
require 'cairo'
require 'pango'

cc = Cairo::Context.new(Cairo::ImageSurface.new(150,150))
cc.set_source_color(:white)
cc.paint
cc.set_source_color(:black)
cc.move_to(0, 0)
layout = cc.create_pango_layout
layout.font_description = Pango::FontDescription.new("Segoe UI Symbol 72")
layout.text = "🔊"
cc.show_pango_layout(layout)
cc.target.write_to_png('test.png')
```

On pango 3.1.8

![test](https://user-images.githubusercontent.com/341847/32686011-e12da662-c66a-11e7-94f2-a05a7c156715.png)

But then in 3.1.9+ I get the following warning:

```
Pango-WARNING **: couldn't load font "emoji Not-Rotated 72", falling back to "Sans Not-Rotated 72", expect ugly output.
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.0-x64-mingw32/lib/gobject-introspection/loader.rb:574:in `block in define_method'
        from pango_emoji.rb:12:in `<main>'
```

And then the test image is:

![test](https://user-images.githubusercontent.com/341847/32686022-0c9f32f2-c66b-11e7-814a-b813aa7e11fc.png)

I'm on Windows, running ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

**Comment by kou** [comment]
Please show cairo gem version when emoji is corrected and emoji is broken.

**Comment by kou** [comment]
And I want to know `ruby -rpango -e 'p Pango::CairoFontMap.default'`.

**Comment by kou** [comment]
It's better that we comment on https://bugzilla.gnome.org/show_bug.cgi?id=787365 .

pango gem 3.1.9 uses Pango 1.40.12. It always uses "emoji" font family for emoji.

On Windows, fontconfig isn't used by default. Windows font renderer is used by default. Windows font renderer doesn't understand "emoji" font family.

Please comment on the Bugzilla page.

**Comment by andymeneely** [comment]
So... an update on this issue. 

As of now, looks like the above code won't error out, but it won't pick up the Segoe UI Symbol font. For cairo v1.16.2 and pango 3.3.2. Running on 2.5.3p105 on Windows 10. 

![test](https://user-images.githubusercontent.com/341847/54002387-5c9a0c00-411c-11e9-8733-7e73c7b6e9d2.png)

And yet I know that the font is installed properly because in my font settings dialog I can still render the emoji properly:

![image](https://user-images.githubusercontent.com/341847/54002418-83f0d900-411c-11e9-9fdb-3ea0dc887d04.png)

Interestingly, if you just change the font to `Serif 72`, it will render the above. So pango just isn't picking up the font when it comes to emojis.

**Comment by andymeneely** [comment]
I did some digging on this, and it looks like Pango added the Segoe UI font as a fallback no matter what.

https://gitlab.gnome.org/GNOME/pango/issues/302
(aka bugzilla 794705)

This gem has the binary with that change, so that explains the behavior change. BUT, this gem doesn't have pango 1.43, which includes this line in the changelog:

```
Improve font fallback handling on win32
```

The change they were talking about is this:

https://gitlab.gnome.org/GNOME/pango/commit/f523c25c12cd19c59fbc3db4a4fe08bae5307802

...which means that the font fallback would go to the registry instead of a hardcoded list. Which I suppose is fine. If ruby-gnome2 upgrades to 1.43, I can just hack the registry to be `Segoe UI Symbol` instead of `Segoe UI`.

But my main question still remains: why is this falling back at all? Is it still just overriding my font string with "emoji"? How do I get around that?

(and I did comment on the bugzilla, but nobody seemed to acknowledge it).

I'm sorry to nag you @kou about this, but this regression is a real hassle for me and I'd like to figure out a workaround.

**Comment by kou** [comment]
The latest pango gem doesn't bundle Pango binary. It uses binary provided by MSYS2.
It seems that the latest Pango package on MSYS2 is 1.43.0: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-pango/PKGBUILD

So you will be able to use your registry with the latest pango gem and Pango package on MSYS2.

Can we close this?

**Comment by andymeneely** [comment]
Ah ok, so digging into my mysys2 folder I can see that 1.43.0-1 is installed (`C:\Ruby26-x64\msys64\var\lib\pacman\local\mingw-w64-x86_64-pango-1.43.0-1`).

So I'm trying the registry hack and I can't get it to work. I'm going to start a thread on Gnome discourse to see if we can get this change documented and ask how we can better specify the emoji font.

I'd like to keep this issue open. I still see it as a regression. I don't like the idea of asking my users to hack their registry just to get emojis working. We need a better solution imo.

**Comment by kou** [comment]
OK. We keep this issue open.

The link to the thread on GNOME Discourse: https://discourse.gnome.org/t/using-emojis-in-pango-1-43-0-1-on-windows/711

**Comment by kou** [comment]
I hope that this was fixed in the latest Pango.
