### ISSUE TITLE
Deprecated method pointer

### ISSUE THREAD

**Issue by arjunmenon** [ruby-gnome/ruby-gnome#1147]
Hey
I am getting this error
```
'Gtk::Widget#pointer' has been deprecated. Use 'Gdk::Window#get_device_position'. (GLib::DeprecatedError)
```
But there is no `get_device_position` in [class Gdk::Window](https://ruby-gnome2.osdn.jp/hiki.cgi?Gdk%3A%3AWindow)

I see that it was raised here, [`define_deprecated_method :pointer, :raise => "Use 'Gdk::Window#get_device_position'."`](https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gtk3/lib/gtk3/deprecated.rb#L1080)

Temporarly blocking that, returns a no method error. Even the `Gtk::Widget#pointer` method is not available in gtk3. So how can I use that?

**Comment by cedlemo** [comment]
I have not tested it in a real script but the method seems to exist:

```
irb -r gdk3                                                                                                                                                      ~
irb(main):001:0> Gdk::Window.instance_methods.grep(/get_device_position/)
=> [:get_device_position, :get_device_position_double]
irb(main):002:0>
```

**Comment by arjunmenon** [comment]
Hey
Can you give an example of this. Generally we can do in gtk2, `app.win.pointer` to get mouse_x and mouse_y.
How do we use the GDK one over the app object?

**Comment by cedlemo** [comment]
You can find an example here:

https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gtk3/sample/gtk-demo/drawingarea.rb#L138

in the *gtk3/sample/* directory there are a lot of examples that will help you.
