### ISSUE TITLE
Can't install without sudo permissions

### ISSUE THREAD

**Issue by nPn-** [ruby-gnome/ruby-gnome#1234]
I am trying to install the gtk2 gem on a ruby 2.5.1 installation but cannot because of the use of native-package-installer which needs sudo permission on the system. Obtaining sudo permission is not an option in this case. The first problem I hit was cairo-gobject-devel, but there may be others.  In most cases I get past similar sudo requirement issues by compiling libraries to some non-system path and then adding those paths to my LD_LIBRARY_PATH, etc.   Is some way I can point to a non-system path rather than have the package installer try and install a package which it will never be able to install?
 
The system I am trying to build for is a rhel6 machine.

**Comment by kou** [comment]
You can use `PKG_CONFIG_PATH` for it.

**Comment by nPn-** [comment]
Thanks for the quick reply.
I am probably not doing this right. Here is what I did try to do:
I modified the cairo-gobject.pc file for the cairo-gobject-devel package (and created a link cairo-gobject-devel.pc to it) to use directories that I have write access to for `prefix exec_prefix libdir includedir` and set `PKG_CONFIG_PATH` to point to that file.
I ran `pkg-config --exists cairo-gobject`  and `pkg-config --exists cairo-gobject-devel` and got a rc=0.  but when I run ruby `extconf.rb`  it still tries to install the packages via `sudo yum` which I think makes sense since I don't think I told it any other way to install the package, just _where_ to install the package.

```
installing 'cairo-gobject-devel' native package... failed
Failed to run '/usr/bin/sudo -p \[sudo\]\ password\ for\ \%u\ to\ install\ \<cairo-gobject-devel\>:\  yum install -y cairo-gobject-devel'.
```

I think I am really close because it seems to only be complaining about that and this

```
installing 'gobject-introspection-devel' native package... failed
Failed to run '/usr/bin/sudo -p \[sudo\]\ password\ for\ \%u\ to\ install\ \<gobject-introspection-devel\>:\  yum install -y gobject-introspection-devel'.

```

Here is the end of the `extconf.rb` run
```
-----
Target libraries: glib2, pango, gtk2
Ignored libraries: gobject-introspection, gio2, cairo-gobject
-----
Done.
```

**Comment by kou** [comment]
You should not modify `cairo-gobject.pc` in cairo-gobject-devel package.
You just use the path where you specified for `--prefix` of built cairo.

If you built cairo with the followings:

```console
% ./configure --prefix=$HOME/local --enable-gobject
% make
% make install
```

You should specify `PKG_CONFIG_PATH` like the following:

```console
% PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig gem install cairo-gobject
```

**Comment by nPn-** [comment]
Thanks again kou,  I was able to get gem install to find cairo-gobject using the following
`gem install cairo-gobject -- --with-pkg-config=path_to_pkg_config_file`

however now the compile fails with the following

compiling rb-cairo-gobject.c
In file included from rb-cairo-gobject.h:28,
                 from rb-cairo-gobject.c:21:
.../jd/development/ruby-gtk2/ruby-gtk2-3.2.7/local_pkgs/usr/include/cairo/cairo-gobject.h:42:5: warning: "CAIRO_HAS_GOBJECT_FUNCTIONS" is not defined
..../jd/development/ruby-gtk2/ruby-gtk2-3.2.7/local_pkgs/usr/include/cairo/cairo-gobject.h:189:3: error: #error Cairo was not compiled with support for GObjectIn file included from rb-cairo-

Any suggestions?  I am willing to live with a reduced set of features if that's an option.

**Comment by kou** [comment]
You need to build cairo with `--enable-gobject` configure option.

**Comment by kou** [comment]
No response.
