### ISSUE TITLE
Not listed in GNOME gobject-introspection user doc. 

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome/ruby-gnome#1299]
I found this when I was trying to figure out what gobject-introspection is.
Maybe we should add ruby-gnome to GNOME gobject-introspection user doc. 
https://gi.readthedocs.io/en/latest/users.html
https://gitlab.gnome.org/GNOME/gobject-introspection/blob/master/docs/website/users.rst

**Comment by kojix2** [comment]
I think I should make a pull request, but how should I write it?

**Comment by kou** [comment]
```text
Ruby GNOME - Ruby bindings (runtime)
```text

**Comment by kojix2** [comment]
done.
