### ISSUE TITLE
undefined method `from_surface' for GdkPixbuf::Pixbuf:Class (NoMethodError)

### ISSUE THREAD

**Issue by yuntan** [ruby-gnome/ruby-gnome#1300]
Method `Gdk::Pixbuf.from_surface` to which [`gdk_pixbuf_get_from_surface`](https://developer.gnome.org/gdk3/stable/gdk3-Pixbufs.html#gdk-pixbuf-get-from-surface)  corresponds is not found.

I found [a test for the method](https://github.com/ruby-gnome/ruby-gnome/blob/f8be7c7b5752ddf83955bd9806a916e0b9dfbe90/gdk3-no-gi/test/test-gdk-pixbuf.rb#L43-L47), but it seems to be disabled.

**Comment by kou** [comment]
It's `surface.to_pixbuf` in gdk3 gem.

**Comment by yuntan** [comment]
Thank you 🙏.
