### ISSUE TITLE
Problem with Treeview inside Viewport inside ScrolledWindow

### ISSUE THREAD

**Issue by LutzLue** [ruby-gnome/ruby-gnome#1301]
With the code below, I get the following error. I do not have it if I leave the viewport away, but I am not sure if this really solves the problem.

>  $ ruby example.rb
> (example.rb:14415): Gdk-ERROR **: The program 'example.rb' received an X Window System error.
> This probably reflects a bug in the program.
> The error was 'BadAlloc (insufficient resources for operation)'.
>   (Details: serial 271 error_code 11 request_code 130 (MIT-SHM) minor_code 5)
>   (Note to programmers: normally, X errors are reported asynchronously;
>    that is, you will receive the error a while after causing it.
>    To debug your program, run it with the GDK_SYNCHRONIZE environment
>    variable to change this behavior. You can then get a meaningful
>    backtrace from your debugger if you break on the gdk_x_error() function.)
> Trace/breakpoint trap (core dumped)

```ruby
require 'gtk3'

treeview = Gtk::TreeView.new
viewport = Gtk::Viewport.new
scroll_win = Gtk::ScrolledWindow.new
content = Gtk::Grid.new
content.add(scroll_win)

# works if i add the treeview directly to scroll_win, but not with a viewport inbetween
scroll_win.add(viewport)
viewport.add(treeview)


window = Gtk::Window.new
window.add(content)
window.show_all

# create model
treestore = Gtk::TreeStore.new(String)

(0..6570).to_a.each do
  treestore.append(nil)
end

treeview.model = treestore
column = Gtk::TreeViewColumn.new('Title', Gtk::CellRendererText.new)
treeview.append_column(column)

Gtk.main
```

**Comment by kou** [comment]
You should not add `Gtk::TreeView` into `Gtk::Viewport` because `Gtk::TreeView` supports scrolling natively.

See also: https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#gtk-scrolled-window-add-with-viewport

> The viewport scrolls the child by moving its GdkWindow, and takes the size of the child to be the size of its toplevel GdkWindow. This will be very wrong for most widgets that support native scrolling; for example, if you add a widget such as GtkTreeView with a viewport, the whole widget will scroll, including the column headings. Thus, widgets with native scrolling support should not be used with the GtkViewport proxy.

**Comment by LutzLue** [comment]
Thank you very much!
