### ISSUE TITLE
Support passing nil when boolean argument is expected

### ISSUE THREAD

**Issue by mvz** [ruby-gnome/ruby-gnome#1305]
Currently, calling `Gtk::TreeViewColumn#set_visible` with `nil` will raise an error "the 0th argument must not nil: <visible>". However, `nil` is fine as a falsy value in Ruby. Please consider adjusting the check for nil arguments to allow them for boolean values.

Related: https://github.com/mvz/alexandria-book-collection-manager/issues/20

**Comment by kou** [comment]
OK. I've accepted the suggestion.

**Comment by mvz** [comment]
Thanks!
