### ISSUE TITLE
How to deliver a gem with GTK3?

### ISSUE THREAD

**Issue by simohakki** [ruby-gnome/ruby-gnome#1306]
How can I make an independent gem (which depends on gtk3) once I have completed a development? do I need to deliver msys2 too?
My environment:

windows 10
ruby 2.4.5
my_gem depends on gtk3 gem
msys2

**Comment by kou** [comment]
Users of your gem need to install Ruby, MSYS2, your gem and depended gems.
They can install them by RubyInstaller (Ruby+Devkit + https://rubyinstaller.org/downloads/ ) and `gem install your-gem`.
(Or they can use Chocolatey: https://chocolatey.org/packages/ruby and https://chocolatey.org/packages/msys2 )

**Comment by rubyFeedback** [comment]
Just use WSL1 - it works very well. You can also watch libui - kojix2 is working on making the ruby bindings better. This should solve these issues, but ruby-gtk on windows does work too. It's more cumbersome for end-users, though.
