### ISSUE TITLE
selection handler triggers many events

### ISSUE THREAD

**Issue by LutzLue** [ruby-gnome/ruby-gnome#1310]
The below code is a showcase of a problem I have with keeping the GUI responsive while having long lasting operations in my selection handler. The biggest problem are all the events that have to be processed when the handler runs for the first time, directly after the window showed up.
The order in which selection handlers finish might be a problem, too, but that's for later. :)

1. If I click the first and the second row immediately after the window showed up I get:

> starting  selection handler call no. 1
> starting  selection handler call no. 2
> finishing selection handler call no. 2 after giving time to 723 events + events called inbetweeen
> result: you selected 1 ####################################################################################################
> finishing selection handler call no. 1 after giving time to 155 events + events called inbetweeen
> result: you selected 0 ####################################################################################################

I am only giving time to pending events to keep the GUI responsive, but where do all these events come from that keep my handler from finishing? Is there a way to block them?

2. If I wait some time after the window showed up and click the first and the second row i get:

> starting  selection handler call no. 1
> starting  selection handler call no. 2
> finishing selection handler call no. 2 after giving time to 27 events + events called inbetweeen
> result: you selected 1 ####################################################################################################
> finishing selection handler call no. 1 after giving time to 14 events + events called inbetweeen
> result: you selected 0 ####################################################################################################

Looks better. The events got processed in the meantime, but you should not have to wait.

Where do all these events come from. Is there a way to block them?

3. If I comment out the `while Gtk.events_pending?`-part I get:

> starting  selection handler call no. 1
> finishing selection handler call no. 1 after giving time to 0 events + events called inbetweeen
> result: you selected 0 ####################################################################################################
> starting  selection handler call no. 2
> finishing selection handler call no. 2 after giving time to 0 events + events called inbetweeen
> result: you selected 1 ####################################################################################################

Everything is correct order but GUI is far from responsive.

------

```
require 'gtk3'

# each of these constants influence the number of events emitted
ROW_COUNT = 50_000
STRING_LENGTH = 100

class NumberSelect
  def initialize
    # setup widgets
    window = Gtk::Window.new
    window.resize(1024,768)
    scrolled_window = Gtk::ScrolledWindow.new
    treeview = Gtk::TreeView.new
    treeview.append_column(Gtk::TreeViewColumn.new(nil, Gtk::CellRendererText.new, :text => 0))
    window.add(scrolled_window)
    scrolled_window.add(treeview)
    window.show_all
    window.keep_above = true

    # create string with length = STRING_LENGTH
    string_with_length = ''
    STRING_LENGTH.times do
      string_with_length += '#'
    end

    # add files to treemodel
    store = Gtk::ListStore.new(String)
    (0..ROW_COUNT).each do |i|
      iter = store.append
      iter[0] = "#{i.to_s} #{string_with_length}"
    end
    treeview.model = store

    # connect selection handler
    @call_counter = 0
    treeview.selection.signal_connect('changed') do |sel|
      @call_counter += 1
      call_no = @call_counter.dup
      puts "starting  selection handler call no. #{call_no}"
      event_counter = 0
      iter = sel.selected

      (1..10).each do
        # Some slow operations which can't be handled in another thread.
        # (treeview.model.append operations in our actual code)
        sleep(0.3)

        # Give GTK some time to keep GUI reactive
        while Gtk.events_pending?
          event_counter += 1
          Gtk.main_iteration
        end
      end

      puts "finishing selection handler call no. #{call_no} after giving time to #{event_counter} events + events called inbetween"
      puts "result: you selected #{iter[0]}" if iter
    end
  end
end

NumberSelect.new
Gtk.main
```

**Comment by kou** [comment]
We need runnable reproduce code.

**Comment by LutzLue** [comment]
> We need runnable reproduce code.
Sorry, I must have ommited the last two lines. I edited the above code and it should run now.

**Comment by kou** [comment]
How about just doing GTK related operations in `GLib::Idle.add {}`?

```ruby
require 'gtk3'

# each of these constants influence the number of events emitted
ROW_COUNT = 50_000
STRING_LENGTH = 100

class NumberSelect
  def initialize
    # setup widgets
    window = Gtk::Window.new
    window.resize(1024,768)
    scrolled_window = Gtk::ScrolledWindow.new
    treeview = Gtk::TreeView.new
    treeview.append_column(Gtk::TreeViewColumn.new(nil, Gtk::CellRendererText.new, :text => 0))
    window.add(scrolled_window)
    scrolled_window.add(treeview)
    window.show_all
    window.keep_above = true

    # create string with length = STRING_LENGTH
    string_with_length = ''
    STRING_LENGTH.times do
      string_with_length += '#'
    end

    # add files to treemodel
    store = Gtk::ListStore.new(String)
    (0..ROW_COUNT).each do |i|
      iter = store.append
      iter[0] = "#{i.to_s} #{string_with_length}"
    end
    treeview.model = store

    # connect selection handler
    @call_counter = 0
    treeview.selection.signal_connect('changed') do |sel|
      @call_counter += 1
      call_no = @call_counter.dup
      puts "starting  selection handler call no. #{call_no}"
      event_counter = 0
      iter = sel.selected

      (1..10).each do |j|
        Thread.new do
          # Some slow operations which can't be handled in another thread.
          # (treeview.model.append operations in our actual code)
          sleep(0.3)

          GLib::Idle.add do
            new_iter = treeview.model.append
            new_iter[0] = "#{call_no}: #{j}: New"
            GLib::Source::REMOVE
          end
        end
      end

      puts "finishing selection handler call no. #{call_no} after giving time to #{event_counter} events + events called inbetween"
      puts "result: you selected #{iter[0]}" if iter
    end
  end
end

NumberSelect.new
Gtk.main
```

**Comment by LutzLue** [comment]
Wow! Works like a charm. Thank you! :)
