### ISSUE TITLE
[Gtk2 gem] Possible a small problem in the file: sample/misc/pangorenderer.rb -> "uninitialized constant Pango::Renderer::PART_FOREGROUND"

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1311]
Hello there,

I am having a small problem with the following **file** in the **gtk2 gem**:

    sample/misc/pangorenderer.rb

There is the following code that **fails**, from that file:

    renderer.set_override_color(Pango::Renderer::PART_FOREGROUND, color)

When running this file, it fails via "**uninitialized constant Pango::Renderer::PART_FOREGROUND**":

    ruby sample/misc/pangorenderer.rb

    sample/misc/pangorenderer.rb:54:in `block (2 levels) in <main>': uninitialized constant Pango::Renderer::PART_FOREGROUND

    Did you mean?  Pango::AttrForeground
         from sample/misc/pangorenderer.rb:50:in `each'
         from sample/misc/pangorenderer.rb:50:in `block in <main>'
         from sample/misc/pangorenderer.rb:66:in `main'
         from sample/misc/pangorenderer.rb:66:in `<main>'

I am not sure what has changed, if anything has changed; perhaps
it is a problem on my home system too, I can not say. (I have
both gtk2 and gtk3, and also both gems, so I kind of "switch"
when necessary.)

If there was an internal change, e. g. for Pango::Renderer::PART_FOREGROUND
then perhaps that could be fixed. It may also be useful to perhaps
add some kind of "special" symbols, such as :pango_part_foreground
or :pango_foreground, but I can understand if this has to be 
thought through, if it is to be used for the whole code base.

For sake of completion, my system is this:

    Operating system: Linux
    Pango version:    1.44.7
    Gtk2 version:     2.24.32
    Atk version:      2.34.1
    Glib version:    2.62.4

(All compiled from source and working fine here otherwise.)

Thanks!

**Comment by kou** [comment]
Thanks for your report.
I've added `Pango::Renderer::PART_*` with deprecation for backward compatibility.
