### ISSUE TITLE
Problem with gtk3: my ruby code seems to be ignored

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1312]
Hello ruby-gnome folks,

Consider the following code in ruby-gtk2:

    require 'gtk2'

    module Gtk

    class Button

    def on_clicked(&block)
      self.signal_connect(:clicked) {
        block.call
      }
    end

    end; end
    window = Gtk::Window.new
    button = Gtk::Button.new 'Hello world button'
    button.on_clicked { puts 'Hello world!' }
    window.add(button)
    window.show_all
    Gtk.main

The above code works (for me at the least). A window opens and
a button is there, which will print out Hello world! upon click event.

What I did here was to add a method called on_clicked to module
Gtk; class Button.

Now, the VERY same code does NOT work in ruby-gtk3:

    require 'gtk3'

    module Gtk

    class Button

    def on_clicked(&block)
      self.signal_connect(:clicked) {
        block.call
      }
    end

    end; end
    window = Gtk::Window.new
    button = Gtk::Button.new 'Hello world button'
    button.on_clicked { puts 'Hello world!' }
    window.add(button)
    window.show_all
    Gtk.main

The following error is shown on the commandline:

    /home/Programs/Ruby/2.7.0/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:216: warning: already initialized constant Gtk::Button
    test_fail.rb:5: warning: previous definition of Button was here
    test_fail.rb:17:in `new': 'Gtk::Button#initialize(label_or_stock_id, use_underline = nil)' style has been deprecated. Use 'Gtk::Button#initialize(:label => nil, :use_underline => nil, :stock_id => nil)' style.
Traceback (most recent call last):
    test_fail.rb:18:in `<main>': undefined method `on_clicked' for #<Gtk::Button:0x26a0d90 ptr=0x2d02180> (NoMethodError)
    Did you mean?  clicked

I do not understand the code in gobject-introspection/loader.rb but the more serious issue appears
to be that my ruby code where I added the method "on_clicked" to class Button is completely
ignored. This makes it difficult for me to transition into gtk3.

I am not sure if the above is a bug or not, but what surprises me is that the code above works
fine on gtk2, but it does not work on gtk3 at all. Perhaps I forgot to add something, type_register
perhaps? Or anything else ... if this is the case, could perhaps be the message more clear
what to do? For example, the message:

    test_fail.rb:17:in `new': 'Gtk::Button#initialize(label_or_stock_id, use_underline = nil)' style has been deprecated. Use 'Gtk::Button#initialize(:label => nil, :use_underline => nil, :stock_id => nil)' style.

is a bit annoying, but it is also helpful, and I can adjust to it. I can write wrapper code too, to check for "if is gtk2" and "if is gtk3", so it is just a warning that I can work with. The other part, though, where my 
modification is ignored, I can not seem to work around since a lot of my old ruby-gtk code is gtk2-specific
and has numerous modifications to the whole "module Gtk" actually. So porting this is not even a lot of
work but right now not possible.

I only glanced briefly at the code in gobject-introspection/loader.rb. If I understood the code correctly
then it loads up all the various classes. This may be ok, but then I wonder why my own code in ruby where I modify class Button, is ignored. Doesn't this qualify as a bug?

Anyway, just reporting it here so that people more familiar with gtk3 can look whether there is some problem - if possible, commandline help may be useful too, e. g. telling users how to move to gtk3 specifically, just like the other message does already.

Actually if I look at this again:

    /home/Programs/Ruby/2.7.0/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:216: warning: already initialized constant Gtk::Button
    test_fail.rb:5: warning: previous definition of Button was here

Then it is weird that there is a "previous definition of Button". Should not:
    require 'gtk3'
be evaluated BEFORE any custom ruby code? Perhaps it is quite dynamic right now, but I don't think custom modifications should be discarded, ever. I don't know of a simple way how to keep modifications to a ruby class, and attach it lateron. Perhaps that may be a new feature for ruby core to suggest - but I believe that either way, it makes no real sense that my ruby code is ignored.

Thank you for reading.

.

**Comment by kou** [comment]
Add `Gtk.init` after `require 'gtk3'`:

```ruby
require 'gtk3'

Gtk.init

module Gtk

class Button

def on_clicked(&block)
  self.signal_connect(:clicked) {
    block.call
  }
end

end; end
window = Gtk::Window.new
button = Gtk::Button.new 'Hello world button'
button.on_clicked { puts 'Hello world!' }
window.add(button)
window.show_all
Gtk.main
```

gtk3 initializes automatically when gtk3 are constants or functions are referred. So adding `Gtk::Button` after `require 'gtk3'` also works:

```ruby
require 'gtk3'

Gtk::Button

module Gtk

class Button

def on_clicked(&block)
  self.signal_connect(:clicked) {
    block.call
  }
end

end; end
window = Gtk::Window.new
button = Gtk::Button.new 'Hello world button'
button.on_clicked { puts 'Hello world!' }
window.add(button)
window.show_all
Gtk.main
```

`module Gtk; class Button; ...; end; end` doesn't refer `Gtk::Button`. So gtk3 isn't initialized automatically.

BTW, normally, you should not extend gtk3 classes directly. If you know what you do, you can do it. :-)
