### ISSUE TITLE
3.4 does not exist in sourceforge

### ISSUE THREAD

**Issue by ncaq** [ruby-gnome/ruby-gnome#1313]
I write [ncaq/ncaq-overlay: ncaq personal gentoo overlay](https://github.com/ncaq/ncaq-overlay).
I want to ruby-gtk2-3.4.1.
I copy script file from `ruby-gtk2-3.3.2.ebuild`.
But it is failed.
Because ruby gnome2 3.4 dose not exist in [Ruby-GNOME 2 - Browse Files at SourceForge.net](https://sourceforge.net/projects/ruby-gnome2/files/).
ruby-gnome project drop sourceforge?
However, [FrontPage - Ruby-GNOME2 Project Website](https://ruby-gnome2.osdn.jp/) `Download` link to [Ruby-GNOME 2 - Browse Files at SourceForge.net](https://sourceforge.net/projects/ruby-gnome2/files/)

It problem too cause to gentoo official ebuild.
Because <https://github.com/gentoo-mirror/gentoo/blob/5446172496b80456dd9f895874372c36dd1e7a6b/eclass/ruby-ng-gnome2.eclass#L47> is to download from sourceforge.
So new ruby gnome2 is unable.

**Comment by kou** [comment]
We dropped support for `.tar.gz` distribution.
Please use the standard `.gem`.

Could you report it to Gentoo?

**Comment by ncaq** [comment]
Thank you.
I'm not a Gentoo maintainer, so I don't know if I can communicate well, but I think this makes it easier to understand the policy.
However, in that case, I think that it is less confusing to remove the download link on the official website.

**Comment by kou** [comment]
>  However, in that case, I think that it is less confusing to remove the download link on the official website.

Could you show where the link exists?

**Comment by ncaq** [comment]
![Screen Shot 2020-01-22 at 18 07 33-fullpage](https://user-images.githubusercontent.com/2913112/72880470-5451bc00-3d42-11ea-8ebe-3126240c472e.png)
[FrontPage - Ruby-GNOME2 Project Website](https://ruby-gnome2.osdn.jp/)

**Comment by kou** [comment]
Thanks. Removed.
