### ISSUE TITLE
Pango-CRITICAL when passing invalid markup on Pango 3.6.9+

### ISSUE THREAD

**Issue by knarewski** [ruby-gnome/ruby-gnome#1315]
## Summary 
After bumping Pango version from `3.3.6` to `3.4.1` the Ruby process occasionally started crashing on `Pango#parse_markup` with segmentation fault (Ruby 2.7, Ubuntu 14.04). Just to make sure it's not an OS-related edge case I've tried to reproduce it in isolation on 18.04. Although it didn't crash Ruby this time, it consistently kept showing the following error:
```
Pango-CRITICAL **: pango_attr_list_unref: assertion 'list->ref_count > 0' failed
  from /usr/local/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.3.9/lib/gobject-introspection/loader.rb:598:in `invoke'
  from /usr/local/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.3.9/lib/gobject-introspection/loader.rb:103:in `block in define_singleton_method'
  from /usr/local/lib/ruby/gems/2.7.0/gems/pango-3.3.9/lib/pango/markup.rb:23:in `parse_markup'
  (...)
```

Then it raised `GLib::Error` as expected
```
GLib::Error (Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;)
```

The problem seems to have been introduced in `3.3.9`.

### Files
Dockerfile
```dockerfile
FROM ruby:2.7
RUN apt-get update
RUN gem install pango -v '3.3.9'
```

docker-compose.yml
```yaml
version: '3'
services:
  app:
    build: .
```

### Steps
1. Enter the irb within the container
```shell
docker-compose run app irb
```

2. Require pango and parse invalid markup
```ruby
require 'pango'
Pango.parse_markup('&')
```

### Other
Not sure if C stacktrace from Ubuntu 14.04 can be relevant, happy to include it if needed (it's super long though). 

Last but not least, thank you for the amazing work of maintaining those bindings!

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.
