### ISSUE TITLE
GOffice test is unnecessary skiped

### ISSUE THREAD

**Issue by naota** [ruby-gnome/ruby-gnome#1316]
The following line in the test requires "libgoffice-0.10.27" or later to run the test.

https://github.com/ruby-gnome/ruby-gnome/blob/master/goffice/test/test-data-scalar-str.rb#L21

But, as shown in the CI result, the test is skipped even if we have a newer libgoffice is installed.

libgoffice-0.10.44 is installed:
https://travis-ci.org/ruby-gnome/ruby-gnome/jobs/646758638#L3660

The test is omitted.
https://travis-ci.org/ruby-gnome/ruby-gnome/jobs/646758638#L3785

This happens because the above code is trying to compare an "API version"  (0.10)and a "Release version" (0.10.27). Since, the "minor" part of the "API version" is always 0, the compare always fails.

Further detail:

The namespace version is set as GOFFICE_API_VER. It is made from "goffice_version_epoch.goffice_version_major" so it does not contain "minor" in the API version string.

https://gitlab.gnome.org/GNOME/goffice/blob/master/goffice/Makefile.am#L8
https://gitlab.gnome.org/GNOME/goffice/blob/master/configure.ac#L57

**Comment by kou** [comment]
Oh, it seems that we need to send a merge request to make `GO_VERSION_*` constants in `goffice/goffice-features.h` introspectable by GObject Introspection to GOffice.

**Comment by kou** [comment]
We need to work on upstream not here.
