### ISSUE TITLE
load_uri(TestWebKit2GtkWebView::#load_uri) test failure with newer webkit

### ISSUE THREAD

**Issue by seb128** [ruby-gnome/ruby-gnome#1389]
Since the webkit2gtk 2.27.91/2.28 updates the test fails in Ubuntu

Log on https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-focal/focal/ppc64el/r/ruby-gnome/20200312_090745_44c87@/log.gz
```

Failure: test: #load_uri(TestWebKit2GtkWebView::#load_uri):
  <true> expected but was
  <false>
/tmp/autopkgtest.1hggva/build.Hv7/src/webkit2-gtk/test/test-webkit2-gtk-web-view.rb:106:in `block (2 levels) in <class:TestWebKit2GtkWebView>'
     103:       @view.load_uri(http_url)
     104:       loop.run
     105: 
  => 106:       assert_true(loaded)
     107:     end
     108:   end
     109: end
```

**Comment by kou** [comment]
Thanks for your report.
But I couldn't reproduce this with ubuntu:20.04 Docker image because the Ubuntu 20.04 image doesn't ship libwebkit2gtk-4.0-dev 2.28.

**Comment by lucaskanashiro** [comment]
@kou you need to add `focal-proposed` to your apt sources list, if you check this link you will see the version `2.28.0-1ubuntu1` there: https://launchpad.net/ubuntu/+source/webkit2gtk

This test failure is one of the reasons that `webkit2gtk` is not in the Ubuntu 20.04 default repository yet: https://people.canonical.com/~ubuntu-archive/proposed-migration/update_excuses.html#webkit2gtk

**Comment by seb128** [comment]
Sorry for the delay following up there, I finally had some time to poke at that. The issue is specific to ppc64el builds and in fact is failing because webkitgtk is busted on that architecture. Closing the report here, the test worked as intended a did catch a real regression

**Comment by kou** [comment]
No problem.
