### ISSUE TITLE
sample\gtk-demo not working

### ISSUE THREAD

**Issue by Itamar-Gozlan** [ruby-gnome/ruby-gnome#1390]
I am running on windows 10 with ruby 2.6.5
when I tried running the gtk-demo I get the following error:
“gtk3/ruby-gnome/gtk3/sample/gtk-demo/demo.gresource”: open() failed: No such file or directory (GLib::FileError)"
indeed demo.gresource without other extension didn't work

what I did:
creating a new folder and did git clone
opened cmd in gtk-demo dir
typed: ruby main.rb

please let me know if you need any more information

**Comment by kou** [comment]
Could you try `ridk exec ruby main.rb`?

**Comment by kojix2** [comment]
`glib-compile-resources`
https://github.com/ruby-gnome/ruby-gnome/blob/9a9d1c51675f98d4748587bb82fcd9d5eb4485af/gtk3/sample/gtk-demo/main.rb#L28-L31

**Comment by Itamar-Gozlan** [comment]
Thank you for you're response
from main.rb:
```
gresource_bin = "#{current_path}/demo.gresoucre"
gresource_xml = "#{current_path}/demo.gresource.xml"
```
but ```gtk3/ruby-gnome/gtk3/sample/gtk-demo/demo.gresoucre``` can't be found
there isn't a file with this name also in the repository
after running  ```ridk exec ruby main.rb``` demo.gresoucre was created but I get the same error:
```open() failed: No such file or directory (GLib::FileError)"```

**Comment by kojix2** [comment]
Does this example show the same error?

https://github.com/ruby-gnome/ruby-gnome/tree/master/gtk3/sample/tutorial/exampleapp2

**Comment by Itamar-Gozlan** [comment]
Yes, it gives the same error
```open() failed: No such file or directory (GLib::FileError)```

**Comment by kojix2** [comment]
After checking that `glib-compile-resources` or `glib-compile-resources.exe` works on the terminal

```
glib-compile-resources --version
```
```
ridk exec glib-compile-resources --version
```

Try to compile your resource manually.

```
cd ruby-gnome\gtk3\sample\tutorial\exampleapp2 
glib-compile-resources.exe --target a.gresource --sourcedir . exampleapp.gresource.xml
```
`a.gresource` is generated in the directory.

Then check if you can load the `a.gresource` .

`irb -r gio2` or `pry -r gio2`

```
Gio::Resource.load("a.gresource")
```

If you still get the same errors, maybe @kou will help you.

**Comment by Itamar-Gozlan** [comment]
```glib-compile-resources --version``` did not work and result in ```not recognized``` error
```ridk exec ruby main.rb``` running from PowerShell worked
thank you very much for you help
