### ISSUE TITLE
system ruby and gem install gtk3

### ISSUE THREAD

**Issue by xetum** [ruby-gnome/ruby-gnome#1392]
I'm using system ruby:
`ruby 2.5.5p157 (2019-03-15 revision 67260) [arm-linux-gnueabihf]`
on RPi3B+ (raspbian buster) and to succeed with `sudo gem install gtk3`
I've had to install dependencies manually, i.e:

`sudo apt install libgirepository1.0-dev libgtk-3-dev`

Why? `gtk3-3.4.1/ext/gtk3/extconf.rb` is suposed to take care of dev dependencies, isn't it?

FOUND: `native-package-installer` doesn't detect raspbian (a debian derivative) in "1.1.0" version

`native-package-installer` "1.0.6", `debian.rb`:

        def current_platform?
          File.exist?("/etc/debian_version")
        end

It works well, but...

`native-package-installer` "1.1.0", ' debian.rb`:

        def current_platform?
          return false unless File.exist?("/etc/os-release")
          File.readlines("/etc/os-release").any? do |line|
            line.chomp == "ID=debian"
          end
        end

but `/etc/os-release`in raspbian is:

    PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
    NAME="Raspbian GNU/Linux"
    VERSION_ID="9"
    VERSION="9 (stretch)"
    ID=raspbian
    ID_LIKE=debian
    HOME_URL="http://www.raspbian.org/"
    SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
    BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

@kou, can you replace `line.chomp == "ID=debian"`by `line.chomp == "ID_LIKE=debian"`? (or create a new Raspbian platform). Thanks

**Comment by kou** [comment]
Could you report this to https://github.com/ruby-gnome/native-package-installer ?
