### ISSUE TITLE
animate SVG elements in Ruby Gtk3 : advices ?

### ISSUE THREAD

**Issue by JC-LL** [ruby-gnome/ruby-gnome#1394]
First, I'd like t thank you especially for your work on Ruby GTK / Gnome. That is awesome !

I'd like your advice about the following : I would like to animate SVG elements in Ruby Gtk3, programmatically (I need to animate complex technical SVG drawings). No CSS or whatever, just pure SVG, also without any web browser. 

I have clear ideas concerning the (ruby) animation/simulation engine itself (event-driven simulator or cycle-based), but I feel less confident regarding the "continuous" update of the SVG elements, based on their ID. This requires quite a lot of work, starting by the xml parsing to detect the SVG elements that require an update during simulation.

Maybe it is simple for you. How would you proceed ? Is there a sketch of such thing around ? Does this remains in the scope of rub-gnome project ?

**Comment by kou** [comment]
If you can compute all frames before you render, you can use `GdkPixbuf::PixbufSimpleAnim` and `Gtk::Image`:

```ruby
require "gtk3"
require "rsvg2"

animation = GdkPixbuf::PixbufSimpleAnim.new(200, 200, 20)
(0..200).each do |x|
  svg = <<-SVG
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
  <rect x="#{x}" y="10" width="100" height="100"/>
</svg>
  SVG
  handle = Rsvg::Handle.new(data: svg)
  animation.add_frame(handle.pixbuf)
end
animation.loop = true

app = Gtk::Application.new
app.signal_connect(:activate) do
  window = Gtk::ApplicationWindow.new(app)
  image = Gtk::Image.new(animation: animation)
  window.add(image)
  window.show_all
end
app.run
```

But this may need large memory because you need raw data for all frames in memory.

(I'll show another approach later.)

**Comment by kou** [comment]
Another approach that uses CSS:

```ruby
require "gtk3"
require "rsvg2"

svg = <<-SVG
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
  <rect id="rectangle" x="0" y="10" width="100" height="100"/>
</svg>
SVG
handle = Rsvg::Handle.new(data: svg)

app = Gtk::Application.new
app.signal_connect(:activate) do
  window = Gtk::ApplicationWindow.new(app)
  drawing_area = Gtk::DrawingArea.new
  drawing_area.signal_connect(:draw) do |_drawing_area, context|
    style_context = drawing_area.style_context
    width = drawing_area.allocated_width
    height = drawing_area.allocated_height
    Gtk.render_background(style_context, context, 0, 0, width, height)
    context.show_rsvg_handle(handle)
    false
  end
  x = 0.step(200, by: 10).cycle
  r = 0.step(255, by: 20).cycle
  GLib::Timeout.add(100) do
    css = <<-CSS
#rectangle {
  fill: #{"#%02x0000" % r.next};
}
    CSS
    handle.stylesheet = css
    drawing_area.queue_draw
    GLib::Source::CONTINUE
  end
  window.add(drawing_area)
  window.show_all
end
app.run
```

This requires Ruby-GNOME 3.4.2 or later.

**Comment by JC-LL** [comment]
Thanks for the two examples ! 
No easy possibility to  modify attributes based on individual IDs ? That is : pick a SVG element marked by its ID, modify this SVG object/part and iterate ? I will try something and keep you informed. Thx again !

**Comment by kou** [comment]
You need to use a XML parser such as REXML, regenerate a new SVG and render it with `Gtk::Imag` approach. 
You can use `#${ID} {...}` syntax with CSS approach.
