### ISSUE TITLE
NotImplementedError (TODO: [attr] in Ruby -> GIArgument(interface)[struct][void][everything])

### ISSUE THREAD

**Issue by knarewski** [ruby-gnome/ruby-gnome#1396]
Hello, thank you very much for your hard work on gnome bindings! I recently encountered a following error when using Pango:
```
NotImplementedError (TODO: [attr] in Ruby -> GIArgument(interface)[struct][void][everything])
```

## Reproduction steps:

```ruby
require 'pango'
attrlist = Pango::AttrList.new
attribute = Pango::AttrSize.new(10)
attrlist.change(attribute)
```

### Environment for completenes:

* Dockerfile:
```dockerfile
FROM ruby:2.7
RUN apt-get update
RUN gem install pango -v '3.4.3'
```

* docker-compose.yml:
```yml
version: '3'
services:
  app:
    build: .
```

Code can be ran from `docker-compose run app irb`.

## Workaround

Currently my best bet is to recreate `AttrList` from scratch, if anyone knows a better workaround, it would be great to hear about it!

**Comment by knarewski** [comment]
I ended up using `Pango::AttrList#insert` instead. It appears to correctly override the previous attribute - when iterating through list, the old attribute is not present any more. There is no mention about overriding in Pango docs, so to avoid potential issues I remove the previous attribute using `Pango::AttrList#filter` before inserting the new one.

This approach does not work exactly like `Pango::AttrList#change`, but works for my use case. Hope that will help others facing this issue.

**Comment by kou** [comment]
Sorry for not working on this.
I've fixed it.
