### ISSUE TITLE
Gtk ProgressBar issue

### ISSUE THREAD

**Issue by OSXLich-Doug** [ruby-gnome/ruby-gnome#1401]
Converting gtk2 ruby scripts to gtk3 for a small community.

Relatively unschooled in this stuff - so please forgive if already asked / answered or should have looked elsewhere.

gtk3 progress bars do not overlay the text onto the progress bar similar to gtk2

gtk3 reports error in Gtk.queue: 'overlay' is not a valid property name

holds true for gtk3 back to version 3.3.8 (was trying to find most recent that retained 'overlay' as a property.)

Can this be restored?  If not, last known version to work with 'overlay' in gtk3?  Or preferred method going forward for progress bars with text overlaid in bar trough?

Thank you for consideration in advance.

**Comment by kou** [comment]
Could you provide the gtk2 version script and the gtk3 version (not working) script that can be run on my environment?

**Comment by OSXLich-Doug** [comment]
I can provide a script that shows the problem (text is not centered IN the progress bar).  I create the 'overlay' error by attempting to pass overlay in the CSS provider.  That is likely my mistake.  Appending two files to demonstrate the text not being in the trough, and amending question - how do we put the text in the progress bar trough, instead of over the progress bar?

Thanks for your first rapid response.  Very appreciated.


[gtk2pb.rb.txt](https://github.com/ruby-gnome/ruby-gnome/files/4956465/gtk2pb.rb.txt)
[gtk3pb.rb.txt](https://github.com/ruby-gnome/ruby-gnome/files/4956466/gtk3pb.rb.txt)

**Comment by kou** [comment]
How about using `Gtk::Overlay` and `min-height` CSS style?

```ruby
require 'gtk3'

win = Gtk::Window.new('Sample')
win.signal_connect('destroy') { Gtk.main_quit }

box = Gtk::Box.new(:vertical)

overlay = Gtk::Overlay.new
pb = Gtk::ProgressBar.new
pb.set_fraction(0.5)
# pb.text = ("Something going on. . . ")
# pb.set_show_text(true)
provider = Gtk::CssProvider.new
provider.load(data: <<-CSS)
trough,
progress
{
  min-height: 30px;
}
CSS
pb.style_context.add_provider(provider, Gtk::StyleProvider::PRIORITY_USER)
overlay.add(pb)

label = Gtk::Label.new("Something going on. . . ")
overlay.add_overlay(label)

b = Gtk::Button.new(label: 'Button')
b.signal_connect('clicked') do
  Thread.new do
    5.times do |i|
      sleep 1
      pb.fraction = (i + 1) / 5.0
    end
  end
end

win.add box
box.pack_start overlay
box.pack_start b

win.show_all

Gtk.main
```

**Comment by OSXLich-Doug** [comment]
Absolutely perfect, and thank you for the coaching, Kou.  I regret that I did not come across this in my journey and appreciate you taking the time to point me to it.  (Non-) issue closed.  Best wishes!
