### ISSUE TITLE
error installing cairo-gobject in ruby 2.7.1p83 on windows

### ISSUE THREAD

**Issue by dsisnero** [ruby-gnome/ruby-gnome#1402]
C:\Users\Dominic E Sisneros\source\repos\ruby\try_arrow>ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]

gem_make_out  https://gist.github.com/dsisnero/be422299cce53404e81e5356c58c87a0

mkmf.log https://gist.github.com/dsisnero/38af37a05c83fde410a21410eb03e2fe

**Comment by kou** [comment]
This is the cairo gem problem not the cairo-gobject gem.
I've fixed the problem. Could you try again?

**Comment by dsisnero** [comment]
Thank you!  It is fixed
