### ISSUE TITLE
require gtk3 with an open class ?

### ISSUE THREAD

**Issue by JC-LL** [ruby-gnome/ruby-gnome#1403]
Hello,

This code raises an exception. I don't understand why.

Thx for the advices
JCLL

```
require 'gtk3'
require_relative 'open_array'
window=Gtk::Window.new
window.set_title 'test'
window.show_all
Gtk.main
```

with 'open_array.rb'  

```
class Array
 def +(other)
    res=[]
    each_with_index do |e,i|
      res[i]=e+other[i]
    end
    return res
  end
end
```

produces : 
/open_array.rb:6:in `+': no implicit conversion of nil into String (TypeError)

**Comment by kou** [comment]
Because gtk3 gem uses `Array#+`.
If you want to change the original `Array#+` behavior, you can't use gtk3 gem.
