### ISSUE TITLE
SystemExit shadowing exceptions in signal_connect handler

### ISSUE THREAD

**Issue by md-work** [ruby-gnome/ruby-gnome#1404]
If an exception is thrown in a signal_connect handler, GTK replaces it with a `SystemExit` exception.
This shadows the original exception which might be a big problem.

Is there a way to disable this exception shadowing?
So the example below would display `caught exception (RuntimeError): exception with important information` instead.

&nbsp;

```ruby
window = Gtk::Window.new
button = Gtk::Button.new(label: 'raise exception')
button.signal_connect 'clicked' do
  raise 'exception with important information'
end
window.add(button)
window.show_all

begin
  Gtk.main
rescue Exception => ex
  puts("caught exception (#{ex.class}): #{ex}")
  # => caught exception (SystemExit): exit
end
```

&nbsp;

The only workaround I found is to place an generic ensure or rescue in every signal_connect. But that's quite annoying.
```ruby
$current_exception = nil

window = Gtk::Window.new
button = Gtk::Button.new(label: 'raise exception')
button.signal_connect 'clicked' do
  begin
    raise 'exception with important information'
  ensure
    $hidden_exception = $!
  end
end
window.add(button)
window.show_all

begin
  Gtk.main
rescue Exception => ex
  ex = $hidden_exception if $hidden_exception
  puts("caught exception (#{ex.class}): #{ex}")
  # => caught exception (RuntimeError): exception with important information
end
```

**Comment by md-work** [comment]
What do you think about this solution?

```ruby
Gtk::Widget.instance_methods  # initialize Gtk binding
class Gtk::Widget
  def safe_signal_connect(*args, &block)
    signal_connect(*args) do
      begin
        block.call
      rescue => ex
        $current_exception = ex
        Gtk.main_quit
      end
    end
  end
end

# [...]

# everywhere Gtk.main is being called
Gtk.main
raise $current_exception if $current_exception
```

As far as I can see, other stuff like `GLib::Timeout.add` isn't replacing exceptions with SystemExit. So `Gtk::Widget` should be enough.

**Comment by kou** [comment]
It's not safe.
`signal_connect`'s expected return value is depends on signal. `Gtk.main_quit` always returns `nil`. If wrong return value is returned from signal connect handler, C library that invokes the handler may be crashed.

You must handle exception in each handler properly.

BTW, what do you want to do on error in handlers? Why do you re-raising the exception raised in handlers after `Gtk.main` in your examples?

**Comment by md-work** [comment]
My actual codebase was using the wxruby Gem (wx widgets gui) and it's currently being ported to Gtk-3.
In that codebase, sometimes exceptions are being thrown inside signal handlers (some for not so clean control flow, other just when something crashes).

In all scenarios the application must not crash. So there's code in the application which rescues those exceptions and either knows how to handle specific exceptions or logs / displays the exceptions content.
For this it's essential to get the original exception and not just always a SystemExit.

&nbsp;

As far as I can see my example returns the block's return value. Except there's a raise, in which case there's no return value from block. It doesn't makes sense to me how this is a problem. Can you explain more in detail?
```ruby
signal_connect(*args) do
      begin
        block.call
      rescue => ex
        $current_exception = ex
        Gtk.main_quit
      end
    end
```

**Comment by md-work** [comment]
@kou 
Interesting, I didn't know that `exit` acutally throws an `SystemExit` exception.

So I'll rephrase what I'm looking for:

&nbsp;

Usually an exception just goes down the stack until it reaches a rescue meant to stop it.
Example stack:
```
42. `raise Foobar` method (top of stack)
41. intermediate methods
...
23. `rescue Foobar` method
22. other methods
...
```
An Foobar exception raised in 42 will take all methods from stack until 23 is being reached. And method 23 will finally rescue the exception.

&nbsp;

From my point of view, this is unfortunately not happening with Ruby-Gtk.
```
42. `raise Foobar` method (top of stack)
41. signal handler
40. Gtk internals
...
24. method calling Gtk.main
23. `rescue Foobar` method
22. other methods
...
```
Yes, method 23 could rescue the SystemExit exception. But that's not what I need.
I need to rescue the original Foobar exception.

&nbsp;

So what I'm trying to do is to get as close as possible to the original behavior when using Ruby-Gtk.
And my currently best (but definitely far from perfect) idea for that is to somehow generically rescue all exceptions before the upper end of the Gtk internals part inside the stack. And then, below the Gtk internals part of the stack, reraise the exception.

**Comment by kou** [comment]
You can get the original exception from `SystemExit` exception by `Exception#cause`:

```ruby
begin
  Gtk.main
rescue SystemExit
  begin
    raise $!.cause
  rescue Foobar
    # ...
  end
end
```

But I think that reconsidering your program design is better.

**Comment by md-work** [comment]
@kou

> You can get the original exception from `SystemExit` exception by `Exception#cause`:
> 
> ```ruby
> begin
>   Gtk.main
> rescue SystemExit
>   begin
>     raise $!.cause
>   rescue Foobar
>     # ...
>   end
> end
> ```

Interestingly `$!.cause` seems to be `nil` sometimes when doing `begin; Gtk.main; rescue ...`.
I'm still currently trying to figure out the exact circumstances.

&nbsp;

> But I think that reconsidering your program design is better.

For where control flow is being done via exceptions: Definitely!

But I also like to catch all exceptions raised by real programming errors and display them in the main view of my application instead of crashing.

**Comment by kou** [comment]
An application can't recover from `GLib.exit_application` safely. Because exception from signal may break something implemented in C.
