### ISSUE TITLE
"draw" signal when resizing and/or hiding 

### ISSUE THREAD

**Issue by JC-LL** [ruby-gnome/ruby-gnome#1405]
Hi,

I have some troubles about the signal "draw", that I am using (maybe it is not the right signal to be used in my case ?)

Here is the context :
- I have a DrawingArea (here named View), packed in a Window.
- when resizing the window, I want my drawing model to be resized accordingly (@model.zoom_fit). That works as expected.

```
class View < Gtk::DrawingArea
     # skipped
    def create_callbacks 
      # skipped
      signal_connect("draw") do |_,cr|
        @model.zoom_fit self
        redraw
      end 
  end
```

- The problem is when I **hide** the window for some reason, **I DON'T WANT** to zoom fit (resize) my model. However "draw" signal seems to be always called and hence my model is also resized again.

Is there a better signaling to separate these two cases (resizing and hiding) ?

Thx

**Comment by pterjan** [comment]
The [size-allocate](https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget-size-allocate) signal seems more appropriate, it is called when the size of your widget changes

**Comment by JC-LL** [comment]
@pterjan  Thanks ! That works like a charm. The issue can be closed.
