### ISSUE TITLE
VTE support on rubygems.org: we currently have two gem versions, vte and vte3. I assume that vte3 is more recent, but could a bit more information be added to the vte gem?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1407]
Hello ruby-gtk developers, maintainers and ruby folks in general.

We currently have two variants of vte hosted on rubygems. These
are the following two:

    https://rubygems.org/gems/vte
    https://rubygems.org/gems/vte3

I understand that possibly these two gems exist in order to support
different version of (upstream) vte, in particular older versions. I
noticed this with other gems too, in particular gtksourceview. :)

On my home setup I keep different versions of (upstream) vte
available here locally in a src/vte/ subdirectory, via tarballs.

Examples:

    vte-0.38.4.tar.xz
    vte-0.52.4.tar.xz
    vte-0.56.4.tar.xz
    vte-0.58.3.tar.xz
    vte-0.59.92.tar.xz
    vte-0.60.3.tar.xz
    vte-0.61.90.tar.xz

I have not yet tried both vte-gems, but I assume that the 0.60* series
of vte is probably needing the vte3 gem, and the other, older tarballs
require the vte gem?

At any rate, my suggestion here is the following:

- Would it be possible to add **which version** is supported by
the two vte gems, in the .gemspec file, on the **description**
displayed by https://rubygems.org/gems/vte ?

For example, for the vte gem:

    "Ruby/VTE is a Ruby binding of VTE."

To something a bit longer, such as:

    "Ruby/VTE is a Ruby binding of VTE. Supported vte 
    versions range up to vte-0.52.4. For more recent
    versions of vte releases, consider using the vte3
    gem."

Or a description similar to the above. In other words, to
show somewhere briefly the version differences between
the vte and the vte3 gem, upon a first page visit.

That way we users and developers instantly know up to which
versions the vte gem supports. (For the vte3 gem this may be 
also helpful, but I think for the vte gem it is more important
because we can assume that vte3 is more for gtk3, which is
newer than gtk2, so people can infer that the vte gem is for
older vte-releases. For these it would be most helpful to
instantly see up to which versions they are supported.)

I hope I could explain the use case. vte is really nice to
quickly get an "embedded shell" available in a ruby-gtk
widget; I use it in connection with Gtk::Notebook and
several tabs, which is really great.

Thank you for reading this issue request; please feel free
to close this issue at any moment in time, for any reason.

**Comment by kojix2** [comment]
I think the difference between VTE and VTE3 is not due to the difference in VTE versions, but to the difference between GTK+ 2 and GTK+ 3

Thus, there are 2 different problems here.
1. It may be difficult for new-comers to understand the difference between VTE and VTE3.
2. Which version of libvte-3 is supported?

**Comment by kou** [comment]
The vte gem is for VTE for GTK+ 2.
The vte3 gem is for VTE for GTK+ 3.

I've updated description of them.
