### ISSUE TITLE
Access to memory pointer of GLib object

### ISSUE THREAD

**Issue by BobdeKlotz** [ruby-gnome/ruby-gnome#1409]
Hello,

I am trying to achieve something similar to #1308.
Because the insertion of lots of elements to my list store is really slow I was wondering if I could implement the slow part in C.
I found out that the GLib objects contain the C pointer:

```ruby
list_store = Gtk::ListStore.new(String)
=> #<Gtk::ListStore:0x555eb483b720 ptr=0x555eb44664e0>
```

I already tried to obtain the raw pointer via Ruby C extensions, but was not able to get it to work.
Is there a way to get that pointer without having to parse it out of this string?

I plan to use the FFI gem for the binding, so a method to obtain the raw pointer would be highly appreciated.
Something like this would be of great help:

```ruby
list_store = Gtk::ListStore.new(String)
list_store.raw_pointer
=> 93865239799008
```

**Comment by kou** [comment]
If you use the ffi gem, you can use `rbgobj_get_gobject()` C API https://github.com/ruby-gnome/ruby-gnome/blob/master/glib2/ext/glib2/rbgobj_object.c#L240 for it.

**Comment by BobdeKlotz** [comment]
Thanks for your extremely fast response, I will try this out.
