### ISSUE TITLE
Would it be worthwhile to make the initializers a bit more flexible, for ruby-gtk2 (backwards-compatible change), in order to aid in the transition phase towards gtk3?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1410]
Hello it's me again. :)

I am slowly porting my ancient code into more "modern" ruby-gtk2 code; and I am also looking at ruby-gtk3.

One change that appears to have happened is to transition into enabling Hashes.

For example:

    exit = Gtk::MenuItem.new(label: 'Exit')

This works on ruby-gtk3, but for ruby-gtk2 we have to use this style:

    exit = Gtk::MenuItem.new('Exit')

Would it be possible to add Hash-style to such gtk-widgets, so that the syntax:

    exit = Gtk::MenuItem.new(label: 'Exit')

Could also work on ruby-gtk2? I am not sure how much work that is; right now I only suggest it on MenuItem, and who knows what the future holds.

The main point why I actually suggest it is because it may help transition more easily into ruby-gtk3 or vice versa towards gtk2 for whatever reason. I am not sure if duck-patching ("monkey-patching") the initializers in ruby-gtk is trivial, so I rather avoid doing this. I had segfauls when I tried to modify "def initialize", which seems a bit difficult to do, but otherwise I modify all the gtk-core classes a LOT.

I suppose the check would go like this, in pseudo-code:

    if it is a String
      everything is fine
    else if it is a hash
      try to find at the least a key called :label and use that
        if no such key has been found, notify the user that this is mandatory, if that style is used

(I mean this only for ruby-gtk2. For ruby-gtk3, we can use the newer style as-is. But I am also not sure if it is worth to make the change, since I assume ruby-gtk2 will eventually be deprecated in the future. I just have not yet transitioned completely, and the transition phase is a bit difficult; some things are trivial to port, others not so much. At any rate, thank you for reading - I believe that at the least the above can give one use case of many other potential use cases.)

PS: The gnome folks already talk about gtk4. I am a bit worried about it, since if we look at ruby-qt for example, it never even managed to go to ruby-qt5. This is also why ruby-gtk is useful - we have a set of bindings that work quite ok-ish.

**Comment by kojix2** [comment]
What kind of application are you making with ruby-gtk2?
I think this is important.

**Comment by kou** [comment]
You can use `Gtk::MenuItem.new('Exit')` with the gtk3 gem.
It works with both the gtk2 gem and the gtk3 gem.

**Comment by kojix2** [comment]
I'm still interested in what applications you're making...

**Comment by kou** [comment]
No response.
