### ISSUE TITLE
gem install gtk2 on Mac OS (ruby 2.6.6) missing gtk/gtkfilesystem.h

### ISSUE THREAD

**Issue by OSXLich-Doug** [ruby-gnome/ruby-gnome#1412]
Trying a simple install of gtk2 version 3.4.3 on mac OS Catalina.  pkg-config 1.4.4 and native-package-installer 1.0.9 

If you were working on this, my apologies - this error seems to be a holdover.

it looks like my problem actually is the implicit declaration of a function and the recent Mac OS CLTools converting the warning to a hard error aborting the compile.

I'll look into it from that angle, but if interested, here's the error:

rbgdkdisplay.c:450:22: error: implicit declaration of function 'gdk_x11_display_get_startup_notification_id' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return CSTR2RVAL(gdk_x11_display_get_startup_notification_id(_SELF(self)));

**Comment by OSXLich-Doug** [comment]
I have now confirmed this.  Apple's Command Line Tools version 11.5 will build GTK2 gem with warnings on macOS up to Catalina.  

Apple's Command Line Tools version 12.0 GM release will fail to build GTK2 gem with error as shown above.  There may be other instances of implicit function declaration that will also need to be addressed - if this code gets refactored at any time.

GTK3 gem does not exhibit the error.  When I have time, I'll do a run against GTK3 and GTK4 at full logging to see if there are any other warnings turned errors in the new tool states.  Thanks for your attention - closing this as  an issue since it is resolved by back-revving.

**Comment by NilSet** [comment]
as a workaround, it can be installed with `CFLAGS="-Wno-implicit-function-declaration" gem install gtk2`
