### ISSUE TITLE
Custom modifications ("monkey patching") in ruby-gtk3 seem to be not working?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1413]
Hello ruby-gtk / ruby-gnome devs,

I have a strange situation that I do not fully understand here.

First, I will show the code, for ruby-gtk2 - this code works fine:

-------------------------------------------------------------------------------

    #!/usr/bin/ruby -w
    # Encoding: UTF-8
    # frozen_string_literal: true
    # =========================================================================== #
    require 'gtk2'

    module Gtk

    class Button

      # ========================================================================= #
      # === toggle_grey
      # ========================================================================= #
      def toggle_grey
        if sensitive?
          set_sensitive(false)
        else
          set_sensitive(true)
        end
      end

    end

    class HelloWorld < ::Gtk::Window

      alias e puts

      # ========================================================================= #
      # === initialize
      # ========================================================================= #
      def initialize(
          run_already = true
        )
        super('First example')
        set_size_request(400, 400)
        set_border_width(10)
        run if run_already
      end

      # ========================================================================= #
      # === run
      # ========================================================================= #
      def run
        button = ::Gtk::Button.new('Say hello')
        button.signal_connect(:clicked) { |_widget|
          e 'Hello World!! \\o/'
        }
        # button.override_font(Pango::FontDescription.new('bold'))
        button.toggle_grey
        add(button)
        signal_connect(:delete_event) { |_widget| ::Gtk.main_quit }
        show_all
        ::Gtk.main
      end
    
    end; end
    
    if __FILE__ == $PROGRAM_NAME
      Gtk::HelloWorld.new
    end

-------------------------------------------------------------------------------

Put this into some .rb file, run it, it should work fine for ruby gtk2
when the gtk2 gem is installed.

Now ... before I show the gtk3 variant, I'd like to say that this was
just a test, to try to modify "module Gtk; class Button". I have lots
of custom modifications like that in another project, where I add 
custom stuff to the whole Gtk module, to enable me write less code
in the long run. :)

Anyway - here comes the ruby-gtk3 code:

    #!/usr/bin/ruby -w
    # Encoding: UTF-8
    # frozen_string_literal: true
    # =========================================================================== #
    require 'gtk3'

    module Gtk

    class Button

      # ========================================================================= #
      # === toggle_grey
      # ========================================================================= #
      def toggle_grey
        if sensitive?
          set_sensitive(false)
        else
          set_sensitive(true)
        end
      end

    end

    class HelloWorld < ::Gtk::Window

      alias e puts

      # ========================================================================= #
      # === initialize
      # ========================================================================= #
      def initialize(
          run_already = true
        )
        super('First example')
        set_size_request(400, 400)
        set_border_width(10)
        run if run_already
      end

      # ========================================================================= #
      # === run
      # ========================================================================= #
      def run
        button = ::Gtk::Button.new(label: 'Say hello')
        button.signal_connect(:clicked) { |_widget|
          e 'Hello World!! \\o/'
        }
        # button.override_font(Pango::FontDescription.new('bold'))
        button.toggle_grey
        add(button)
        signal_connect(:delete_event) { |_widget| ::Gtk.main_quit }
        show_all
        ::Gtk.main
      end

    end; end

    if __FILE__ == $PROGRAM_NAME
      Gtk::HelloWorld.new
    end

When you run this example for ruby gtk3, you get this error:

    /root/.gem/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:216: warning: already initialized constant Gtk::Button
    example.rb:9: warning: previous definition of Button was here
    Traceback (most recent call last):
            3: from example.rb:59:in `<main>'
            2: from example.rb:59:in `new'
            1: from example.rb:37:in `initialize'
    example.rb:49:in `run': undefined method `toggle_grey' for #<Gtk::Button:0x558f5e4c2410 ptr=0x558f5e8c9180> (NoMethodError)

I am not sure if you understand this, but the way I see it, and
understand it, is that the modifications to "module Gtk; class Button"
do not seem to be honoured by ruby-gtk3. Remember that this is almost
identical code to ruby-gtk2.

I do not know C (sorry; should really learn it seriously), but I believe
that something is done when I do "gtk3" that pulls in some code. And
perhaps that code somehow makes the "module Gtk; class Button" code
not work - or, worse, ignore it. And this latter situation is totally
confusing to me.

I am quite used that, in ruby, we can "monkey patch" everything at any
moment in time. In fact, this is what I am currently doing in ruby-gtk2,
too. And there it works just fine.

But in ruby-gtk3, something seems to have changed. Perhaps it has
to do with the gobject-introspection situation, to make it easier
to generate bindings automatically, or something like this? But either
way, for a strange reason, the code that I used above, aka the
part specifically at "module Gtk; class Button" seems to be ignored
in gtk3, whereas almost the same code works fine in gtk2. To me this
is super-confusing. Did I do a mistake or is it really the way that
ruby-gtk3 changed here?

I do not know if this can be changed or has to stay how it currently
is; perhaps I am doing something wrong with gtk3 too, that may true.
Or perhaps there is some bug - I have no idea right now. Either way
it is very surprising to me, and I think if I can not use my 
custom modifications from ruby-gtk3 then I am not sure I can port
my code to ruby-gtk3, since I could not use my custom modifications.

At any rate, I just report this to make sure I did not make a mistake;
I think I will experiment with python a bit (no worries, I am still
using ruby primarily), just to find out how python does things in
python gtk3. I am sure there is some logical explanation out there,
but I am actually not just that experienced with gtk + gnome; I just
experiment more than I read. :)

Thank you for reading; please feel free to close this issue at any
moment in time.

**Comment by kojix2** [comment]
Hi. I don't know how gtk3 works in detail either. 
But it's easy to get the above code working. Just call init first.

```ruby
require 'gtk3'

module Gtk
  init() # here!
  class Button
    def meow
      puts "meow"
    end
  end
end

Gtk::Button.new.meow
```

**Comment by kojix2** [comment]
Gtk modules use `const_missing`, so the first time a constant is called, many gtk3 files and classes are loaded.
See the following files.

See
https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk3/lib/gtk3.rb

```
require 'gtk3'

module Gtk
  Button
  class Button
    def meow
      puts "meow"
    end
  end
end

Gtk::Button.new.meow
```

works fine.

**Comment by kojix2** [comment]
But why does gtk3 load all the files when the first constant is called, rather than when gtk3.rb is loaded?
I do not know why.

**Comment by kou** [comment]
You need to call `Gtk.init` in this case.
We don't always call it in `require "gtk3"` to support customizing program argument with `Gtk.init(custom_argv)`.
