### ISSUE TITLE
Slightly confusing warning in ruby-gtk3, for the method set_default_response() and Gtk::Dialog options

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1418]
Hello there.

A (to me slightly) confusing example follows next; this can be copy/pasted if someone wants to
have a look:

    require 'gtk3'

    class GtkDialogSample < Gtk::Dialog

      def initialize
        super()
        set_title 'Gtk::Dialog Sample'
        set_default_size(600, 250)
        move(0, 0)
        child.add(Gtk::Label.new('Gtk::Dialog Sample'))
        add_button('OK', :ok)
        add_button(Gtk::Stock::CANCEL, :cancel)
        add_button(Gtk::Stock::CLOSE, :close)
        set_default_response(Gtk::Dialog::RESPONSE_CANCEL)
        signal_connect(:response) { |widget, response|
          case response
          when :ok
            p 'OK'
          when :cancel
            p 'Cancel'
          when :close
            p 'Close'
            destroy #dialog.destroy
          end
        }
        show_all
      end

    end

    if __FILE__ == $PROGRAM_NAME
      GtkDialogSample.new
      Gtk.main  
    end

Please feel free to put this into a standalone .rb file and execute/run it.

If this is run, then the following warning appears:

    gtk_dialog_sample.rb:25:in `initialize': 'Gtk::Dialog::RESPONSE_CANCEL' has been deprecated. Use 'Gtk::ResponseType::CANCEL' or ':cancel'.

Ok - this is quite clear.

HOWEVER had, when I replace this, and use :cancel instead,
as indicated by the warning, aka a short symbol, I get this error:

    /root/.gem/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:600:in `invoke': no implicit conversion of Symbol into Integer (TypeError)

And it won't run at all.

Using Gtk::ResponseType::CANCEL instead of Gtk::Dialog::RESPONSE_CANCEL
works fine, by the way, so the only problematic variant is the
most convenient one for the user: the short one. The :cancel symbol. :)

I can think of two ways to fix or resolve this, aside from just using 
Gtk::ResponseType::CANCEL, which I currently do; the most logical
one would be to also allow :cancel. I think this is the one that is meant, and the
most logical, from the warning message. Using a symbol works in many
other places, so I am not sure why set_default_response() is different.

IF, however had, this can not be changed for whatever the reason,
then I think the warning should be different. In case a Symbol 
may not be used there, for this method/function call, then I
believe the warning should not recommend to the user to use a
Symbol, as in that case it would lead to the .rb file at hand 
not being executed at all whatsoever.

So, to give an example for the second option, even though the
first option would be the better, the warning message could
then be:

   gtk_dialog_sample.rb:25:in `initialize': 'Gtk::Dialog::RESPONSE_CANCEL' has been deprecated. Use 'Gtk::ResponseType::CANCEL'.

(gobject-bindings are still a bit confusing to me; the warnings and
error notifications they provide seem to be a bit less compared to
the older ruby-gtk2 variants. Not sure if my impression is correct
or incorrect, but it is not always easy to see what is going wrong.
I am slowly getting more experience with ruby-gtk3 now, though.)

PS: I understand that ruby-gtk2 is only in slight maintenance mode,
but it would be pretty cool if we could use Symbols for all ruby-gtk
versions. These seem very convenient and that was a good change
IMO; I like the idea of using just :cancel rather than having to specify
the exact constant as-is.

**Comment by kou** [comment]
Thanks for your report.
I've fixed.

ruby-gtk2 reaches EOL because GTK+ 2 reaches EOL: https://blog.gtk.org/2020/12/16/gtk-4-0/
