### ISSUE TITLE
Do ruby-gtk2 and ruby-gtk3 work on ruby 3?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1422]
I seem to be having problems installing ruby-gtk2 and ruby-gtk3
with ruby 3.x these days.

Example for "gem install gtk2:

compiling rbglib_spawnerror.c
compiling rbglib_threads.c
compiling rbglib_timer.c
compiling rbglib_timezone.c
compiling rbglib_ucs4.c
compiling rbglib_unichar.c
compiling rbglib_unicode.c
compiling rbglib_utf16.c
compiling rbglib_utf8.c
compiling rbglib_utils.c
compiling rbglib_win32.c
compiling rbglibdeprecated.c
compiling rbgobj_binding.c
compiling rbgobj_boxed.c
rbgobj_boxed.c:60:5: warning: missing initializer for field ‘dsize’ of ‘struct <anonymous>’ [-Wmissing-field-initializers]
   60 |     },
      |     ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:34,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_boxed.c:22:
/usr/include/ruby-3.0.0/ruby/internal/core/rtypeddata.h:75:18: note: ‘dsize’ declared here
   75 |         size_t (*dsize)(const void *);
      |                  ^~~~~
compiling rbgobj_closure.c
rbgobj_closure.c: In function ‘g_rclosure_new_raw’:
rbgobj_closure.c:244:5: warning: ‘rb_cData’ is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
  244 |     closure->rb_holder  = Data_Wrap_Struct(rb_cData,
      |     ^~~~~~~
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:27,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_closure.c:23:
/usr/include/ruby-3.0.0/ruby/internal/core/rdata.h:169:1: note: declared here
  169 | rb_cData(void)
      | ^~~~~~~~
compiling rbgobj_convert.c
compiling rbgobj_enumflags.c
compiling rbgobj_enums.c
rbgobj_enums.c:114:5: warning: missing initializer for field ‘dsize’ of ‘struct <anonymous>’ [-Wmissing-field-initializers]
  114 |     },
      |     ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:34,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_enums.c:23:
/usr/include/ruby-3.0.0/ruby/internal/core/rtypeddata.h:75:18: note: ‘dsize’ declared here
   75 |         size_t (*dsize)(const void *);
      |                  ^~~~~
compiling rbgobj_flags.c
rbgobj_flags.c:83:5: warning: missing initializer for field ‘dsize’ of ‘struct <anonymous>’ [-Wmissing-field-initializers]
   83 |     },
      |     ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:34,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_flags.c:22:
/usr/include/ruby-3.0.0/ruby/internal/core/rtypeddata.h:75:18: note: ‘dsize’ declared here
   75 |         size_t (*dsize)(const void *);
      |                  ^~~~~
compiling rbgobj_object.c
rbgobj_object.c:109:5: warning: missing initializer for field ‘dsize’ of ‘struct <anonymous>’ [-Wmissing-field-initializers]
  109 |     },
      |     ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:34,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_object.c:26:
/usr/include/ruby-3.0.0/ruby/internal/core/rtypeddata.h:75:18: note: ‘dsize’ declared here
   75 |         size_t (*dsize)(const void *);
      |                  ^~~~~
rbgobj_object.c: In function ‘rbgobj_register_property_setter’:
rbgobj_object.c:518:18: warning: ‘rb_cData’ is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
  518 |                  Data_Wrap_Struct(rb_cData, NULL, NULL, func));
      |                  ^~~~~~~~~~~~~~~~
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:27,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_object.c:26:
/usr/include/ruby-3.0.0/ruby/internal/core/rdata.h:169:1: note: declared here
  169 | rb_cData(void)
      | ^~~~~~~~
rbgobj_object.c: In function ‘rbgobj_register_property_getter’:
rbgobj_object.c:539:18: warning: ‘rb_cData’ is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
  539 |                  Data_Wrap_Struct(rb_cData, NULL, NULL, func));
      |                  ^~~~~~~~~~~~~~~~
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:27,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_object.c:26:
/usr/include/ruby-3.0.0/ruby/internal/core/rdata.h:169:1: note: declared here
  169 | rb_cData(void)
      | ^~~~~~~~
compiling rbgobj_param.c
rbgobj_param.c:61:5: warning: missing initializer for field ‘dsize’ of ‘struct <anonymous>’ [-Wmissing-field-initializers]
   61 |     },
      |     ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:34,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_param.c:22:
/usr/include/ruby-3.0.0/ruby/internal/core/rtypeddata.h:75:18: note: ‘dsize’ declared here
   75 |         size_t (*dsize)(const void *);
      |                  ^~~~~
compiling rbgobj_paramspecs.c
compiling rbgobj_signal.c
rbgobj_signal.c:39:5: warning: missing initializer for field ‘dsize’ of ‘struct <anonymous>’ [-Wmissing-field-initializers]
   39 |     },
      |     ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:34,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_signal.c:23:
/usr/include/ruby-3.0.0/ruby/internal/core/rtypeddata.h:75:18: note: ‘dsize’ declared here
   75 |         size_t (*dsize)(const void *);
      |                  ^~~~~
rbgobj_signal.c: In function ‘rbgobj_set_signal_func’:
rbgobj_signal.c:72:5: warning: ‘rb_cData’ is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
   72 |     VALUE obj = Data_Wrap_Struct(rb_cData, NULL, NULL, func);
      |     ^~~~~
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:27,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_signal.c:23:
/usr/include/ruby-3.0.0/ruby/internal/core/rdata.h:169:1: note: declared here
  169 | rb_cData(void)
      | ^~~~~~~~
rbgobj_signal.c: In function ‘rbgobj_set_signal_call_func’:
rbgobj_signal.c:94:5: warning: ‘rb_cData’ is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
   94 |     VALUE obj = Data_Wrap_Struct(rb_cData, NULL, NULL, func);
      |     ^~~~~
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:27,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_signal.c:23:
/usr/include/ruby-3.0.0/ruby/internal/core/rdata.h:169:1: note: declared here
  169 | rb_cData(void)
      | ^~~~~~~~
rbgobj_signal.c: In function ‘Init_gobject_gsignal’:
rbgobj_signal.c:950:5: warning: ‘rb_cData’ is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
  950 |     RG_TARGET_NAMESPACE = rb_define_class_under(mGLib, "Signal", rb_cData);
      |     ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:27,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_signal.c:23:
/usr/include/ruby-3.0.0/ruby/internal/core/rdata.h:169:1: note: declared here
  169 | rb_cData(void)
      | ^~~~~~~~
compiling rbgobj_strv.c
In file included from rbgobject.h:27,
                 from rbgprivate.h:31,
                 from rbgobj_strv.c:22:
rbgobj_strv.c: In function ‘strv_from_ruby’:
rbglib.h:124:24: warning: initialization of ‘const gchar **’ {aka ‘const char **’} from incompatible pointer type ‘gchar **’ {aka ‘char **’} [-Wincompatible-pointer-types]
  124 | #define RVAL2STRV(ary) rbg_rval2strv(&(ary), NULL)
      |                        ^~~~~~~~~~~~~
rbgobj_strv.c:33:29: note: in expansion of macro ‘RVAL2STRV’
   33 |     const gchar **strings = RVAL2STRV(from);
      |                             ^~~~~~~~~
compiling rbgobj_type.c
rbgobj_type.c: In function ‘rbgobj_class_info_register_without_lock’:
rbgobj_type.c:136:5: warning: ‘rb_cData’ is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
  136 |     c = TypedData_Make_Struct(rb_cData, RGObjClassInfo, data_type, cinfo);
      |     ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:27,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_type.c:22:
/usr/include/ruby-3.0.0/ruby/internal/core/rdata.h:169:1: note: declared here
  169 | rb_cData(void)
      | ^~~~~~~~
rbgobj_type.c: In function ‘get_superclass’:
rbgobj_type.c:243:9: warning: ‘rb_cData’ is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
  243 |         return rb_cData;
      |         ^~~~~~
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:27,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_type.c:22:
/usr/include/ruby-3.0.0/ruby/internal/core/rdata.h:169:1: note: declared here
  169 | rb_cData(void)
      | ^~~~~~~~
rbgobj_type.c: In function ‘rbgobj_register_class’:
rbgobj_type.c:535:9: warning: ‘rb_cData’ is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
  535 |         c = TypedData_Make_Struct(rb_cData, RGObjClassInfo, data_type, cinfo);
      |         ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:27,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_type.c:22:
/usr/include/ruby-3.0.0/ruby/internal/core/rdata.h:169:1: note: declared here
  169 | rb_cData(void)
      | ^~~~~~~~
compiling rbgobj_typeinstance.c
compiling rbgobj_typeinterface.c
compiling rbgobj_typemodule.c
compiling rbgobj_typeplugin.c
compiling rbgobj_value.c
rbgobj_value.c: In function ‘rbgobj_gvalue_to_rvalue’:
rbgobj_value.c:120:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
  120 |         {
      |         ^
rbgobj_value.c:134:7: note: here
  134 |       case G_TYPE_VARIANT:
      |       ^~~~
rbgobj_value.c: In function ‘rbgobj_rvalue_to_gvalue’:
rbgobj_value.c:307:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
  307 |         {
      |         ^
rbgobj_value.c:322:7: note: here
  322 |       case G_TYPE_VARIANT:
      |       ^~~~
compiling rbgobj_valuearray.c
compiling rbgobj_valuetypes.c
rbgobj_valuetypes.c: In function ‘rbgobj_ruby_value_get_type’:
rbgobj_valuetypes.c:189:11: warning: cast between incompatible function types from ‘VALUE (*)(VALUE)’ {aka ‘long unsigned int (*)(long unsigned int)’} to ‘void * (*)(void *)’ [-Wcast-function-type]
  189 |           (GBoxedCopyFunc)boxed_ruby_value_ref,
      |           ^
rbgobj_valuetypes.c:190:11: warning: cast between incompatible function types from ‘void (*)(VALUE)’ {aka ‘void (*)(long unsigned int)’} to ‘void (*)(void *)’ [-Wcast-function-type]
  190 |           (GBoxedFreeFunc)boxed_ruby_value_unref);
      |           ^
rbgobj_valuetypes.c: In function ‘Init_boxed_ruby_value’:
rbgobj_valuetypes.c:227:7: warning: ‘rb_cData’ is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
  227 |       Data_Wrap_Struct(rb_cData,
      |       ^~~~~~~~~~~~~~~~
In file included from /usr/include/ruby-3.0.0/ruby/internal/core.h:27,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:26,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from rbgobject.h:26,
                 from rbgprivate.h:31,
                 from rbgobj_valuetypes.c:22:
/usr/include/ruby-3.0.0/ruby/internal/core/rdata.h:169:1: note: declared here
  169 | rb_cData(void)
      | ^~~~~~~~
compiling rbgobject.c
compiling rbgutil.c
compiling rbgutil_callback.c
compiling rbgutil_list.c
compiling rbgutildeprecated.c
linking shared-object glib2.so

----------------

Unfortunately my knowledge of C is too limited to help solve
this. I currently work around it by using ruby 2.7.2 where 
the gtk-bindings work fine, but I wanted to report this just
in case it has not been reported yet. Thanks!

**Comment by rubyFeedback** [comment]
Sorry - ruby-gtk3 works. I just tested it.

I am not sure why I can't get ruby-gtk2 to work but I mostly use ruby-gtk3 these days, so this can be considered closed more or less.

**Comment by kou** [comment]
We dropped support for gtk2 gem because GTK+ 2 reached EOL.

We'll maintain gtk3 gem. We have CI with Ruby 3.0: https://github.com/ruby-gnome/ruby-gnome/blob/master/.github/workflows/linux.yml#L20
