### ISSUE TITLE
window.set_icon() correctly works with unity, but not wayland

### ISSUE THREAD

**Issue by Guarmanda** [ruby-gnome/ruby-gnome#1423]
System info:
ubuntu 20.04 
gdk&gtk 3.4.3, 
ruby 2.7.0
gnome-desktop with basic dock options
lightdm instead of gdm3

How to reproduce:
On ubuntu login screen, chose wayland instead of unity

Gtk.init
window = Gtk::Window.new()
window.set_icon(any_icon_from_any_format)
window.show_all

The icon won't display in the dock: the setings icon will apear instead. If you close your session and go back to unity, it works.

**Comment by kou** [comment]
You need to use `.desktop` instead of `Gtk::Window#set_icon` for GNOME Shell: https://gitlab.gnome.org/GNOME/gtk/-/issues/1602
Wayland isn't related. It's a difference between Unity and GNOME Shell.

**Comment by Guarmanda** [comment]
Just to clarify, you say me to create a .desktop file to launch my app rather than launching it with the terminal ? (ruby app.rb)
(and you say wayland isn't related to this but wayland is the really unique parameter that changes between the two executions of the program^^)

**Comment by kou** [comment]
Yes.
You use GNOME Shell not Unity with Wayland, right?

**Comment by Guarmanda** [comment]
Mmmmh, I'll clarify a little. I said shit with unity: I should have said xorg, unity is a desktop environ ment, not a display server. I use default Ubuntu desktop environment. 
Ubuntu uses xorg as a display server by default, but you can switch to wayland (wayland will be used by default in next Ubuntu version) 
When I switch to wayland, the icon doesn't display in the dock, and I don't thing it comes from gnome shell and unity, because I don't change them at all

**Comment by Guarmanda** [comment]
I just noticed this bug also append with eclipse IDE: eclipse icon isn't shown with wayland. So it's not related to ruby or Gtk at all.
