### ISSUE TITLE
require 'gtk3' throws error. Possibly from pango?

### ISSUE THREAD

**Issue by ChickenBeard** [ruby-gnome/ruby-gnome#1424]
Not sure if this is a gtk3 issue so apologies if not...

MacOS Big Sur 11.2.3
ruby 2.6.6p146 (2020-03-31 revision 67876) [-darwin20]

When I go into `irb` I can `require 'sqlite3'` successfully.
But `require 'gtk3'` fails with the following: https://gist.github.com/ChickenBeard/306eb9b53344bdbd176f45a87c0f408c

**Comment by kou** [comment]
Could you show the output of `ruby -e 'require "pango"; p Pango::AttrType.ancestors'`?

**Comment by ChickenBeard** [comment]
(NULL)-WARNING **: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:179:in `load_enum_info'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:66:in `load_info'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:43:in `block in load'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/repository.rb:34:in `block (2 levels) in each'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/repository.rb:33:in `times'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/repository.rb:33:in `block in each'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/repository.rb:32:in `each'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/repository.rb:32:in `each'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:42:in `load'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango.rb:29:in `<module:Pango>'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango.rb:24:in `<top (required)>'
	from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from -e:1:in `<main>'
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pango (LoadError)
	12: from -e:1:in `<main>'
	11: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	10: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	 9: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	 8: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango.rb:24:in `<top (required)>'
	 7: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango.rb:29:in `<module:Pango>'
	 6: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:45:in `load'
	 5: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango/loader.rb:32:in `post_load'
	 4: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango/loader.rb:85:in `require_libraries'
	 3: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 1: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango/attr-type.rb:17:in `<top (required)>'
/opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango/attr-type.rb:18:in `<module:Pango>': AttrType is not a class (TypeError)

**Comment by kou** [comment]
Could you try `DYLD_LIBRARY_PATH=$(brew --prefix)/lib ruby -e 'require "pango"; p Pango::AttrType.ancestors'`?

**Comment by ChickenBeard** [comment]
`[Pango::AttrType, GLib::Enum, Object, Kernel, BasicObject]`

After which `ruby -e 'require "pango"; p Pango::AttrType.ancestors'` returned:
(NULL)-WARNING **: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:179:in `load_enum_info'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:66:in `load_info'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:43:in `block in load'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/repository.rb:34:in `block (2 levels) in each'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/repository.rb:33:in `times'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/repository.rb:33:in `block in each'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/repository.rb:32:in `each'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/repository.rb:32:in `each'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:42:in `load'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango.rb:29:in `<module:Pango>'
	from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango.rb:24:in `<top (required)>'
	from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from -e:1:in `<main>'
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pango (LoadError)
	12: from -e:1:in `<main>'
	11: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	10: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	 9: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	 8: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango.rb:24:in `<top (required)>'
	 7: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango.rb:29:in `<module:Pango>'
	 6: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:45:in `load'
	 5: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango/loader.rb:32:in `post_load'
	 4: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango/loader.rb:85:in `require_libraries'
	 3: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /opt/homebrew/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 1: from /opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango/attr-type.rb:17:in `<top (required)>'
/opt/homebrew/lib/ruby/gems/2.6.0/gems/pango-3.4.3/lib/pango/attr-type.rb:18:in `<module:Pango>': AttrType is not a class (TypeError)

**Comment by kou** [comment]
This is a Homebrew problem. Could you report this to https://github.com/Homebrew/homebrew-core/issues ?

`$(brew --prefix)/share/gir-1.0/GLib-2.0.gir` provided by the glib formula uses absolute path such as `/opt/homebrew/opt/glib/lib/libgobject-2.0.0.dylib` for `shared-library`. (You can confirm it by `grep shared-library $(brew --prefix)/share/gir-1.0/GLib-2.0.gir`.)

But `$(brew --prefix)/share/gir-1.0/Pango-1.0.gir` provided by the pango formula doesn't use absolute path such as `libpango-1.0.0.dylib` for `shared-library`.  (You can confirm it by `grep shared-library $(brew --prefix)/share/gir-1.0/Pango-1.0.gir`.)

`.gir` files provided by Homebrew should always use absolute path because Homebrew users can change Homebrew prefix from `/usr/local`. Not absolute path works with `/usr/local` because the default `DYLD_FALLBACK_LIBRARY_PATH` includes `/usr/local/lib`.  (See `dyld(1)`.) But not absolute path doesn't work with not `/usr/local` such as `/opt/homebrew`.

**Comment by kou** [comment]
https://github.com/Homebrew/homebrew-core/issues/75020 may be related.

**Comment by ChickenBeard** [comment]
Looks like it's already reported..? https://github.com/Homebrew/homebrew-core/issues/75020

**Comment by kou** [comment]
Could you comment additional information on the issue?

**Comment by kou** [comment]
I close this.

**Comment by carlocab** [comment]
> `.gir` files provided by Homebrew should always use absolute path because Homebrew users can change Homebrew prefix from `/usr/local`. Not absolute path works with `/usr/local` because the default `DYLD_FALLBACK_LIBRARY_PATH` includes `/usr/local/lib`. (See `dyld(1)`.) But not absolute path doesn't work with not `/usr/local` such as `/opt/homebrew`.

Thanks for the explanation, @kou. Would you know how to make sure that `Pango-1.0.gir` uses an absolute path?
