### ISSUE TITLE
Windows binaries and getting ruby-gtk3 to work on windows? Do we have some means for a simplified download or perhaps even binaries for ruby-gtk3 + windows?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1425]
Hey ruby folks,

Today I managed to get ruby-tk to work on windows.

Note: I already can use ruby-gtk and ruby-tk on windows via WSL1 (and
probably WSL2 but I did not try this yet). So here I refer to ruby-tk
on windows, via oldschool cmd.exe.

The .rb file for "hello world" in ruby-tk worked. \o/

I was following this guide:

  https://rubytalk.org/t/documentation-for-installing-ruby-tk-on-windows/75311

And indeed, it worked.

But I wrote a LOT of ruby-gtk code in general and I am still writing 
ruby-gtk code. In particular the CSS styline is really nifty, it all
looks nice - but for me only on linux, or windows+WSL1. :D

I remember many years ago we had downloadable binaries for ruby-gtk2
on windows. These worked too!

I don't know what happened, but I think there are no downloadable
binaries anymore.

If I understood it correctly what we have to do on windows then we
have to compile via e. g. MSYS2.

On linux I can just use:

  gem install gtk3

And that works. All nice.

On windows, I first need the gtk-specific parts, and that is quite
tedious. I'd wish there was a way like for tcl/tk!

It does not have to be a downloadable .exe file, mind you. I am
fine using ruby (from rubyinstaller2) and some scripts that would
get this all installed, compiled and ready. But doing so on my
own is a bit ... difficult. I don't fully understand windows nor
msys2. And I am not really using windows that much to begin
with, either. (My laptop runs win10, but my desktop system runs
linux, so most of my time I am on linux.)

I actually do not need a GUI for my own use case (I can use
the commandline stuff just fine anyway; or if really necessary
I can write a GUI either in ruby-gtk3 these days, or .cgi/sinatra,
it's all fine.) - but there are elderly relatives who are stuck
with windows. Since I have to help debug stuff, I'd love a simple
GUI where I can then tell them to just click some buttons to 
solve something. Like a control panel in a GUI and start this
by default; that would work. But I'd prefer to use ruby-gtk3
if possible.

Anyway. This here is mostly just a long term suggestion, please
feel free to disregard/close it. For the time being I think I
will use ruby-tk, even though it looks uglier than ruby-gtk,
but today I realized it works as-is on windows, whereas with
ruby-gtk3 I am not quite sure how to get it to work. I may
try at a later time, but for now I'll write some ruby-tk 
specific code for windows. Thanks for reading this.

**Comment by kou** [comment]
You can install the gtk3 gem by `gem install gtk3` on Windows.
Dependencies including GTK+ 3 are automatically installed.
