### ISSUE TITLE
Password (gtk_entry) - invisible char

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1426]
This is a tiny issue, so not sure if worth reporting, but as always please feel free to disregard / close as appropriate.

In ruby gtk3 the following works just fine:

    require 'gtk3'

    vbox = Gtk::Box.new(:horizontal)
    vbox.set_border_width(20)
    password = Gtk::Entry.new
    password.set_visibility(false)
    password.invisible_char = 42 # This is '*' in Unicode.
    vbox.add(password)
    window = Gtk::Window.new
    window.add(vbox)
    window.show_all
    window.set_size_request(500, -1)
    window.move(0, 0)
    Gtk.main

As can be seen when you input something into the gtk-entry, the '*' token appears,
as is typical of a "password-entry" interface.

However had I looked at the python example too. I copy/paste it here:

    import sys
    import gi

    gi.require_version('Gtk', '3.0')
    from gi.repository import Gtk

    import os

    class AppWindow(Gtk.ApplicationWindow):
      def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_border_width(10)
        prompt_str = "What is the password for " + os.getlogin() + "?"
        question = Gtk.Label(label = prompt_str)
        label = Gtk.Label(label = "Password:")
        passwd = Gtk.Entry()
        passwd.set_visibility(False)
        passwd.set_invisible_char("*")
        hbox = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
        hbox.pack_start(label, False, False, 5)
        hbox.pack_start(passwd, False, False, 5)
        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        vbox.pack_start(question, False, False, 0)
        vbox.pack_start(hbox, False, False, 0)
        self.add(vbox)
        self.move(0, 0)

    class Application(Gtk.Application):
      def __init__(self, *args, **kwargs):
        super().__init__(*args, application_id="org.example.myapp",
                 **kwargs)
        self.window = None

      def do_activate(self):
        if not self.window:
          self.window = AppWindow(application=self, title="Password")
        self.window.show_all()
        self.window.present()

    if __name__ == "__main__":
      app = Application()
      app.run(sys.argv)

The interesting entry is this one:

    passwd.set_invisible_char("*")

It directly sets the invisible char as a String.

I tried this in ruby-gtk3 but I get an error:

gobject-introspection/loader.rb:600:in `invoke': no implicit conversion of String into Integer (TypeError)

It seems we can not use Strings here, but must use Integer. Is this a bug? It's not a big
deal because I can use 42, but I was wondering why we had to use a number whereas
in python we can use a String.

**Comment by kou** [comment]
It makes sense.
I've implemented.
