### ISSUE TITLE
Supported versions for webkit? Would it be possible to mention this in the gemspec and/or README?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1431]
Hey ruby folks,

I had a look at:

https://github.com/ruby-gnome/ruby-gnome/tree/master/webkit2-gtk

Now - I compile everything from source, so that includes webkitgtk.

I follow LFS/BLFS usually which works fine:

https://www.linuxfromscratch.org/blfs/view/svn/x/webkitgtk.html

Most recent "stable" release is:

https://webkitgtk.org/releases/webkitgtk-2.32.3.tar.xz

Now I am fine compiling that, but it takes about 1-2 hours or so
on my computer, give or take. Not a problem, but this leads me
to a question:

- Which versions are supported by the ruby bindings? For instance,
2.33.x is probably not supported but perhaps 2.32.x is neither?

If it would be possible, could the supported upstream version be
added? That way I can adjust, and, for instance, compile an older
webkit version if need be.

For ruby-vte kojix2 added that information so thanks about that by
the way. Would be great if this could also happen for webkit - 
I saw kou's old(er) presentation where he did fun stuff with webkit
from ruby, which was kind of cool. (I don't remember when
that presentation happened ... probably some years ago
already; also I am trying to install yardview_gtk3 but first I
have to solve my local webkit problem, which is why I ask :) ).

**Comment by kou** [comment]
I've added minimum supported version. It's the version that Ubuntu 18.04 ships. (We have CI on Ubuntu 18.04.)

> I saw kou's old(er) presentation where he did fun stuff with webkit from ruby, which was kind of cool. (I don't remember when that presentation happened ...

https://youtu.be/Iw0ha41Ty6I?t=357 ?

**Comment by kojix2** [comment]
I think I have only tried WebKit2GTK on Ubuntu, 
I wanted to run ruby + webkit on macOS and Windows, but I didn't know how...

**Comment by kou** [comment]
WebKitGTK doesn't support macOS and Windows...
