### ISSUE TITLE
Segmentation Fault on finalizer

### ISSUE THREAD

**Issue by zhum** [ruby-gnome/ruby-gnome#1447]
Hello!

I try to implement my gtk3-based app to organize my books/music/etc.
After adding the autocompletion feature the app hits segmentation fault **occasionally**. I've described the way to reproduce it in the BUG-REPRODUCE.md file.

Because it is hard for me to extract minimal example and I do not understand the exact cause of segfault, I extracted all needed files (only one ruby file and some data files).

Here is the actual git branch with all needed files: https://github.com/zhum/keep-it-well/tree/bugreport

`log` - is the dump, the ruby interpreter generated on the last fault.

I've posted this bug to ruby-lang, but got the answer:

```
According to the log, it is very likely to be a problem with gtk3. Could you contact on the author of the gem?
I guess the gem wrongly assumes the order in which finalizers are called.
```

**Comment by kou** [comment]
Thanks for preparing the reproducible script but I couldn't do "select any empty cell in 'Genre' column". How to do it?

Screenshot: ![image](https://user-images.githubusercontent.com/27350/139743500-6f7888d4-1f12-4162-892c-9610ddd0d05e.png)

**Comment by zhum** [comment]
O! My fault! I forgot to add sample data. Please do `git pull`, then start the app as `ruby ./disks-gtk3.rb Abooks`.

**Comment by zhum** [comment]
Please, try to use new version?

**Comment by kou** [comment]
Confirmed.
You can't  share `Gtk::EntryCompletion` with multiple `Gtk::Entry`s. Could you create a `Gtk::EntryCompletion` for each `Gtk::Entry`? Or could you disconnect one shared `Gtk::EntryCompletion` before you connect it to another `Gtk::Entry`?
