### ISSUE TITLE
Consideration for a slight (possible) improvement: error was "Junk at end of value for padding (Gtk::CssProviderError::Syntax)"

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1448]
Hello kou and other ruby-gtk folks (also kou if you haven't yet checked out, make sure to have a look at Andy's glimmer-gtk here: https://github.com/AndyObtiva/glimmer-dsl-gtk - one DSL to rule them all! \o/ )

Right now I encountered a syntax error in the following CSS:

    tooltip {
      border: 3px solid darkblue;
      background-color: white;
      color: black;
      font-size: 30px;
      padding: 12px
    }

For those readers who may not know: this is a CSS rule to style all tooltips in an application.
Don't worry too much about the setting, I just like increasing font size and make things
more colourful when I debug stuff. ;)

There is one typo in the above; at padding: 12px I forgot to add the trailing ;

Simple fix.

But this is what I got from ruby-gtk:

I just copy/paste all warnings from the commandline, as superuser:

    /root/.gem/gems/red-colors-0.3.0/lib/colors/xterm256.rb:45: warning: assigned but unused variable - y
    /root/.gem/gems/red-colors-0.3.0/lib/colors/xterm256.rb:45: warning: assigned but unused variable - z
    /root/.gem/gems/red-colors-0.3.0/lib/colors/linear_segmented_colormap.rb:83: warning: assigned but unused variable - shape
    /root/.gem/gems/red-colors-0.3.0/lib/colors/colormap_registry.rb:33: warning: assigned but unused variable - existing
    /root/.gem/gems/red-colors-0.3.0/lib/colors/colormap_data/matplotlib_builtin.rb:957: warning: assigned but unused variable - b_data
    /root/.gem/gems/glib2-3.4.9/lib/glib2/deprecatable.rb:163: warning: method redefined; discarding old domain
    /root/.gem/gems/gobject-introspection-3.4.9/lib/gobject-introspection/loader.rb:261: warning: previous definition of domain was here
    /root/.gem/gems/glib2-3.4.9/lib/glib2/deprecatable.rb:163: warning: method redefined; discarding old signature
    /root/.gem/gems/gobject-introspection-3.4.9/lib/gobject-introspection/loader.rb:261: warning: previous definition of signature was here

    /root/.gem/gems/gobject-introspection-3.4.9/lib/gobject-introspection/loader.rb:616:in `invoke':     <data>:862:2Junk at end of value for padding (Gtk::CssProviderError::Syntax)
            from /root/.gem/gems/gobject-introspection-3.4.9/lib/gobject-introspection/loader.rb:616:in `invoke'
            from /root/.gem/gems/gobject-introspection-3.4.9/lib/gobject-introspection/loader.rb:529:in `block in define_method'
            from /root/.gem/gems/gtk3-3.4.9/lib/gtk3/css-provider.rb:43:in `load_from_data'
            from /root/.gem/gems/gtk3-3.4.9/lib/gtk3/css-provider.rb:25:in `load'
            from /home/Programs/Ruby/3.0.2/lib/ruby/site_ruby/3.0.0/gtk_paradise/base_module/css.rb:177:in `do_apply_the_CSS_rules'
            from /home/Programs/Ruby/3.0.2/lib/ruby/site_ruby/3.0.0/gtk_paradise/base_module/css.rb:25:in `more_css_then_apply_the_CSS_rules'
            from /home/x/programming/ruby/src/rpg_paradise/lib/rpg_paradise//gui/gtk3/magic_the_gathering/card_collection/card_collection.rb:304:in `handle_CSS_rules'

So the error message was: 

**<data>:862:2Junk at end of value for padding (Gtk::CssProviderError::Syntax)**

First, the 862:2 part is quite confusing. I assume it may come from gtk itself? But anyway this is a minor
issue; the bigger is that the message doesn't tell me much.

Now that I know this refers to a lack of trailing ";", so I won't get confused in the future (and by 
describing this here, perhaps other folks out there may find the issue here).

Evidently it was a syntax-error in CSS, so technically the message is correct. But it does not tell
me much, yet alone how to fix it. This was a fairly easy CSS; imagine a really long one ... I'd
have to manually scan each line.

My question or suggestion thus is: would it be possible to enhance the error message, at the
least that one?

I am now quite used to improvements such as the did-you-mean gem, so an additional 
suggestion may be helpful in this case, like "Did you ensure trailing ; were used in the
CSS rule?" or something like that. Could be shorter too, like "Check for missing ; in the CSS"
or anything that is more useful than the default message. I assume that many of these
things originate from upstream glib/gtk/gobject-introspection - in particular the leader
seems to be a bit cryptic in regards to how things are reported to the end user or developer
downstream.

Anyway, as usual please disregard if not applicable or not sufficiently important - this is
mostly to serve as information. :)

**Comment by kou** [comment]
Yes. This message is generated by upstream GTK: https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gtk/gtkcsskeyframes.c#L259

Could you report this to GTK?
