### ISSUE TITLE
minimal gtk + mruby ?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1450]
Hello kou and everyone else,

This is not an "issue request", per se, but more a discussion / ideas suggestion. Please do feel free
to ignore or disregard or auto-close as-is.

Background for the idea I have here:

I have been using ruby since a long time, and ruby-gtk as well.

Some time ago kojix2 wrote the wrapper code for libui; I think kou knows that since kojix2 also
commented on ruby fiddle. The code written by kojix2 allows other projects to be quite nifty in
this regard - see Andy's glimmer-dsl-libui here, in particular look at the screenshots. Quite
impressive what Andy (and kojix2, by logical extension) managed to do so far with ruby-libui:

https://github.com/AndyObtiva/glimmer-dsl-libui

I personally still use ruby-gtk a lot these days, in particular ruby-gtk3. The CSS support is really
nice. I can adjust things a LOT and they look somewhat ok-ish. (HTML pages + CSS may look
better, but I am fine to use the CSS support in gtk as-is.)

Recently I wanted to go into arduino and build custom stuff. arduino is quite interesting.

I also searched for mruby + arduino but not so much happens there. Some guides on the
www use PHP for connecting to these devices. I'd want to use ruby rather than PHP.

So I thought ... can we have a "minimal gtk" for arduino and/or mruby? The latter is not
as important to me personally, but having a minimal gtk would be great.

With minimal gtk I kind of mean to not really need everything. Just the very bare minimum,
button, perhaps gtk-entry for user input ... perhaps also being able to display simple
images (format is not so important, we can autoconvert via imagemagick so simplest
format is fine).... hmm. Mostly just to have a "minimal gtk" going, similar to what libui
is trying to do (but it's kind of cross-platform).

Would it be possible to have something like this supported on small, embeddable devices?

I don't know enough C to be able to judge whether that is possible. We can skip most
of the implementation, even CSS - while CSS is nice, I really mean just a minimal 
example so we don't have to rely on e. g. PHP or so. Just for tiny interfaces, a
bit similar to libui.

I don't know how easy that would be. GTK in itself is quite big if you include all the
various glib, atk, pango, cairo, fontconfig and so forth so it may not be the ideal
toolkit. Unfortunately I don't know of many alternatives (libui uses gtk on linux
as far as I know).

Anyway I wanted to put this issue here; perhaps others can comment and chime
in, with more experience in regards to mruby, and have this issue more open for
perhaps 2 weeks or so before closing it? Either way please feel free to disregard -
I just wondered how feasible it would be to be able to use ruby on a small arduino
project where I may need to auto-capture images when the cat enters through
the cat door in the regular door (you can see lots of videos where people 
capture cat entry and cat leave through the cat door, so I am mostly interested
in this, but ideally without having to use C or C++ - so to stay in ruby as much
as possible, if that makes sense to others).

**Comment by kou** [comment]
https://github.com/ppibburr/mruby-gtk3 and/or https://github.com/jbreeden/mruby-ui will be what you want.

**Comment by HuBandiT** [comment]
Have you looked at Tk? Also available in Glimmer: https://github.com/AndyObtiva/glimmer-dsl-tk
