### ISSUE TITLE
gtk4: "warning: GRClosure invoking callback: already destroyed: GtkGestureDrag::drag-update"

### ISSUE THREAD

**Issue by HuBandiT** [ruby-gnome/ruby-gnome#1453]
(My apologies, this might be my mistake, I'm a newbie.)

When I create multiple instances of a custom widget (class written in Ruby) which has a `drag-update` handler, sooner or later the `drag-update` handler stops working, and instead each invocation will then emit this error message:

```
gtk4: "C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.4.9/lib/gobject-introspection/loader.rb:616: warning: GRClosure invoking callback: already destroyed: GtkGestureDrag::drag-update"
```

below is the code of the handler insertion:

```
      drag = Gtk::GestureDrag.new
      drag.button = Gdk::BUTTON_PRIMARY
      @gtk_picture_instance.add_controller drag

      drag.signal_connect("drag-update", @gtk_picture_instance) do |gesture, dx, dy, area|
          old_value = @gtk_adjustment_instance.value
          @gtk_adjustment_instance.value += dx * @pixel_scale

          next  if old_value == @gtk_adjustment_instance.value

          m_x, m_y = get_child_position @gtk_picture_instance
          move @gtk_picture_instance, @x_0 + @gtk_adjustment_instance.value / @pixel_scale, m_y
        end
 
```

It definitely feels odd to have to specify `@gtk_picture_instance` twice like that.

I'm assuming I'm doing something wrong (even something trivial)? Thank you in advance for any insight.

**Comment by rubyFeedback** [comment]
I can not be of help, sorry - I am still using ruby-gtk3. But it's cool to see other people push
for ruby-gtk4 so you have my thumbs up. Hopefully if kou may find some time in the future
he could have a look - the gtk devs upstream keep on adding nice things to gtk4 so hopefully
we may all use gtk4 one day. :)
