### ISSUE TITLE
[Error / Possible bug] gobject-introspection/loader.rb:555:in `define_method': can't modify frozen Hash: {"create_pango_context"= [and a lot more output here]

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1455]
Hey there kou,

I just did "gem install gtk4" and then "gem install gtk3" to make sure I have the latest two gems installed.

I then downloaded via git clone the latest source code of ruby-gnome here.

Now, I navigate to this directory:

    cd /Depot/jjjj/ruby-gnome/gtk4/sample/

In that directory I run:

    ruby drawing.rb

I then get exactly this error:

    /Depot/jjjj/ruby-gnome/gobject-introspection/lib/gobject-introspection/loader.rb:555:in `define_method':
    can't modify frozen Hash: {"create_pango_context"= [and a lot more output here]

Not entirely certain where the error is but I suppose there are not that many instances of hash usage in that .rb file. In fact,
in the .rb file I can not seem to find any Hash at all, so perhaps gobject-introspection does something "behind the scene".

(Prior to that I had a ractor-related error, but that error went away after I did the two "gem install" commands.)

**Comment by rexkogitans** [comment]
@rubyFeedback I have exactly the same problem. Did you solve it?

**Comment by HuBandiT** [comment]
Temporary workaround: #1474

**Comment by kou** [comment]
Fixed.
