### ISSUE TITLE
Can not do "gem install gtk2" anymore

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1458]
My glib version is: 2.70.2

Perhaps I have to downgrade.

When trying:

"gem install gtk2"

it fails. The output will be shown in a moment; "gem install gtk3" works fine.

    gem install gtk2
    Fetching glib2-3.4.3.gem
    Fetching pkg-config-1.4.7.gem
    Fetching red-colors-0.3.0.gem
    Fetching native-package-installer-1.1.1.gem
    Fetching cairo-1.17.5.gem
    Fetching cairo-gobject-3.4.3.gem
    Fetching gobject-introspection-3.4.3.gem
    Fetching pango-3.4.3.gem
    Fetching gio2-3.4.3.gem
    Fetching gdk_pixbuf2-3.4.3.gem
    Fetching atk-3.4.3.gem
    Fetching gtk2-3.4.3.gem
    Successfully installed pkg-config-1.4.7
    Successfully installed native-package-installer-1.1.1
    Building native extensions. This could take a while...
    ERROR:  Error installing gtk2:
	    ERROR: Failed to build gem native extension.

        current directory: /root/.gem/gems/glib2-3.4.3/ext/glib2
    /usr/bin/ruby -I /usr/lib/ruby/site_ruby/3.1.0 -r ./siteconf20220116-14998-519xz.rb extconf.rb
    checking for --enable-debug-build option... no
    checking for -Wall option to compiler... yes
    checking for -Waggregate-return option to compiler... yes
    checking for -Wcast-align option to compiler... yes
    checking for -Wextra option to compiler... no
    checking for -Wformat=2 option to compiler... yes
    checking for -Winit-self option to compiler... yes
    checking for -Wlarger-than-65500 option to compiler... yes
    checking for -Wmissing-declarations option to compiler... yes
    checking for -Wmissing-format-attribute option to compiler... yes
    checking for -Wmissing-include-dirs option to compiler... yes
    checking for -Wmissing-noreturn option to compiler... yes
    checking for -Wmissing-prototypes option to compiler... yes
    checking for -Wnested-externs option to compiler... yes
    checking for -Wold-style-definition option to compiler... yes
    checking for -Wpacked option to compiler... yes
    checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
    checking for -Wpointer-arith option to compiler... yes
    checking for -Wundef option to compiler... yes
    checking for -Wout-of-line-declaration option to compiler... no
    checking for -Wunsafe-loop-optimizations option to compiler... yes
    checking for -Wwrite-strings option to compiler... yes
    checking for Homebrew... no
    checking for gobject-2.0 version (>= 2.12.0)... yes
    checking for gthread-2.0... yes
    checking for unistd.h... yes
    checking for io.h... no
    checking for g_spawn_close_pid() in glib.h... yes
    checking for g_thread_init() in glib.h... yes
    checking for g_main_depth() in glib.h... yes
    checking for g_listenv() in glib.h... yes
    checking for rb_check_array_type() in ruby.h... yes
    checking for rb_check_hash_type() in ruby.h... yes
    checking for rb_exec_recursive() in ruby.h... yes
    checking for rb_errinfo() in ruby.h... yes
    checking for rb_thread_call_without_gvl() in ruby.h... yes
    checking for ruby_native_thread_p() in ruby.h... yes
    checking for rb_thread_call_with_gvl() in ruby.h... yes
    checking for rb_gc_register_mark_object() in ruby.h... yes
    checking for rb_exc_new_str() in ruby.h... yes
    checking for rb_enc_str_new_static() in ruby.h... yes
    checking for curr_thread in ruby.h,node.h... no
    checking for rb_curr_thread in ruby.h,node.h... no
    creating ruby-glib2.pc
    creating glib-enum-types.c
    creating glib-enum-types.h
    creating Makefile
    
    current directory: /root/.gem/gems/glib2-3.4.3/ext/glib2
    make DESTDIR\= clean

    current directory: /root/.gem/gems/glib2-3.4.3/ext/glib2
    make DESTDIR\=
    compiling glib-enum-types.c
    In file included from glib-enum-types.c:4:
    rbgprivate.h:61:24: error: unknown type name ‘GStaticPrivate’
       61 | G_GNUC_INTERNAL extern GStaticPrivate rg_polling_key;
          |                        ^~~~~~~~~~~~~~
    make: *** [Makefile:246: glib-enum-types.o] Error 1
    
    make failed, exit code 2

    Gem files will remain installed in /root/.gem/gems/glib2-3.4.3 for inspection.
    Results logged to /root/.gem/extensions/x86_64-linux/3.1.0/glib2-3.4.3/gem_make.out

**Comment by kou** [comment]
We dropped support for gtk2 gem because the upstream GTK+ 2 reached EOL.
