### ISSUE TITLE
Mac Menu Bar

### ISSUE THREAD

**Issue by AndyObtiva** [ruby-gnome/ruby-gnome#1463]
How do I write GTK3 code to implement a true Mac menubar?

For example, when I run the code in https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk3/sample/misc/menu.rb, I get an embedded menubar inside the application as opposed to a true menubar at the top in the Mac display:

![Screen Shot 2022-01-27 at 7 07 07 PM](https://user-images.githubusercontent.com/23052/151464073-ff7ae466-d380-47a4-bd3f-955c4bbe9339.png)

Notice how the Mac menubar only has the Apple and "ruby" menus while the actually declared menus "test line 2", "foo", and "bar" are showing inside the application window instead.

Does GTK3 even support integrating with the Mac menubar from Ruby?

Clarification is highly appreciated.

**Comment by kou** [comment]
You can use the style automatically with GTK4 and `Gtk::Application`.
https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk4/sample/examples/hello_world.rb is one of examples to use GTK4 and `Gtk::Application` but it doesn't use a menu.
