### ISSUE TITLE
Could an example be added to "goffice" gem?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1464]
Hey there,

Would it be possible to add an example for the goffice gem?

I could install the gem just fine:

    Building native extensions. This could take a while...
    Successfully installed goffice-3.5.1
    Parsing documentation for goffice-3.5.1
    Installing ri documentation for goffice-3.5.1
    Done installing documentation for goffice after 0 seconds
    1 gem installed

But now I am not certain what to do with it. Thank you for considering!

**Comment by kou** [comment]
Generally, goffice gem isn't used directly. Users will use goffice gem with gnumeric gem. But there is no example for gnumeric gem too...

**Comment by kojix2** [comment]
I agree with Ruby Feedback, people who visit ruby-gnome wonder what goffice is. 

I also wondered what it was, and forgot about it.

I think just a few lines of explanation is enough. It will help those who are curious.
