### ISSUE TITLE
Missing docs on https://ruby-gnome2.osdn.jp/

### ISSUE THREAD

**Issue by colinm** [ruby-gnome/ruby-gnome#1465]
Where did the docs go for gtk2/3 from https://ruby-gnome2.osdn.jp ? does anyone have a clone or a copy?

**Comment by kou** [comment]
Oh...
I don't know why but it seems that all data were lost around 2022-03-11 04:39... I confirmed this by `ssh shell.osdn.net`.
Files that can't be accessed from Web were also removed. So I think that someone removed flies on `shell.osdn.net`...

There is a backup on 2008-03-29.

Anyway, we should change our official Web site to GitHub pages or somewhere from osdn.jp.

**Comment by kojix2** [comment]
I vote to use Github Pages.
If the documentation is on a branch, it is easy to migrate from Github to another source code host.

**Comment by colinm** [comment]
Not that I'm a contributor, but GitHub pages is a solid & logical move! :)

**Comment by neet93** [comment]
How can I help with that effort to move to Github Pages? I've thirsting for up-to-date documentation of GTK for Ruby!

**Comment by kou** [comment]
Ah, we also have another backup at 2011-03-10: https://github.com/ruby-gnome/doc

Anyway, I've created a new repository for GitHub Pages: https://github.com/ruby-gnome/ruby-gnome.github.io

We can discuss this in the repository.

**Comment by kojix2** [comment]
I wrote it using Github Actions. Making prototypes is one of the contributions.
I think it's too hard and impractical to document by hand.

Github Actions:
https://github.com/kojix2/ruby-gnome/blob/kojix2-doc-challenge/.github/workflows/doc.yml

Deployed docs:
https://kojix2.github.io/ruby-gnome/
