### ISSUE TITLE
require "gtk4" fails

### ISSUE THREAD

**Issue by SamiSieranoja** [ruby-gnome/ruby-gnome#1479]
I get the following error when loading gtk4(3.5.1):

```
  irb(main):001:0> require "gtk4"
  /var/lib/gems/3.0.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:555:in `define_method': can't modify frozen Hash:  ...

```
Whole message is in attachment. OS Ubuntu 22.04. Gtk3 works fine. 

[gtk4_debug.txt](https://github.com/ruby-gnome/ruby-gnome/files/8848127/gtk4_debug.txt)

**Comment by kou** [comment]
I'm working on this. Sorry.

See also: #1474, #1455 (duplicated)
