### ISSUE TITLE
libsecret - no implicit conversion of Secret::SchemaAttributeType into String

### ISSUE THREAD

**Issue by spchamp** [ruby-gnome/ruby-gnome#1481]
Following along with the [Python examples for Libsecret](https://developer-old.gnome.org/libsecret/0.20/py-examples.html) I was trying to define a **Secret::Schema** instance in Ruby, using Ruby-GNOME, such as to use when storing or retrieving a credentials token with libsecret. 

For the first item in that usage case, I've tested this with the following Ruby code:

~~~~
require 'gtk3'
require 'libsecret'
$SCHEMA = Secret::Schema.new(
  "space.thinkum.pebbl.test01", :none,
  {"name" => Secret::SchemaAttributeType::STRING,
   "token" => Secret::SchemaAttributeType::STRING
  })
~~~~

When evaluating the last form, an error is produced from the gobject-introspection loader, "no implicit conversion of Secret::SchemaAttributeType into String (TypeError) "

~~~~
irb(main):005:1* $SCHEMA = Secret::Schema.new(
irb(main):006:1*   "space.thinkum.pebbl.test01", :none,
irb(main):007:2*   {"name" => Secret::SchemaAttributeType::STRING,
irb(main):008:2*    "token" => Secret::SchemaAttributeType::STRING
irb(main):009:0>   })
/opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke': no implicit conversion of Secret::SchemaAttributeType into String (TypeError)                                                                             
        from /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'
        from /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:347:in `block (2 levels) in initialize'
        from /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:346:in `catch'
        from /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:346:in `block in initialize'
        from /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:345:in `each'
        from /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:345:in `initialize'
        from (irb):5:in `new'
        from (irb):5:in `<main>'
        from ./bin/gtkconsole:38:in `<main>'
~~~~

If providing a string for each attribute type in the schema, then glib's logger produces a warning, e.g "invalid type for attribute name"
~~~~
Secret::SchemaAttributeType::STRING.name
=> "SECRET_SCHEMA_ATTRIBUTE_STRING"

irb(main):043:1* $SCHEMA = Secret::Schema.new(
irb(main):044:1*   "space.thinkum.pebbl.test01", :none,
irb(main):045:2*   {"name" => Secret::SchemaAttributeType::STRING.name,
irb(main):046:2*    "token" => Secret::SchemaAttributeType::STRING.name
irb(main):047:0>   })

(gtkconsole:42226): libsecret-WARNING **: 09:44:12.440: invalid type for attribute name
(gtkconsole:42226): libsecret-WARNING **: 09:44:12.440: invalid type for attribute token

=> #<Secret::Schema:0x000000080d3bd2c8 ptr=0x000000080e26e4e0 own=true>
~~~~

Towards trying to understand how the API is implemented in Ruby-GNOME, I've noticed that the single constructor for `Secret::Schema` expects a ghash type as its third arg

~~~~
init_invokers = Secret::Schema::INITIALIZE_INVOKERS.values
=> ...
init_invokers.length
=> 1
init_invokers[0].instance_variable_get(:@full_method_name)
=> "Secret::Schema#initialize_new"
init_invokers[0].instance_variable_get(:@in_arg_types)
=> 
[#<GObjectIntrospection::TypeInfo:0x0000000810055268 ptr=0x000000080c273540 own=true tag=#<GObjectIntrospection::TypeTag utf8>>,
 #<GObjectIntrospection::TypeInfo:0x0000000810055240 ptr=0x000000080c2732d0 own=true tag=#<GObjectIntrospection::TypeTag interface>>,
 #<GObjectIntrospection::TypeInfo:0x0000000810055218 ptr=0x000000080c273230 own=true tag=#<GObjectIntrospection::TypeTag ghash>>]
~~~~

In a guess, albeit: Perhaps the ghash type may be providing a mapping for strings to strings? or perhaps that error emits from elsewhere.

There is the error if trying to provide a Secret::SchemaAttributeType as the value for any entry in the hash object, where the API in Ruby expects a string.

Perhaps the API in GNOME may expect an integer value for each attribute type?
~~~~
Secret::SchemaAttributeType::STRING.to_int
=> 0
Secret::SchemaAttributeType::INTEGER.to_int
=> 1
Secret::SchemaAttributeType::BOOLEAN.to_int
=> 2
~~~~

With the warning from libsecret when providing a string for each attribute type to the API in GNOME and the possible mismatch to the enum values in the examples, I've not tried to proceed any further after the [libsecret Python example](https://developer-old.gnome.org/libsecret/0.20/py-examples.html).  Certainly, the [documentation for the SecretSchema type](https://developer-old.gnome.org/libsecret/0.20/libsecret-SecretSchema.html#SecretSchema) mentions that attribute  values are stored as strings. For the schema definition, perhaps it may need a schema attribute type for each named attribute however?

If it may be possible to approach this with a local patch, I wonder if there may be some way to define a type mapping specifically for the third arg to the Secret::Schema initialization invoker in Ruby, using a new _Custom type_ onto glib to facilitate the type mapping? I'll try to test  this approach locally, if I can figure out how to develop an extension onto GLib's `GHashTable` type in Ruby, perhaps also to ensure it has a type tag for the gobject-introspection support. Perhaps there may be any other approach.

Towards making a custom type of `GHashTable`, perhaps a custom type for this type of object would need to be defined and compiled in C, along with any custom type in Ruby by this approach?

Though I've interacted with C source code to some extent, perhaps I myself may not be able to provide any immediate patch for this. I'm certain that there must be more than one way to approach it, though perhaps all ways would lead through C here.

Towards an example of a usage case, perhaps the libsecret API could be used for _web client applications_ using the Ruby-GNOME support. I'm certain there must be an innumerable number of possible usage cases for web client support, not only for a FreeBSD bugzilla client lol. 

For the web client usage case, perhaps there may be a way to hack some indirection using a JavaScript API for the credentials storage, via the GTK WebKit support in Ruby-GNOME, or via any features in GTK WebKit where GTK Webkit may be using libsecret for credentials storage.

If libsecret could be used to store and retrieve authentication credentials directly, then ostensibly any HTTP client API in Ruby could be used with this.

**Comment by kou** [comment]
This is just a bug.
I've fixed the bug.

**Comment by spchamp** [comment]
I've updated my project Gemfile to install the Ruby-GNOME gems from GitHub sources. I can evaluate the following now:

~~~~
require 'gtk3'
require 'libsecret'
$SCHEMA = Secret::Schema.new(
  "space.thinkum.pebbl.test01", :none,
  {"name" => Secret::SchemaAttributeType::STRING,
   "token" => Secret::SchemaAttributeType::STRING,
  })
~~~~

I'm seeing a new error when trying to access the attributes method on the libsecret schema object
~~~~
 $SCHEMA.attributes
~~~~

The error I'm seeing:
~~~~
/longpath/rblib/vendor/bundle/ruby/3.1/bundler/gems/ruby-gnome-a09fcaceb5cf/gobject-introspection/lib/gobject-introspection/loader.rb:283:in `get_field_value': TODO: GIArgument(array)[c] -> Ruby: zero-terminated: false fixed-size: 32 length: -1 (NotImplementedError)
	from /longpath/rblib/vendor/bundle/ruby/3.1/bundler/gems/ruby-gnome-a09fcaceb5cf/gobject-introspection/lib/gobject-introspection/loader.rb:283:in `block in load_field_reader'
	from (irb):13:in `<main>'
	from -e:1:in `<main>'
~~~~

Perhaps the schema attributes value may still be usable to libsecret, whether or not it can be accessed for evaluation in Ruby? To test this, I'll try taking a look at the rest of the libsecret walkthrough for Python, towards porting it to Ruby

**Comment by kou** [comment]
I've implemented the case.
