### ISSUE TITLE
Two probably minor issues with gtk4 - utils.rb, and a frozen Hash

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1485]
(1) Right now the examples in the gtk4/ subdirectory require the file utils.rb.

Would it be possible to make the gtk4 examples standalone? This is not a big issue either way, but more of a convenience, so that I can run e. g. the hello world example without needing a separate .rb file (e. g. if we can somehow integrate or avoid utils.rb).

(2) The more important issue is that I run into the following problem, of a frozen Hash:

    gobject-introspection/loader.rb:555:in `define_method': can't modify frozen Hash:
     {"create_pango_context"=>#<GObjectIntrospection::Loader::Invoker:0x00007f643e89d2b8
    @info=#<GObjectIntrospection::FunctionInfo:0x00007f643e89d4c0 ptr=0x000055c3b8a7c850
    own=true signature=<create_context(cr: interface(CairoGObject::Context(CairoContext))): 
    _arg_nil_indexes=[], @function_info_p=true, @have_return_value_p=false, @require_callback_p=false, 
    @on_invalid=:raise>} (FrozenError)
    # lots more output here from that big Hash ^^^
    from /root/.gem/gems/gdk4-3.5.1/lib/gdk4/loader.rb:73:in `load_function_info'

The example I used was the grid-packer example.

For convenience I will copy/paste it next, but it is in the sample/ subdirectory of the ruby-gnome project.

    require_relative "utils"

    require_gtk4

    application = Gtk::Application.new("org.gtk.example", :flags_none)

    application.signal_connect "activate" do |app|
      # Create a new window and set its title
      win = Gtk::ApplicationWindow.new(app)
      win.title = "window"
    
      # Here we construct the container that is going to pack our buttons.
      grid = Gtk::Grid.new
    
      # Pack the container in the window
      win.add(grid)
    
      button = Gtk::Button.new(:label => "Button 1")
      button.signal_connect("clicked") { puts "Hello World!" }
    
      # Place the first button in the grid cell (0, 0), and make it fill
      # just 1 cell horizontally and vertically (ie no spanning)
      grid.attach(button, 0, 0, 1, 1)
    
      button = Gtk::Button.new(:label => "Button 2")
      button.signal_connect("clicked") { puts "Hello World!" }
    
      # Place the second button in the grid cell (1, 0), and make it fill
      # just 1 cell horizontally and vertically (ie no spanning)
      grid.attach(button, 1, 0, 1, 1)
    
      button = Gtk::Button.new(:label => "Quit")
      button.signal_connect("clicked") { win.destroy }
    
      # Place the Quit button in the grid cell (0, 1), and make it
      # span 2 columns.
      grid.attach(button, 0, 1, 2, 1)
    
      win.show
    end
    
    application.run

Thanks for reading. Right now I am using ruby-gtk3 exclusively and it works
very well; I am still playing around with the CSS functionality. You can do
quite interesting effects with it, such as animations via keyframes.

I'd love to test this on ruby-gtk4 too but I can not get gtk4 to work. Considering
we are already at gtk 4.6.6 and gtk 4.7.0 it would be great to have ruby work on
it too. Unfortunately I do not know C so I am of very limited help.

On https://www.gtk.org/ they mention the following languages in the first
example:

    C, JavaScript, Perl, Python, Rust, Vala

Would be nice to add ruby support there too. :D  (The python example there
uses gtk4 for instance, I also just tested it, it works).

**Comment by cyclotron3k** [comment]
I think I'm seeing the same `FrozenError` issue as you:

```
$ irb
irb(main):001:0> require 'gtk4'
/home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:555:in `define_method': can't modify frozen Hash: {"create_pango_context"=>#<GObjectIntrospection::Loader::Invoker:0x00007feb0ae402a8 [...snip...]} (FrozenError)
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gdk4-3.5.1/lib/gdk4/loader.rb:73:in `load_function_info'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:63:in `load_info'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:47:in `block (2 levels) in load'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/repository.rb:34:in `block (2 levels) in each'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/repository.rb:33:in `times'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/repository.rb:33:in `block in each'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/repository.rb:32:in `each'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/repository.rb:32:in `each'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:46:in `block in load'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:622:in `prepare_class'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:41:in `load'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gdk4-3.5.1/lib/gdk4/loader.rb:21:in `load'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gdk4-3.5.1/lib/gdk4.rb:34:in `<module:Gdk>'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gdk4-3.5.1/lib/gdk4.rb:26:in `<top (required)>'
	from <internal:/home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	... 8 levels...
<internal:/home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- gtk4 (LoadError)
	from <internal:/home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from (irb):1:in `<main>'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/bin/irb:25:in `load'
	from /home/cyclotron3k/.rbenv/versions/3.1.2/bin/irb:25:in `<main>'
irb(main):002:0> 
```

**Comment by kou** [comment]
gtk4 works on the master branch but it's not released yet.
(I hope that I can release a new version in this month...)

**Comment by kou** [comment]
Released.
