### ISSUE TITLE
Exceptions and segfault in iteration with Gtk::AccelMap

### ISSUE THREAD

**Issue by spchamp** [ruby-gnome/ruby-gnome#1487]
Is there a way to use the  `Gtk::AccelMap.each` or `Gtk::AccelMap.foreach_unfiltered` methods without producing a segfault or an exception on a null value?

The following code produces a segfault in each of the methods `test_mapping_a` and `test_mapping_b`

For each of the methods `test_mapping_c` and `test_mapping_d`, an exception is raised, for instance, `undefined method 'each' for nil:NilClass (NoMethodError)`. The iterator used in each of methods is not in itself nil.

~~~~
require 'gtk3'

class TestProxy

  def initialize()
    wdw = Gtk::Window.new
    ## create an AccelGroup and add an AccelMap binding
    group = Gtk::AccelGroup.new
    wdw.add_accel_group(group)
    ## Key 'n' in $PREFIX/include/gtk-3.0/gdk/gdkkeysyms.h
    ## has key code 0x06e
    Gtk::AccelMap.add_entry("<TestProxy>/Test/Test 01", 0x06e,
                            Gdk::ModifierType::MOD1_MASK)
  end


  def test_mapping_a
    ## test for unfiltered iteration on the global AccelMap
    ## => segfault
    Gtk::AccelMap.foreach_unfiltered do |path, key, mods, changed|
      GLib::Log.info("[KEYS] %s => [%s] %s (%p)" % [
        path, mods, key, changed
      ])
    end
  end

  def test_mapping_b
    ## test for iteration with the filtered API on the global AccelMap
    ## => segfault
    Gtk::AccelMap.each do |path, key, mods, changed|
      GLib::Log.info("[KEYS] %s => [%s] %s (%p)" % [
        path, mods, key, changed
      ])
    end
  end

  def test_mapping_c
    ## test for iteration on the uniltered global AccelMap, via an iterator
    ## => undefined method `foreach_unfiltered' for nil:NilClass (NoMethodError)
    iter = Gtk::AccelMap.foreach_unfiltered
    raise "null iterator" if iter.nil? ## ensure this is not nil
    iter.each do |path, key, mods, changed|
      GLib::Log.info("[KEYS] %s => [%s] %s (%p)" % [
        path, mods, key, changed
      ])
    end
  end

  def test_mapping_d
    ## test for iteration on the filtered global AccelMap, via an iterator
    ## => undefined method `each' for nil:NilClass (NoMethodError)
    iter = Gtk::AccelMap.each
    raise "null iterator" if iter.nil? ## ensure this is not nil
    iter.each do |path, key, mods, changed|
      GLib::Log.info("[KEYS] %s => [%s] %s (%p)" % [
        path, mods, key, changed
      ])
    end
  end


end
~~~~

With the two methods illustrated above, such that do not result in segfault, I'm seeing the following exceptions:
~~~~
irb(main):001:0> require_relative '[sic]/accel-test'                                                                        
=> true                                                                                                                           
irb(main):002:0> obj = TestProxy.new                              
=> #<TestProxy:0x0000000808638b60>

irb(main):003:0> obj.test_mapping_c                               
[sic]/accel-test.rb:39:in `each': undefined method `foreach_unfiltered' for nil:NilClass (NoMethodError)                                                                            
                                                                                               
    iter.each do |path, key, mods, changed|                                                    
        ^^^^^                                                                                  
        from [sic]/accel-test.rb:39:in `test_mapping_c'
        from (irb):3:in `<main>'                                                               
        from ./bin/console:129:in `<main>'                                                     

irb(main):004:0> obj.test_mapping_d                               
[sic]/accel-bug-test.rb:49:in `each': undefined method `each' for nil:NilClass (NoMethodError)                                                                                          
        from [sic]/accel-test.rb:49:in `test_mapping_d'
        from (irb):4:in `<main>'                                          
        from ./bin/console:129:in `<main>'
 ~~~~

Although I'm not really certain if this code meets the requirements of the API, I believe it matches generally with the function signatures displayed in the GNOME Devhelp documentation for GTK 3

Trying to understand how this is implemented, I've looked at the source code in `gtk3-no-gi/ext/gtk3/rbgtk-accel-map.c`. Now noticing the pathname of that file, I don't believe that's being used here though. 

With a rudimentary search, I was not able to able to locate any specific AccelMap interface in the gtk3 gem. 

I'd discovered this segfault/exception behavior when trying to use an AccelMap iterator in application with a Gtk::TreeView, such that the TreeView would be used in a user interface for an application preferences dialog window.  This user interface may not in itself depend on the AccelMap.each methods. Hypothetically, it may be one approach towards providing a user interface for editing any editable key bindings in an application.

For this usage case, there may be a workaround in iterating on a value singularly in the Ruby environment, rather than iterating on the global AccelMap itself. That may be an ideal approach. It would allow for the caller's API  to ensure that not any mappings would be shown for any  'locked' accel paths, such as for any binding of an accel path to 'Esc` that may not be easily configured with this interface.

For the general case of iterating on any accel paths and bindings defined to the global Gtk::AccelMap, while I'm not absolutely certain if it is a bug, it seems that it may be?

**Comment by kou** [comment]
The [`gtk_accel_map_foreach()`](https://docs.gtk.org/gtk3/type_func.AccelMap.foreach.html) and [`gtk_accel_map_foreach_unfiltered()`](https://docs.gtk.org/gtk3/type_func.AccelMap.foreach_unfiltered.html) don't follow general GObject callback convention. Generally, `x(XXXFunc xxx_func, gpointer data)` style is used but they use `x(gpointer data, XXXFunc xx_func)` style. The gtk3 gem uses GObject Introspection that generates Ruby bindings automatically with metadata. But GObject Introspection can't detect correct metadata with the wrong style.

We can add support for this case by implementing Ruby bindings by hand. FYI: `Gtk::AccelMap` has been removed in GTK 4: https://docs.gtk.org/gtk4/migrating-3to4.html#use-the-new-apis-for-keyboard-shortcuts

**Comment by kou** [comment]
Implemented.

**Comment by spchamp** [comment]
Thank you for the info about GTK 4 and the implementation in GTK 3. This will affect the design of  terminal emulator using Ruby-GNOME, albeit it's still far from a first release.  It's good to have an of idea of how much of a redesign might be needed for GTK4 support in the application? 

The change set is very informative too. Thank you for making attention to this. There's much to consider, beside that I believe some of my own API for key codes has been redundant. 

If a Gtk::AccelMap binding can be modified at runtime, I'll try to retain this part of the thing. Perhaps the API for key bindings may be a little more unified in Gtk 4?
