### ISSUE TITLE
Performance situation in a gtk-combo box: are there recommendations to go about for large combo box entries above +2000 elements?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1492]
Hey there kou,

First let me copy/paste the example. This is probably making it easiest for you to
reproduce and then determine whether there is an issue or not.

So first the copy paste:

    #!/usr/bin/ruby -w
    # Encoding: UTF-8
    # frozen_string_literal: true
    # =========================================================================== #
    # $GTK_PARADISE/examples/gtk3/combo_box_example.rb
    # =========================================================================== #
    require 'gtk3'
    
    alias e puts
    
    window = Gtk::Window.new
    
    combo_box1 = Gtk::ComboBoxText.new
    
    # =========================================================================== #
    # === FROZEN_STRING_CONSTANT
    #
    # Should be frozen.
    # =========================================================================== #
    FROZEN_STRING_CONSTANT = 'ABC'
    
    # =========================================================================== #
    # === ARRAY_FOR_COMBO_BOX1
    # =========================================================================== #
    ARRAY_FOR_COMBO_BOX1 = %w(
      combo_box_entry1
      combo_box_entry2
      combo_box_entry3
      combo_box_entry4
      combo_box_entry5
      combo_box_entry6
      combo_box_entry7
      combo_box_entry8
    )
    
    # =========================================================================== #
    # 2500 additions to a combo box cause a delay already. We can toggle that
    # number to lower or higher values, and see whether this makes any
    # difference.
    # =========================================================================== #
    N_TIMES = 2_500
    N_TIMES.times {
      ARRAY_FOR_COMBO_BOX1 << FROZEN_STRING_CONSTANT
    }
    
    ARRAY_FOR_COMBO_BOX1.each { |val| 
      combo_box1.append_text(val) 
    }
    combo_box1.active = 3
    vbox = Gtk::Box.new(:vertical)
    vbox.add(Gtk::Label.new('Showing '+N_TIMES.to_s+' entries next'))
    vbox.add(combo_box1)
    
    combo_box2 = Gtk::ComboBoxText.new
    combo_box2.wrap_width = 5 # This means to pad 5 entries per row.
    %w( one two three four five six ).each { |val| 
      combo_box2.append_text(val) 
    }
    combo_box2.active = 4
    combo_box2.signal_connect(:changed) {
      if combo_box2.active_iter
        e "#{combo_box2.active}: #{combo_box2.active_iter[0]}"
      end
    }
    vbox.add(combo_box2)
    
    window.add(vbox)
    window.show_all
    window.move(0, 0)
    window.set_size_request(800, 800)
    Gtk.main

Ok. I took this from my gem gtk_paradise and adapted it a bit, e. g.
added the N_TIMES constant. This constant we can change, e. .g.
to a lower value and then the gtk-application will be much faster.

When I change the value to about 2_500 I get this warning:

    (034_combo_box_example.rb:12574): Gdk-WARNING **: 00:36:13.846: Native Windows wider or taller than 32767 pixels are not supported

Not sure why this happens but I assume it is doing some
internal calculation about how much down a window can
scroll, or something.

So background:

I also maintain the rbt gem, which I use to compile stuff
from source on linux.

I track about 3700 different programs so far, all via yaml
files but I also experiment with sqlite now. Anyway.

In one of the ruby-gtk3 wrappers I wanted to have:

a) completion supprt e. g. gtk-entry completion model.
So that if the user types something like "rub" then
it may be completed to "ruby" in a drop down listing.
This is quite convenient.

b) a combo box entry showing ALL registered programs.
So I need +3700 entries. And this should work fast,
e. g. not freeze the app.

Unfortunately the application kind of freezes when
I have too many elements.

I assume it has to do with gobject-introspection
doing some dynamic loading which causes problems.

I also assume that if the same .rb example I showed
above, written in C, would not have this speed penalty.
Correct? Probably because C is faster than C, we
can compile things, and we don't need gobject
introspection. But it is also disappointing to me.

It means that javascript on the www is MUCH more
efficient than ruby-gtk, because I think we can
add tons of entries to a web formular with a drop
down listing. 

Of course I may have also done something wrong. But my
example shown above is really quite simple, and the
problem already shows in it. The window kind of 
takes like 20 seconds to load if you have a high
value for N_PROGRAMS like 5000, or even 3000,
and then even after it has loaded it is slow, or 
continues to be slow while using it. Is there some way
to populate a combo box without causing that combo
box to slow down? Perhaps another method that
could allow us to populate it?

Anyway, I report this just so that you are aware. My C
knowledge is very limited unfortunately so I am not sure
I can be of much help.

**Comment by kou** [comment]
This is not a Ruby problem.

You should not `Gtk::CombBoxText` for this use case.

A simplified C version:

```c
/* cc -o XXX XXX.c $(pkg-config --cflags --libs gtk+3.0) */
#include <gtk/gtk.h>

int
main(int argc, char **argv)
{
  gtk_init(&argc, &argv);
  GtkWidget *window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
  GtkWidget *combo_box = gtk_combo_box_text_new();
  GDateTime *begin = g_date_time_new_now_local();
  for (int i = 0; i < 2500; i++) {
    gtk_combo_box_text_append_text(GTK_COMBO_BOX_TEXT(combo_box), "a");
  }
  gtk_container_add(GTK_CONTAINER(window), combo_box);
  gtk_widget_show_all(window);
  GDateTime *end = g_date_time_new_now_local();
  g_print("initialized: %f\n", g_date_time_difference(end, begin) / 1000.0 / 1000.0);
  g_date_time_unref(begin);
  g_date_time_unref(end);
  gtk_main();
  return 0;
}
```

It outputs the following on my environment:

```text
initialized: 2.019771

(aa:484634): Gdk-WARNING **: 23:00:10.003: Native Windows wider or taller than 32767 pixels are not supported

(aa:484634): Gdk-WARNING **: 23:00:10.003: Native Windows wider or taller than 32767 pixels are not supported
```

Could you try `Gtk::ListStore` and `Gtk::TreeView` instead?
See also:
* https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk3/sample/misc/listview.rb
* https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk3/sample/gtk-demo/list_store.rb

**Comment by kou** [comment]
No response.
