### ISSUE TITLE
Exit status 1 after Gtk.main_quit

### ISSUE THREAD

**Issue by mvz** [ruby-gnome/ruby-gnome#1495]
With release 4.0.1, I'm getting exit status set to 1 when calling Gtk.main_quit from a signal handler, for example for a button (but not for the `destroy` signal).

I can reproduce this with sample apps such as `gtk3/samples/misc/window.rb` and `gtk3/samples/misc/button.rb`, but only with installed gems. If I use `run.sh` from the repo the exit code is 0.

**Comment by kou** [comment]
Hmm... I couldn't reproduce it on local. What is your environment?

**Comment by mvz** [comment]
I'm running on Debian sid using libgtk-3-0 3.24.34-3 with Ruby 3.1.2p20.

I've run a git bisect and it seems the relevant change is in ff40f62a1095fe4e0d58976d0fcf19355a65f279. If I revert that change in master and add back `g_rclosure_attach_gobject`, (see this branch: https://github.com/mvz/ruby-gnome/tree/fix-exit-code-experimental) the problem no longer happens.

Please let me know if you need any more info about my environment; I'm not sure what to include.

**Comment by kou** [comment]
Thanks. I could reproduce this with the following change on my local Debian GNU/Linux sid:

```diff
--- a/gtk3/sample/misc/menu.rb
+++ b/gtk3/sample/misc/menu.rb
@@ -98,4 +98,6 @@ box2.pack_start(button, :expand => true, :fill => true, :padding => 0)
 
 window.show_all
 
+GC.stress = true
+
 Gtk.main
```

**Comment by kou** [comment]
Could you try https://github.com/ruby-gnome/ruby-gnome/commit/2827d92aa82de5431c3038130ae0aa2c9c392128 ?

**Comment by mvz** [comment]
Yes, that commit fixes the problem for me as well. Thanks!

**Comment by kou** [comment]
Good to know!
