### ISSUE TITLE
ruby gobject-introspection 4.0.1 testsuite segfaults

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome/ruby-gnome#1496]
With ruby gobject-introspection 4.0.1 as well as master (  f9394e9998c7cf4f41b281430bca9708b6fb34d7 ) test suite segfaults.  
With 3.5.1, I tried rebuilding and test passes (no segfault), so currently this issue does not seem to be due to ruby or libffi side issue.

Using Fedora 37 system:

* ruby-3.1.2-167.fc37.x86_64
* libffi-3.4.2-9.fc37.x86_64

[run-test-rgobject-introspection.log.txt](https://github.com/ruby-gnome/ruby-gnome/files/9484190/run-test-rgobject-introspection.log.txt)

[gdb-rgobject-introspection-nocolor.log.txt](https://github.com/ruby-gnome/ruby-gnome/files/9484192/gdb-rgobject-introspection-nocolor.log.txt)

**Comment by mtasaka** [comment]
git bisect shows:

```
2f9aac9f03945e629e072bd047f4e3f6a1f14378 is the first bad commit
commit 2f9aac9f03945e629e072bd047f4e3f6a1f14378
Author: Sutou Kouhei <kou@clear-code.com>
Date:   Tue Jun 28 11:56:55 2022 +0900

    gi: don't use deprecated g_callable_info_{prepare,free}_closure()

 .../ext/gobject-introspection/rb-gi-callback.c     | 27 +++++++++++++++++-----
 1 file changed, 21 insertions(+), 6 deletions(-)
```

I tried master ( f9394e9998c7cf4f41b281430bca9708b6fb34d7 ) with ( 2f9aac9f03945e629e072bd047f4e3f6a1f14378 ) only reverted and actually ruby-gobject-introspection test suite passes.

**Comment by mtasaka** [comment]
Note that I am using glib2-2.73.3-2.fc37.x86_64

**Comment by mtasaka** [comment]
... and gobject-introspection-1.73.0-2.fc37.x86_64

**Comment by mtasaka** [comment]
So although I am not sure exactly, looking at https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/283 , after adding the following change against current master (i.e. f9394e9998c7cf4f41b281430bca9708b6fb34d7 ), ruby-gobject-instrospection test suite passes.

```
diff --git a/gobject-introspection/ext/gobject-introspection/rb-gi-loader.c b/gobject-introspection/ext/gobject-introspection/rb-gi-loader.c
index 50d9922ff..bee6607d1 100644
--- a/gobject-introspection/ext/gobject-introspection/rb-gi-loader.c
+++ b/gobject-introspection/ext/gobject-introspection/rb-gi-loader.c
@@ -151,6 +151,7 @@ rg_s_implement_virtual_function(G_GNUC_UNUSED VALUE klass,
     GType vtable_gtype;
     const gchar *method_name;
     RBGICallback *callback;
+    GICallbackInfo *callback_info;
 
     field_info = RVAL2GI_FIELD_INFO(rb_field_info);
     implementor_gtype = rbgobj_gtype_from_ruby(rb_implementor_gtype);
@@ -159,12 +160,10 @@ rg_s_implement_virtual_function(G_GNUC_UNUSED VALUE klass,
 
     {
         GITypeInfo *type_info;
-        GICallbackInfo *callback_info;
 
         type_info = g_field_info_get_type(field_info);
         callback_info = g_type_info_get_interface(type_info);
         callback = rb_gi_callback_new(callback_info, method_name);
-        g_base_info_unref(callback_info);
         g_base_info_unref(type_info);
     }
 
@@ -183,7 +182,12 @@ rg_s_implement_virtual_function(G_GNUC_UNUSED VALUE klass,
         }
         offset = g_field_info_get_offset(field_info);
         method_address = G_STRUCT_MEMBER_P(vtable_struct, offset);
+#if GI_CHECK_VERSION(1, 72, 0)
+        *method_address = g_callable_info_get_closure_native_address(callback_info, callback->closure);
+#else
         *method_address = callback->closure;
+#endif
+        g_base_info_unref(callback_info);
         g_type_class_unref(implementor_struct);
     }
 
```

... although I am not sure this is correct... What I can say here is that `g_callable_info_create_closure` is not a simple replacement for `g_callable_info_prepare_closure`.

**Comment by kou** [comment]
Thanks for your report! You're right. Could you try https://github.com/ruby-gnome/ruby-gnome/commit/15ee40826a7cbcfef64b1a5b9d84c58cb4ee6916 ?

**Comment by mtasaka** [comment]
Yes, 15ee40826a7cbcfef64b1a5b9d84c58cb4ee6916 is working, thank you!

**Comment by kou** [comment]
Good to know!
