### ISSUE TITLE
Released gtk4 gem does not contain 'ext' code

### ISSUE THREAD

**Issue by anatol** [ruby-gnome/ruby-gnome#1498]
Grepping through 'gtk4' directory I see that it required `gtk4.so` library https://github.com/ruby-gnome/ruby-gnome/blob/09ba5ea6e8a557cb558b8aafcd8417cef1fbb497/gtk4/lib/gtk4/loader.rb#L69
that comes from `ext/gtk4` directory https://github.com/ruby-gnome/ruby-gnome/tree/09ba5ea6e8a557cb558b8aafcd8417cef1fbb497/gtk4/ext/gtk4

But when I download the released gem here https://rubygems.org/gems/gtk4/versions/4.0.2 it turns out it does not contain any `ext` thus it cannot build `gtk4.so`.

It looks like gtk4 project needs to be improved and add `ext` directory to the released gem file.

**Comment by rubyFeedback** [comment]
Aha! I ran into this issue too where it could not find gtk4.so, so I was
not sure where the error was. It perhaps did not show up for kou
when he wrote the code. I could not find gtk4.so after doing a "gem
install gtk4".

**Comment by kou** [comment]
Oh... I didn't notice it...
