### ISSUE TITLE
Possible Bug? Unable to use the "page up" and "page down" buttons for scrolling

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1499]
Heya kou,

Consider the following code:

    require 'gtk3'

    alias e puts

    window = Gtk::Window.new
    window.move(0, 0)
    text_buffer = Gtk::TextBuffer.new
    text_buffer.set_text(
      "Hello world!\n"*100
    )
    text_view = Gtk::TextView.new(text_buffer)
    text_view.set_size_request(1400, 1000)
    text_view 

    this_font = 'Sans 22'
    _ = Pango::FontDescription.new(this_font)
    window.override_font(_)
    
    box = Gtk::Box.new(:vertical)
    scrolled_window = Gtk::ScrolledWindow.new
    scrolled_window.add_with_viewport(text_view)
    box.pack_start(scrolled_window, fill: true, expand: true, padding: 10)
    box.show_all
    window.show_all
    window.add(box)
    window.set_size_request(1600, 1000)
    Gtk.main

Problem: When I hit "page up" or "page down" it does not scroll.

I believe in most GNOME3 applications this works by default.

I also think it used to work in ruby-gtk2. But perhaps there is
something wrong with my gtk-version.

Either way, I would like to ask:

(1) Can you, or anyone else, reproduce this issue? That is when
I can not get the scroll down or scroll up buttons (e. g. arrow up
and arrow down icons).

(2) Is there a simple way to fix this? I assume that I can somehow
override it via events, and then just reposition the slider/trough on
the right side. But before I investigate this here, I wanted to see
whether this is a bug. I am almost 100% certain this used to
work fine in ruby-gtk2. So I am not sure where the problem is.

If someone can reproduce, this would be helpful. I am having a 
few other issues that nobody else seems to have, but more on
this perhaps at a later time. For now I only want to find out
why my page down and page up buttons do not work as-is.

Thanks for reading!

**Comment by kou** [comment]
You need to put the `Gtk::TextBuffer` into the `Gtk::ScrolledWindow` without adding view port:

```ruby
require 'gtk3'

alias e puts

window = Gtk::Window.new
window.move(0, 0)
text_buffer = Gtk::TextBuffer.new
text_buffer.set_text(
  "Hello world!\n"*100
)
text_view = Gtk::TextView.new(text_buffer)
text_view.set_size_request(1400, 1000)
text_view 

this_font = 'Sans 22'
_ = Pango::FontDescription.new(this_font)
window.override_font(_)

scrolled_window = Gtk::ScrolledWindow.new
scrolled_window.add(text_view)
window.add(scrolled_window)
window.set_size_request(1600, 1000)
window.show_all
Gtk.main
```

**Comment by kou** [comment]
Can we close this?
