### ISSUE TITLE
[Small enhancement to ruby-gtk4, deprecation warning for Gdk::Screen]

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1503]
Hi,

I ran into this:

    /root/.gem/gems/glib2-4.0.3/lib/glib2/deprecatable.rb:127:in `const_missing': experimental_for_gtk4.rb:41:in `run': 'Gdk::Screen' has been deprecated. No longer available in GDK 4

It took me about 15 minutes of googling or so, or perhaps only 10 minutes.

This is the replacement code that seems to work:

    Gtk::StyleContext.add_provider_for_display(
          Gdk::Display.default,
          provider,
          Gtk::StyleProvider::PRIORITY_APPLICATION
        )

Perhaps the deprecation warning could be changed to hint to people that
Gdk::Display can be used instead?

I found out the replacement code from a python script by the way - very
useful that they figured out these things already. :)

**Comment by kou** [comment]
We can't replace all `Gdk::Screen` related features with `Gdk::Display`: https://docs.gtk.org/gtk4/migrating-3to4.html#stop-using-gdkscreen

> The GdkScreen object has been removed in GTK 4. Most of its APIs already had replacements in GTK 3 and were deprecated, a few remaining replacements have been added to GdkDisplay.

We already show a deprecation message that `Gtk::StyleContext.add_provider_for_display` is the alternative of `Gtk::StyleContext.add_provider_for_screen`:

https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk4/lib/gtk4/deprecated.rb#L838-L839
