### ISSUE TITLE
[ruby-gtk4] Oddity with Gtk::ScrolledWindow

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1504]
I get this odd error:

    /root/.gem/gems/gobject-introspection-4.0.3/lib/gobject-introspection/loader.rb:360:in `initialize': wrong arguments: 
    Gtk::ScrolledWindow#initialize(nil, nil): available signatures: ()

Test code I used:

    #!/usr/bin/ruby -w
    # Encoding: UTF-8
    # frozen_string_literal: true
    # =========================================================================== #
    require 'gtk4'

    application = Gtk::Application.new('org.gtk.text_view_example', :flags_none)

    application.signal_connect(:activate) { |app|
      win = Gtk::ApplicationWindow.new(app)
      win.title = 'Text View Example'
      win.set_default_size(120, 600)
      text_buffer = Gtk::TextBuffer.new
      text_buffer.set_text(
        "Hello world!\n" * 50
      )
      text_view = Gtk::TextView.new(text_buffer)
      text_view.set_size_request(1400, 1000)

      scrolled_window = Gtk::ScrolledWindow.new()
      scrolled_window.set_child(text_view)

      win.set_child(scrolled_window)
      win.show
    }

    application.run

The part that confuses me is this:

    /root/.gem/gems/gobject-introspection-4.0.3/lib/gobject-introspection/loader.rb:360:in `initialize': wrong arguments: 
    Gtk::ScrolledWindow#initialize(nil, nil): available signatures: ()

initialize(nil, nil)? Hmmm. And where am I passing it? I think I pass no argument
to it. And then add a child via set_child().

I think this should work, see the python code here:

https://stackoverflow.com/questions/73000992/gtk4-applicationwindow-that-is-also-a-scrolledwindow

I am going through the individual widgets slowly; already covered Gtk::Label and Gtk::Button,
these seem to work fine with ruby-gtk4.

**Comment by rubyFeedback** [comment]
I just tested this:

    require 'gtk4'
    x = Gtk::ScrolledWindow.new

This does not work.

If I change from gtk4 to gtk3 in the above, no error message is displayed.

I believe there is probably something with with the signature. I can not seem
to pass any child widget to a scrolled window widget in ruby-gtk4; in ruby-gtk3
this works fine so perhaps some signature has to be changed (I don't really
understand C code unfortunately so I am not sure how this is done in 
gobject-introspection).

**Comment by kou** [comment]
Thanks. I've fixed this.

**Comment by HuBandiT** [comment]
Greetings,

I am seeing this bug after `gem install gtk4` (which said it installed gtk4-4.0.3).

I'm on a RubyInstaller-based installation under Windows.

Looks like a possible merging or packaging error?

Because the code in `scrolled-window.rb` is still the old code from before https://github.com/ruby-gnome/ruby-gnome/commit/04c8e8d6ce1a09902b3a396d2d80cb858f495f23 :

```
module Gtk
  class ScrolledWindow
    alias_method :initialize_raw, :initialize
    def initialize(hadjustment=nil, vadjustment=nil)
      initialize_raw(hadjustment, vadjustment)
    end
  end
end
```

Thank you in advance.
