### ISSUE TITLE
[Minor / Trivial] Small typo in gtk4/deprecated.rb

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1506]
Hey there kou,

I believe there is a small typo in the following file:

    gtk4/deprecated.rb:632:in `block in <class:Image>': undefined local variable
    or method `iamge' for Gtk::Image:Class

        [{icon_name: iamge}]
                     ^^^^^

I believe "iamge" should be "image". I am making a similar typo every now and
then by the way. ;-)

I think the direct link to this should be here:

https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk4/lib/gtk4/deprecated.rb#L632

(I found this typo "by chance" when I looked at older ruby-gtk3 code for
Stock icons; so many things changed in ruby-gtk4.]

Thanks for reading and your time investment!

**Comment by kou** [comment]
Good catch!
Could you open a pull request for it?

**Comment by kojix2** [comment]
@rubyFeedback 

You can create a pull request with just a few clicks in your browser. It takes less time than creating this issue. You don't even need a terminal. Just clicking a few buttons on the browser screen is enough.

If you feel that your pull request is not up to standard, don't worry. This is because it is not for you to decide if it is up to standard, but for the maintainer to decide. 

I urge you to create a pull request.

**Comment by kojix2** [comment]
## How to make a pull request with your browser

@rubyFeedback 
Maybe you don't know how to create a pull request in your browser.
If so, please see the screenshot below. 

### First, open the file you want to change. Then click the pencil button. This will launch a simple editor. You can also select Visual Studio Code if you prefer.

![image](https://user-images.githubusercontent.com/5798442/191042916-5b4808b8-1c22-4e2f-a326-1839687bbcc3.png)

### ButtonBox is deprecated, so let's change it to Box.

![image](https://user-images.githubusercontent.com/5798442/191044884-fc108f75-4e1b-4dce-808b-3ebf496c9d0a.png)

↓

![image](https://user-images.githubusercontent.com/5798442/191045174-d8893963-6ab1-4b47-ac3b-27f84538f424.png)

### After editing, enter a commit message. And check the check button to create a branch.

![image](https://user-images.githubusercontent.com/5798442/191045614-9073089f-fe29-46bc-9f04-ab463dd8b13c.png)

### Click Propose changes, then Create pull request.

![image](https://user-images.githubusercontent.com/5798442/191046470-98dd2a40-fdc5-4c61-8890-27bfc3dbc5b8.png)

### The further steps are exactly the same as the issue report. Nothing is difficult.

**Comment by kojix2** [comment]
If for some reason you really don't want to use the Github pull request, how about sending a traditional patch file?

Glad if you would be willing to do so.

**Comment by kojix2** [comment]
@rubyFeedback 
I'm still waiting for a pull request or patch. 
Just a few clicks in your browser and a few typos are enough to create a pull request, which takes less than 5 minutes.
(How to do it is written above. (The trick is to start with the pencil button, not the pull request tab.)

If you are unable to do that by any means, would you still be willing to upload a patch file? That way we can add your code to the project. By all means!

I have seen some of your published gems and I am sure you can do it.
