### ISSUE TITLE
[Small deprecation warning in the example grid_packing.rb] Suggestion to change win.add(grid) towards win.set_child(grid)

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1507]
Hey there kou,

I think a small deprecation warning can be found in grid_packing.rb for ruby-gtk4 at the following URL:

https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk4/sample/examples/grid_packing.rb#L36

From:

    grid_packing.rb:36:in `block in <main>': 'Gtk::Window#add' has been deprecated. Use 'Gtk::Window#set_child'.

    win.add(grid)
    # ^^^

I believe to change the line towards:

    win.set_child(grid)
    # ^^^

Should fix/remove that deprecation warning. I hope it's ok to report
such small deprecation warnings and changes to them too.

**Comment by kou** [comment]
Could you open a pull request for this?

**Comment by kojix2** [comment]
I also found this problem. But I would like to wait until @rubyFeedback sends a pull request.

**Comment by kojix2** [comment]
@rubyFeedback 
I have submitted a pull request to fix one `win.add` in hello_world.rb
https://github.com/ruby-gnome/ruby-gnome/pull/1512

There are countless of these things, so if you find one, please make a CONTRIBUTION! :+1:
