### ISSUE TITLE
Where is the doc

### ISSUE THREAD

**Issue by arbims** [ruby-gnome/ruby-gnome#1514]
I search a documentation for ruby gtk4 but i donn't find help please

**Comment by kojix2** [comment]
The documentation automatically generated by https://github.com/ruby-gnome/yard-gobject-introspection is missing.

**Comment by kou** [comment]
I simply added `gtk4` gem to our gem documents: https://ruby-gnome.github.io/ruby-gnome/doc/dev/Gtk.html

But it mixes `gtk3` and `gtk4` gems... We need more work for this...
