### ISSUE TITLE
I can't create liste iterable with ListeStore

### ISSUE THREAD

**Issue by arbims** [ruby-gnome/ruby-gnome#1517]
I can't show my file list inside ListeStore

this is my code

```
  grid = Gtk::Grid.new()
  grid.row_spacing = 20
  grid.column_spacing = 20
  @win.add(grid)
  files = Dir.glob("*.wav")
  listFiles = Gtk::ListStore.new(String)
  iter = listFiles.append()
  files.each_with_index do |value, index|
    iter[index] = value
  end

  treeview = Gtk::TreeView.new(listFiles)
  renderer = Gtk::CellRendererText.new()
  column = Gtk::TreeViewColumn.new("Name Song", renderer)
  treeview.append_column(column)

  scroll_treelist = Gtk::ScrolledWindow.new
  scroll_treelist.set_vexpand(true)
  grid.attach(scroll_treelist, 0,0,0,10)
  scroll_treelist.add(treeview)


```

please any idea

**Comment by galtgendo** [comment]
I'd say: works as designed.

An iter for a ListStore(String) is an array of length == 1.
Move creation of the iter into files loop and only assign to iter[0].

(So, your question is basically "I don't understand GTK API")

**Comment by galtgendo** [comment]
Also, `grid.attach(scroll_treelist, 0,0,0,10)` should likely just be `grid.attach(scroll_treelist, 0,0,1,1)`.
`width == 0` is almost certainly wrong, `height == 10` looks pointless in the given context (might make sense in a broader one, but not in just the snippet).

**Comment by arbims** [comment]
Ok then howa i Can write data inside liste store because data is Always empty

**Comment by galtgendo** [comment]
Off top of my head (so might be not quite correct):

```ruby
  files.each do |value|
    iter = listFiles.append()
    iter[0] = value
  end
```

should work for filling the liststore (well, as long as there's something in files).

Other part would be:

```ruby
  column = Gtk::TreeViewColumn.new("Name Song", renderer, :text => 0)
```
That's actually a mix of GTK API and ruby-gtk. The `0` is the column number in the liststore - yours only has one.

**Comment by kou** [comment]
Can we close this?
