### ISSUE TITLE
gtk4: can't set up a callback for 'editing-started' signal on Gtk.CellRendrer

### ISSUE THREAD

**Issue by galtgendo** [ruby-gnome/ruby-gnome#1518]
In gtk3, following worked (and still does):

```ruby
  renderer = Gtk::CellRendererText.new
  renderer.editable = true
  renderer.signal_connect('editing-started') do |cell, editable, path|
    next if not editable.is_a? Gtk::Entry
    editable.editable = false
  end
```
(yes, that `next if` line is a bit silly, but I'm pants at ruby, so didn't have anything more natural when `return` turned out to break things)

In gtk4, upon double-clicking (it's for a TreeViewColumn after all), the result is a crash with an odd message: `no implicit conversion of String into Array`. Now, the thing is, it's not the content of the callback that's the problem, it's adding the callback by itself - commenting these two lines still gives the same crash. It's odd, cause there doesn't seem to be anything on ruby-gtk side that would be doing anything in that direction, yet gtk3 from the same tarball works, so it doesn't seem to be a glib problem.

**Comment by kou** [comment]
Could you provide a runnable script (that includes the snippet) for gtk3 gem and a runnable script (but doesn't work well) for gtk4 gem?

**Comment by galtgendo** [comment]
...surprisingly, I've got a problem with producing a minimal example.

The problem is easily reproducible in a toy of mine (about 3000 lines), but I can't (yet) extract a smaller part of it.

The struct of the toy isn't that complicated: Window:Box:[Stack:Switcher].
The elements on the Stack are either deeper Stack:Switcher pairs or ScrolledWindows with Treeviews.

Any hints on how to capture where that error is coming from ?

**Comment by kou** [comment]
> Any hints on how to capture where that error is coming from ?

It's difficult without a runnable script...

**Comment by galtgendo** [comment]
...on unrelated note, in gtksourceview5/sample/test.rb, the line should likely go 'require 'gtksourceview5''.

As for the issue, I could send you the toy, I'd just prefer not to attach it here. For reasons...
Dumb reasons, but still reasons.

**Comment by kou** [comment]
> ...on unrelated note, in gtksourceview5/sample/test.rb, the line should likely go 'require 'gtksourceview5''.

Good catch! Could you open a pull request for it?

**Comment by galtgendo** [comment]
...you know, this is beginning to look like a memory management problem.
While it's run normally, the error is most of the times as stated above, but every now and then it's different.

However, if run through irb, it's all over the place:
```
no implicit conversion of Ripper::Lexer::State into Array
```

```
undefined method `call' for END|LABEL:Ripper::Lexer::State
```

```
undefined method `call' for "xterm-256color":String
```

```
undefined method `call' for "\n":String
```

```
undefined method `call' for "==":String
```

as some of random examples, all from the same action - double clicking the same column. So it's likely something about this callback being garbage collected before its time...

**Comment by galtgendo** [comment]
It might explain why coming up with a self-contained example is so difficult - the models are quite heavy with data, so timing might play a role.

**Comment by galtgendo** [comment]
I've got some basic understanding of glib/gobject on C side, but next to none when it comes to ruby C side.

Assuming this is something like #1496 or commit ff40f62a1095fe4e0d58976d0fcf19355a65f279, where should I dig ?

**Comment by kou** [comment]
If this is a GC related problem, adding `GLib::Timeout.add(1000) {GC.start; GLib::Source::CONTINUE}` to a self-contained example may help you. It finalizes most objects even when we don't have many objects.

**Comment by galtgendo** [comment]
...wow...

It may take awhile to trim it down, but with that line added, it crashes not even with a simple ruby traceback, but with full '[BUG] Segmentation fault at 0x0000000000000000' ruby backtrace.

**Comment by galtgendo** [comment]
[test-crash.rb](https://github.com/ruby-gnome/ruby-gnome/files/9845936/test-crash.rb.txt)

So, still a bit of cruft left, but this crashes just fine for me.
(note a minor thing: likely independent of this bug, when the treeview/liststore has only one column, it behaves somewhat derangedly with double clicks - not sure if that's ruby-gtk or just plain gtk)

**Comment by galtgendo** [comment]
Also, more of  a support question / general ruby query, but was there a more natural ruby construct for an early return from that callback than 'next if...' ?

**Comment by galtgendo** [comment]
...googling for hints led me to [this](https://gitlab.gnome.org/GNOME/pygobject/-/issues/535): the comments are slightly disturbing, given that pygobject is among GNOME hosted projects, so technically should have rather easy access to gobject-introspection people...

**Comment by kou** [comment]
Thanks.
I've fixed this.

`next if` works but I like `lambda` and `return`:

```ruby
  callback = lambda do |cell, editable, path|
    return if not editable.is_a? Gtk::Entry
    editable.editable = false
  end
  renderer.signal_connect('editing-started', &callback)
```

**Comment by galtgendo** [comment]
Thanks. The fix seems to work for me too.

As for the 'behaves somewhat derangedly' remark: at smaller font sizes (as it doesn't seem to happen at `font-size: 11pt`, though likely there's another factor involved), when double clicking a cell, sometimes instead of the cell being activated,  the treeview is somewhat randomly scrolled. ...number of columns isn't actually a factor there, happens with two columns too...

PS: that `gtk_css_node_insert_after: assertion 'previous_sibling == NULL || previous_sibling->parent == parent'` assertion seems to be a gtk4 bug - it happens with python too.

**Comment by galtgendo** [comment]
Oh, and on why I feel `next if` is awkward: a callback just doesn't feel like a loop. Then again, having rechecked it, both `next` and `break` in ruby can return a value...
