### ISSUE TITLE
Removal of GValueArray may have been somewhat premature

### ISSUE THREAD

**Issue by mpalmer** [ruby-gnome/ruby-gnome#1520]
While GValueArray may be deprecated in GLib2, it is far from being completely unused, even in core-adjacent projects.  Specifically, I've got a Ruby script that uses the [gstreamer `level` plugin](https://gstreamer.freedesktop.org/documentation/level/index.html), which emits messages containing GValueArrays.  If I pin the `glib2` and `gstreamer` gems to versions that pre-date bac054f, then the script works fine.  Newer versions of those gems fail to recognise the value coming out of the message as being an array, and all hack breaks loose.

If it isn't a huge maintenance burden, can the GValueArray support be re-added to the `glib2` gem until such time as it's actually *removed* from GLib2, rather than merely being deprecated?  It'd make life a lot easier for those of us stuck consuming GValueArrays we don't control.

**Comment by kou** [comment]
OK. I've re-added `GValueArray` support.

**Comment by mpalmer** [comment]
Thank you!
