### ISSUE TITLE
[Compile/Install problem with ruby-gtk2 and ruby 3.2.0] Can not compile the gtk2 gem version 3.4.3

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1532]
On ruby 3.2.0 I can not compile/install gtk2 gem anymore:

    Fetching gtk2-3.4.3.gem
    Fetching glib2-3.4.3.gem
    Building native extensions. This could take a while...
    ERROR:  Error installing gtk2:
            ERROR: Failed to build gem native extension.

        current directory: /root/.gem/gems/glib2-3.4.3/ext/glib2
    /home/Programs/Ruby/3.2.0/bin/ruby -I /home/Programs/Ruby/3.2.0/lib/ruby/3.2.0 extconf.rb
    checking for --enable-debug-build option... no
    checking for -Wall option to compiler... yes
    checking for -Waggregate-return option to compiler... yes
    checking for -Wcast-align option to compiler... yes
    checking for -Wextra option to compiler... no
    checking for -Wformat=2 option to compiler... yes
    checking for -Winit-self option to compiler... yes
    checking for -Wlarger-than-65500 option to compiler... yes
    checking for -Wmissing-declarations option to compiler... yes
    checking for -Wmissing-format-attribute option to compiler... yes
    checking for -Wmissing-include-dirs option to compiler... yes
    checking for -Wmissing-noreturn option to compiler... yes
    checking for -Wmissing-prototypes option to compiler... yes
    checking for -Wnested-externs option to compiler... yes
    checking for -Wold-style-definition option to compiler... yes
    checking for -Wpacked option to compiler... yes
    checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
    checking for -Wpointer-arith option to compiler... yes
    checking for -Wundef option to compiler... yes
    checking for -Wout-of-line-declaration option to compiler... no
    checking for -Wunsafe-loop-optimizations option to compiler... yes
    checking for -Wwrite-strings option to compiler... yes
    checking for Homebrew... no
    checking for gobject-2.0 version (>= 2.12.0)... yes (2.74.4)
    checking for gthread-2.0... yes (2.74.4)
    checking for unistd.h... yes
    checking for io.h... no
    checking for g_spawn_close_pid() in glib.h... yes
    checking for g_thread_init() in glib.h... yes
    checking for g_main_depth() in glib.h... yes
    checking for g_listenv() in glib.h... yes
    checking for rb_check_array_type() in ruby.h... yes
    checking for rb_check_hash_type() in ruby.h... yes
    checking for rb_exec_recursive() in ruby.h... yes
    checking for rb_errinfo() in ruby.h... yes
    checking for rb_thread_call_without_gvl() in ruby.h... yes
    checking for ruby_native_thread_p() in ruby.h... yes
    checking for rb_thread_call_with_gvl() in ruby.h... yes
    checking for rb_gc_register_mark_object() in ruby.h... yes
    checking for rb_exc_new_str() in ruby.h... yes
    checking for rb_enc_str_new_static() in ruby.h... yes
    checking for curr_thread in ruby.h,node.h... no
    checking for rb_curr_thread in ruby.h,node.h... no
    creating ruby-glib2.pc
    creating glib-enum-types.c
    creating glib-enum-types.h
    creating Makefile
    
    current directory: /root/.gem/gems/glib2-3.4.3/ext/glib2
    make DESTDIR\= sitearchdir\=./.gem.20221229-874339-7qeva1 sitelibdir\=./.gem.20221229-874339-7qeva1 clean
    
    current directory: /root/.gem/gems/glib2-3.4.3/ext/glib2
    make DESTDIR\= sitearchdir\=./.gem.20221229-874339-7qeva1 sitelibdir\=./.gem.20221229-874339-7qeva1
    compiling glib-enum-types.c
    compiling rbglib-bytes.c
    compiling rbglib-gc.c
    In file included from /home/Programs/Ruby/3.2.0/include/ruby-3.2.0/ruby/internal/core.h:34,
                     from /home/Programs/Ruby/3.2.0/include/ruby-3.2.0/ruby/ruby.h:29,
                     from /home/Programs/Ruby/3.2.0/include/ruby-3.2.0/ruby.h:38,
                     from rbgobject.h:26,
                     from rbgprivate.h:31,
                     from rbglib-gc.c:21:
    rbglib-gc.c: In function ‘rbg_gc_marker_new_raw’:
    rbglib-gc.c:87:39: error: ‘rb_cData’ undeclared (first use in this function)
       87 |     gc_marker = TypedData_Wrap_Struct(rb_cData,
          |                                       ^~~~~~~~
    /home/Programs/Ruby/3.2.0/include/ruby-3.2.0/ruby/internal/core/rtypeddata.h:442:30: note: in definition of macro ‘TypedData_Wrap_Struct’
      442 |   rb_data_typed_object_wrap((klass),(sval),(data_type))
          |                              ^~~~~
    rbglib-gc.c:87:39: note: each undeclared identifier is reported only once for each function it appears in
       87 |     gc_marker = TypedData_Wrap_Struct(rb_cData,
          |                                       ^~~~~~~~
    /home/Programs/Ruby/3.2.0/include/ruby-3.2.0/ruby/internal/core/rtypeddata.h:442:30: note: in definition of macro ‘TypedData_Wrap_Struct’
      442 |   rb_data_typed_object_wrap((klass),(sval),(data_type))
          |                              ^~~~~
    make: *** [Makefile:248: rbglib-gc.o] Error 1
    
    make failed, exit code 2
    
    Gem files will remain installed in /root/.gem/gems/glib2-3.4.3 for inspection.
    Results logged to /root/.gem/extensions/x86_64-linux/3.2.0-static/glib2-3.4.3/gem_make.out

It worked fine on the previous ruby version, so I assume something changed API-wise. Unfortunately
I do not really know C so I don't know how to fix this.

**Comment by kou** [comment]
gtk2 gem isn't maintained now.
