### ISSUE TITLE
cannot install gobject-introspection on ruby 3.2

### ISSUE THREAD

**Issue by dsisnero** [ruby-gnome/ruby-gnome#1533]
[gem_make.out](https://gist.github.com/dsisnero/98d9703ea82e77d929bc462fc6ba00be) 

[gem env](https://gist.github.com/dsisnero/da376a5d76777b211cfabae172138bd4)

**Comment by kou** [comment]
Could you show the output from `dir f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/gems/glib2-4.0.5/ext/glib2/`?

**Comment by dsisnero** [comment]
F:\windows\scoop\apps\alacritty\current>dir f:\windows\tools\ruby\Ruby3.2\lib\ruby\gems\3.2.0\gems\glib2-4.0.5\ext\glib2\
 Volume in drive F is f
 Volume Serial Number is 4CCE-F67D

 Directory of f:\windows\tools\ruby\Ruby3.2\lib\ruby\gems\3.2.0\gems\glib2-4.0.5\ext\glib2

01/03/2023  11:17 AM    <DIR>          .
01/03/2023  11:17 AM    <DIR>          ..
01/03/2023  11:09 AM               715 depend
01/03/2023  11:09 AM             3,520 extconf.rb
01/03/2023  11:12 AM            49,662 glib-enum-types.c
01/03/2023  11:12 AM             7,272 glib-enum-types.h
01/03/2023  11:09 AM             4,618 glib2.def
01/03/2023  11:12 AM            13,868 Makefile
01/03/2023  11:09 AM               936 rbgcompat.h
01/03/2023  11:09 AM             3,248 rbglib-bytes.c
01/03/2023  11:09 AM             5,224 rbglib-gc.c
01/03/2023  11:09 AM             8,153 rbglib-variant-type.c
01/03/2023  11:09 AM            12,843 rbglib-variant.c
01/03/2023  11:09 AM            31,201 rbglib.c
01/03/2023  11:09 AM             9,983 rbglib.h
01/03/2023  11:09 AM             4,157 rbglib2conversions.h
01/03/2023  11:09 AM             1,648 rbglibdeprecated.c
01/03/2023  11:09 AM             1,085 rbglib_io_constants.c
01/03/2023  11:09 AM            22,571 rbglib_keyfile.c
01/03/2023  11:09 AM            14,260 rbglib_maincontext.c
01/03/2023  11:09 AM             3,294 rbglib_mainloop.c
01/03/2023  11:09 AM             4,682 rbglib_matchinfo.c
01/03/2023  11:09 AM             5,447 rbglib_messages.c
01/03/2023  11:09 AM             2,203 rbglib_pollfd.c
01/03/2023  11:09 AM            14,468 rbglib_regex.c
01/03/2023  11:09 AM             1,850 rbglib_shell.c
01/03/2023  11:09 AM             1,390 rbglib_shellerror.c
01/03/2023  11:09 AM             5,195 rbglib_source.c
01/03/2023  11:09 AM             8,474 rbglib_spawn.c
01/03/2023  11:09 AM             2,830 rbglib_spawnerror.c
01/03/2023  11:09 AM             1,331 rbglib_threads.c
01/03/2023  11:09 AM             2,923 rbglib_timer.c
01/03/2023  11:09 AM             2,333 rbglib_timezone.c
01/03/2023  11:09 AM             2,223 rbglib_ucs4.c
01/03/2023  11:09 AM             7,591 rbglib_unichar.c
01/03/2023  11:09 AM             2,435 rbglib_unicode.c
01/03/2023  11:09 AM             2,219 rbglib_utf16.c
01/03/2023  11:09 AM             6,592 rbglib_utf8.c
01/03/2023  11:09 AM             8,823 rbglib_utils.c
01/03/2023  11:09 AM             3,258 rbglib_win32.c
01/03/2023  11:09 AM            11,762 rbgobject.c
01/03/2023  11:09 AM            13,933 rbgobject.h
01/03/2023  11:09 AM             1,470 rbgobj_binding.c
01/03/2023  11:09 AM             7,720 rbgobj_boxed.c
01/03/2023  11:09 AM            10,395 rbgobj_closure.c
01/03/2023  11:09 AM             4,833 rbgobj_convert.c
01/03/2023  11:09 AM             2,906 rbgobj_enumflags.c
01/03/2023  11:09 AM            11,573 rbgobj_enums.c
01/03/2023  11:09 AM            15,049 rbgobj_flags.c
01/03/2023  11:09 AM            33,112 rbgobj_object.c
01/03/2023  11:09 AM            12,405 rbgobj_param.c
01/03/2023  11:09 AM            13,110 rbgobj_paramspecs.c
01/03/2023  11:09 AM            33,813 rbgobj_signal.c
01/03/2023  11:09 AM             1,391 rbgobj_strv.c
01/03/2023  11:09 AM            30,781 rbgobj_type.c
01/03/2023  11:09 AM             3,775 rbgobj_typeinstance.c
01/03/2023  11:09 AM             5,970 rbgobj_typeinterface.c
01/03/2023  11:09 AM             2,263 rbgobj_typemodule.c
01/03/2023  11:09 AM             1,871 rbgobj_typeplugin.c
01/03/2023  11:09 AM            12,445 rbgobj_value.c
01/03/2023  11:09 AM             2,878 rbgobj_valuearray.c
01/03/2023  11:09 AM             5,709 rbgobj_valuetypes.c
01/03/2023  11:09 AM             7,962 rbgprivate.h
01/03/2023  11:09 AM             6,162 rbgutil.c
01/03/2023  11:09 AM             5,556 rbgutil.h
01/03/2023  11:09 AM             5,738 rbgutildeprecated.c
01/03/2023  11:09 AM             2,868 rbgutildeprecated.h
01/03/2023  11:09 AM             7,975 rbgutil_callback.c
01/03/2023  11:09 AM             6,844 rbgutil_list.c
01/03/2023  11:09 AM             4,336 rbgutil_list.h
01/03/2023  11:12 AM               112 ruby-glib2.pc
              81 File(s)        646,340 bytes
               2 Dir(s)  3,177,317,842,944 bytes free

F:\windows\scoop\apps\alacritty\current>

**Comment by dsisnero** [comment]
it worked.  thanks
