### ISSUE TITLE
glib2 cannot compile on ruby 3.2.2

### ISSUE THREAD

**Issue by Akkiesoft** [ruby-gnome/ruby-gnome#1563]
I tried to install glib2 from the bundle command, but it failed with an error like the attached log file.

(It seems similar to #361 ?)

[gem_make.out.txt](https://github.com/ruby-gnome/ruby-gnome/files/11415351/gem_make.out.txt)
[mkmf.log](https://github.com/ruby-gnome/ruby-gnome/files/11415352/mkmf.log)

My environment.
Ruby 3.2.2 (installed by rbenv and ruby-build)
glib2 2.74.7 (installed by MacPorts)
M1 Mac / macOS Ventura 13.3.1

**Comment by kou** [comment]
Yes. This is similar to #361. An unrelated header file (`gmodule.h`) is processed.

Could you also share the followings?

* `glib-enum-types.c` in a build directory. (You can find it in `/Users/akkie/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/glib2-4.1.4/ext/glib2`.)
* An output of `pkg-config --cflags glib-2.0`.
* An output of `find /opt/local/include/glib-2.0`.

**Comment by Akkiesoft** [comment]
> * `glib-enum-types.c` in a build directory. (You can find it in `/Users/akkie/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/glib2-4.1.4/ext/glib2`.)

[glib-enum-types.c.txt](https://github.com/ruby-gnome/ruby-gnome/files/11417240/glib-enum-types.c.txt)

> * An output of `pkg-config --cflags glib-2.0`.

```
% pkg-config --cflags glib-2.0
-I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include
```

> * An output of `find /opt/local/include/glib-2.0`.

[find-glib-2.0.txt](https://github.com/ruby-gnome/ruby-gnome/files/11417241/find-glib-2.0.txt)

**Comment by kou** [comment]
Thanks.
`-I/opt/local/include` is unexpected.

Could you also show `/opt/local/lib/pkgconfig/glib-2.0.pc`?

**Comment by Akkiesoft** [comment]
Thank you for taking the time to reply :)

> Could you also show /opt/local/lib/pkgconfig/glib-2.0.pc?

```
prefix=/opt/local
includedir=${prefix}/include
libdir=${prefix}/lib

bindir=${prefix}/bin
glib_genmarshal=${bindir}/glib-genmarshal
gobject_query=${bindir}/gobject-query
glib_mkenums=${bindir}/glib-mkenums

Name: GLib
Description: C Utility Library
Version: 2.74.7
Requires.private: libpcre2-8 >=  10.32
Libs: -L${libdir} -lglib-2.0 -lintl
Libs.private: -liconv -framework Foundation -framework CoreFoundation -framework AppKit -framework Carbon
Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include
```

**Comment by kou** [comment]
Could you try master?

https://github.com/ruby-gnome/ruby-gnome#install-from-github-master-branch

**Comment by Akkiesoft** [comment]
I tried the master branch and it compiled successfully!

Thank you very much!

**Comment by kou** [comment]
Thanks for confirming this.
I'll release a new version in a few days.

**Comment by kou** [comment]
Done.
