### ISSUE TITLE
Simple gtk4 example for key press event?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1571]
The following example works in python:

    #!/usr/bin/python

    import gi
    from gi.repository import Gtk
    gi.require_version("Gtk", "4.0")

    class AppWindow(Gtk.ApplicationWindow):

        def __init__(self, app):

            super(AppWindow, self).__init__(application=app)

            self.init_ui()

        def init_ui(self):

            self.set_title('Key press')
        
            keycont = Gtk.EventControllerKey()
            keycont.connect('key-pressed', self.on_key_pressed)
            self.add_controller(keycont)

            self.set_default_size(350, 250)

        # keyval, keycode, state, user_data
        def on_key_pressed(self, keyval, keycode, *_):

            if keycode == ord('q'):
                self.close()

    def on_activate(app):
        win = AppWindow(app)
        win.present()

    app = Gtk.Application(application_id='com.zetcode.KeyPress')
    app.connect('activate', on_activate)
    app.run(None)

I tried to rewrite this into ruby:

    #!/usr/bin/ruby -w
    # Encoding: UTF-8
    # frozen_string_literal: true
    # =========================================================================== #
    require 'gtk4'

    module Gtk

    class QuitOnKeypressEvent < ::Gtk::Box # === Gtk::QuitOnKeypressEvent

      # ========================================================================= #
      # === initialize
      # ========================================================================= #
      def initialize(
          run_already = true
        )
        super(:horizontal)
        reset
        run if run_already
      end

      # ========================================================================= #
      # === title?
      # ========================================================================= #
      def title?
        'Changed Events Example'
      end; alias title title? # === title

      # ========================================================================= #
      # === reset                                                     (reset tag)
      # ========================================================================= #
      def reset
      end

      # ========================================================================= #
      # === run
      # ========================================================================= #
      def run
        keycont = Gtk::EventControllerKey.new
        keycont.signal_connect(:key_pressed) {|widget, event|
          e 'WE WERE PRESSED!'
          pp event
        }
        add_controller(keycont)
        set_halign(:center)
      end

    end; end

    if __FILE__ == $PROGRAM_NAME
      alias e puts
      application = Gtk::Application.new('org.gtk.changed_events_example', :flags_none)
      application.signal_connect(:activate) { |app|
        win = Gtk::ApplicationWindow.new(app)
        win.title = 'Showcasing Events' 
        win.set_default_size(600, 200)
        win.set_child(Gtk::QuitOnKeypressEvent.new)
        win.signal_connect(:close_request) {
          e 'Exiting now.'
        }
        win.show
      }
      application.run
    end

This does not work though.

The problem I have is with this code:

        keycont = Gtk::EventControllerKey.new
        keycont.signal_connect(:key_pressed) {|widget, event|
          e 'WE WERE PRESSED!'
          pp event
        }
        add_controller(keycont)

I am not sure why the python code works but the ruby code does not work. Most likely
I made a mistake.

The changed event system in gtk4 confuses me. I can not seem to get it to work in
ruby. I intend to read up on it more, but if anyone else is able to get events to work,
that would be super-helpful. The changed events are the single biggest reason for
me to not yet use gtk4 more regularly, and with the release of  gtk 4.12.0 I wanted
to see what improved in gtk (e. g. a few bugs or buggy behaviour I got in gtk 3).

Would it be possible to add a simple event-example to the gtk4 examples, as a
standalone .rb file? I checked through application1/ application2/ and so forth
but they seem to be for a slightly more complicated example, and there are no
special click/events that I can see, so it seems more of an introduction to gtk4.

At any rate thank you for reading this and feel free to close it at any moment in
time.

**Comment by kou** [comment]
You need to add `Gtk::EventControllerKey` to `Gtk::ApplicationWindow` not `Gtk::Box`:

```ruby
#!/usr/bin/env ruby -w
# Encoding: UTF-8
# frozen_string_literal: true
# =========================================================================== #
require 'gtk4'

module Gtk

class QuitOnKeypressEvent < ::Gtk::Box # === Gtk::QuitOnKeypressEvent

  # ========================================================================= #
  # === initialize
  # ========================================================================= #
  def initialize(
      window,
      run_already = true
    )
    super(:horizontal)
    reset
    run(window) if run_already
  end

  # ========================================================================= #
  # === title?
  # ========================================================================= #
  def title?
    'Changed Events Example'
  end; alias title title? # === title

  # ========================================================================= #
  # === reset                                                     (reset tag)
  # ========================================================================= #
  def reset
  end

  # ========================================================================= #
  # === run
  # ========================================================================= #
  def run(window)
    keycont = Gtk::EventControllerKey.new
    keycont.signal_connect(:key_pressed) {|widget, event|
      e 'WE WERE PRESSED!'
      pp event
    }
    window.add_controller(keycont)
    set_halign(:center)
  end

end; end

if __FILE__ == $PROGRAM_NAME
  alias e puts
  application = Gtk::Application.new('org.gtk.changed_events_example', :flags_none)
  application.signal_connect(:activate) { |app|
    win = Gtk::ApplicationWindow.new(app)
    win.title = 'Showcasing Events' 
    win.set_default_size(600, 200)
    win.set_child(Gtk::QuitOnKeypressEvent.new(win))
    win.signal_connect(:close_request) {
      e 'Exiting now.'
    }
    win.show
  }
  application.run
end
```

**Comment by SamiSieranoja** [comment]
I was struggling with the same thing also, and had to additionally set PropagationPhase::CAPTURE for the controller to get same behaviour as in gtk3.
```
keycont.set_propagation_phase(Gtk::PropagationPhase::CAPTURE)
```

**Comment by kou** [comment]
It must be resolved.
