### ISSUE TITLE
Reading clipboard

### ISSUE THREAD

**Issue by SamiSieranoja** [ruby-gnome/ruby-gnome#1576]
Trying to figure out how to read clipboard in Gtk4. (Migrating my project from gtk3=>gtk4 github.com/samiSieranoja/vimamsa ). I got this far, but not sure what to give as parameter to read_text_finish:
```
window  = Gtk::Window.new()
window.display.clipboard.read_text_finish(parameter)
```
Thanks a lot for any help with this.

**Comment by kou** [comment]
You need to call `Gdk::Clipboard#read_text_async` before calling `Gdk::Clipboard#read_text_finish`:

```ruby
require "gtk4"

application = Gtk::Application.new("org.gtk.example")
application.signal_connect(:activate) do
  window = Gtk::ApplicationWindow.new(application)
  window.present
  clipboard = window.display.clipboard
  clipboard.read_text_async do |_clipboard, result|
    pp clipboard.read_text_finish(result)
  end
end
application.run
```

**Comment by SamiSieranoja** [comment]
Works great! Thank you!
