### ISSUE TITLE
Menu example

### ISSUE THREAD

**Issue by SamiSieranoja** [ruby-gnome/ruby-gnome#1581]
Trying to figure out how the menus works, I recreated this example in ruby:
https://toshiocp.github.io/Gtk4-tutorial/sec17.html

I hope the code is useful for somebody. Maybe you can add it to sample/examples/ ?

```
require "gtk4"

app = Gtk::Application.new("org.gtk.example", :flags_none)

app.signal_connect "activate" do
  window = Gtk::ApplicationWindow.new(app)
  window.set_application(app)

  act_quit = Gio::SimpleAction.new("quit")
  app.add_action(act_quit)
  act_quit.signal_connect "activate" do |_simple_action, _parameter|
    window.destroy
    exit!
  end

  menubar = Gio::Menu.new()
  menu_item_menu = Gio::MenuItem.new("Menu", nil)
  menu = Gio::Menu.new()
  menu_item_quit = Gio::MenuItem.new("Quit", "app.quit")
  menu.append_item(menu_item_quit)
  menu_item_menu.set_submenu(menu)
  menubar.append_item(menu_item_menu)
  app.menubar = menubar
  window.set_show_menubar true

  window.show
end

app.run

```

I also tried to do (instead of app.add_action) like with g_action_map_add_action in the c code:
`Gio::ActionMap.add_action(action)`
.. but it doesn't work. add_action is listed in instance methods, but no way to create the instance. Is there some use for this class if no way to access the instance?

There is somewhat similar menu example in sample/examples/action-namespace.rb,  but I wanted to create the menu structure dynamically (in case runtime changes needed) and not use static xml like in that example.

**Comment by kou** [comment]
Could you open a pull request to add this example?

`Gio::ActionMap` is a `Module`. So it's not instantiatable. We can use methods in `Gio::ActionMap` with classes that `include` `Gio::ActionMap` like `Gtk::Application` (`Gio::Application`).

**Comment by rubyFeedback** [comment]
Hey there SamiSieranoja,

What licence would you use for the file? I'd like to also include
an adjusted example for my gtk-related gem (separate of the
bindings maintained by kou here).

**Comment by kou** [comment]
@rubyFeedback Good catch!

@SamiSieranoja Could you change the license header of https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk4/sample/examples/menubar.rb to GPLv3+?
See also: https://toshiocp.github.io/Gtk4-tutorial/sec1.html
