### ISSUE TITLE
Creating a button with icon in GTK4

### ISSUE THREAD

**Issue by SamiSieranoja** [ruby-gnome/ruby-gnome#1587]
I'm trying to replicate this in Gtk4:
`button = gtk_button_new_from_icon_name ("go-next-symbolic");`
(From https://github.com/GNOME/gtk/blob/main/demos/gtk-demo/headerbar.c )

Based on the deprecation notice:
`Gtk::Button#initialize(label_or_stock_id, use_underline = nil)' style has been deprecated. Use 'Gtk::Button#initialize(:label => nil, :use_underline => nil, :stock_id => nil)' style.`

I would expect it to work like this:
`Gtk::Button.new(:stock_id => "go-next-symbolic")`
or
`Gtk::Button.new(stock_id: "go-next-symbolic")`

But the Button just shows blank without any icon. Using :label works fine. I didn't get any other icon to work either.

**Comment by kou** [comment]
Could you share your working version?
(PR is OK.)

**Comment by SamiSieranoja** [comment]
Here's my code:
https://gist.github.com/SamiSieranoja/016bf440d017c559f9454133e611bedf

I'm trying to create a simple audio player using GTK4 and Gstreamer.  Potentially, this could serve also as example to either of those packages (not sure which one).  It kind of works, though still needs some improvement. One of the issues is that I can't get the Button with an icon to work.  

See line 214:
`# play_button = Gtk::Button.new(:stock_id => "media-playback-start-symbolic")`


A side note, I tried also using  Gtk::MediaControls and Gtk::MediaFile (which also use Gstreamer backend) before testing with Gstreamer, and that somehow jammed the pulseaudio server. So, that's the main reason I'm not using Gtk::MediaControls widget here.

**Comment by kou** [comment]
Could you try `Gtk::Button.new(icon_name: "media-playback-start-symbolic")` instead?

**Comment by SamiSieranoja** [comment]
That works. Thanks!
