### ISSUE TITLE
GLib::Instantiatable.signals causes segfault

### ISSUE THREAD

**Issue by SamiSieranoja** [ruby-gnome/ruby-gnome#1589]
Running this code causes a segfault:
```
require "gtk4"
GLib::Instantiatable.signals
```
The error: 
GLib-GObject-CRITICAL **: g_signal_list_ids: assertion 'G_TYPE_IS_INSTANTIATABLE (itype) || G_TYPE_IS_INTERFACE (itype)' failed

I came across this while trying to generate documentation for everything under GLib

edit: And same issue with GLib::Variant

**Comment by kou** [comment]
Thanks for your report. I've fixed it.
