### ISSUE TITLE
Drag&Drop in Gtk4

### ISSUE THREAD

**Issue by SamiSieranoja** [ruby-gnome/ruby-gnome#1594]
I'm trying to implement handling of drag & drop of files (from external application) in GTK4.

Following how it's done in gtktextview.c:
https://github.com/gnome/gtk/blob/main/gtk/gtktextview.c#L1936

I wonder if I'm doing this correct:
dest = gtk_drop_target_new (G_TYPE_STRING, GDK_ACTION_COPY | GDK_ACTION_MOVE);
=>
dt = Gtk::DropTarget.new(GLib::Type["GString"], [Gdk::DragAction::COPY, Gdk::DragAction::MOVE])

When I add "enter" signal handler to the DropTarget, it's not called in any situation. If I do the same using Gtk::DropControllerMotion, it works fine, but that class can't be used to catch the drop event. The default controllers can handle the drag&drop.

My full code is here:
```ruby:
#!/usr/bin/env ruby
require "gtk4"

app = Gtk::Application.new("org.gtk.example", :flags_none)

app.signal_connect "activate" do
  window = Gtk::ApplicationWindow.new(app)
  window.application = app

  # tw = GtkSource::View.new
  tw = Gtk::TextView.new
  str = (("FOOBAR " * 10) + "\n") * 1000
  tw.buffer.set_text(str)
  sw = Gtk::ScrolledWindow.new()
  sw.set_child(tw)
  window.set_child(sw)
  window.set_size_request(500, 500)

  clist = tw.observe_controllers
  $to_remove = []
  (0..(clist.n_items - 1)).each { |x|
    ctr = clist.get_item(x)
    if ctr.class == Gtk::DropControllerMotion or ctr.class == Gtk::DropTarget
      $to_remove << ctr
    end
    pp ctr
  }
  $to_remove.each { |x|
    puts "Remove controller: #{x}"
    tw.remove_controller(x)
  }

  dc = Gtk::DropControllerMotion.new
  tw.add_controller(dc)
  dc.signal_connect "enter" do |o, x, y|
    p "dc,enter", 2
    p [x, y]
  end

  dc.signal_connect "motion" do |o, x, y|
    p "dc,move", 2
    p [x, y]
  end

  dt = Gtk::DropTarget.new(GLib::Type["GString"], [Gdk::DragAction::COPY, Gdk::DragAction::MOVE])
  tw.add_controller(dt)
  dt.signal_connect "drop" do |gesture, x, y|
    p "dt, drop"
  end

  dt.signal_connect "enter" do |gesture, x, y|
    p "dt, enter"
  end

  dt.signal_connect "motion" do |gesture, x, y|
    p "dt, move"
  end

  window.show
end

app.run

```

**Comment by kou** [comment]
`GLib::Type["GString"]` isn't `G_TYPE_STRING`.
You need to use `GLib::Type::STRING` for `G_TYPE_STRING`.

**Comment by kou** [comment]
It makes sense.
Implemented.
