### ISSUE TITLE
Object ownership when working with GTK - TL;DR;: keep a reference to everything on the Ruby side (beginner's question)

### ISSUE THREAD

**Issue by HuBandiT** [ruby-gnome/ruby-gnome#1601]
It would be difficult for me to create a simplified testcase for this – so is this maybe enough to suggest where to look?

---

I have a Gtk::Notebook, I create a few fixed tabs during program startup. These work without a crash initially.

However, if I create new tabs during the running of the program (as a response to user clicks), and then the user starts to switch between tabs, the program often crashes upon a tab click with the message below, even if the user clicked on a tab that worked initially:

```
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:705:in `invoke': undefined method `call' for [39824, 6]:Array
         from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:705:in `invoke'
         from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:573:in `run'
         from multifir.rb:921:in `<main>'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/glib2-4.2.0/lib/glib2.rb:46:in `exit': exit
         from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/glib2-4.2.0/lib/glib2.rb:46:in `exit_application'
         from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:705:in `invoke'
         from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:705:in `invoke'
         from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:573:in `run'
         from multifir.rb:921:in `<main>'
```

It is always an undefined method 'call' for an `Array` with two numbers, the first around 30-40 thousand, the second below 100, often below 20.

Thank you in advance.

**Comment by kou** [comment]
It seems that this is a GC related problem.
`GC.disable` is a workaround but it'll use many memory.
We can't fix a real problem without reproducible code... Can you provide a non-simplified program that  reproduces this problem?

**Comment by HuBandiT** [comment]
Thank you again for your time and help. Hmm... providing a program will not be a small task... but maybe let me ask you this first:

I have pure Ruby `MyOwnWidget < Gtk::Box` (that is, it does not `type_register` or anything – it just has pure Ruby coded behaviour) of which I to put many in a standard `Gtk::Box` _without_ keeping Ruby references to them. (Because I thought the `Gtk::Box` itself will manage their lifecycle.)

Is this maybe the problem?

If yes, is there way to enable `MyOwnWidget` to be used like this?

**Comment by HuBandiT** [comment]
My apologies: I misunderstood ownership in GTK. I neglected to read  this sentence for e.g. [Gtk::Box#append](https://docs.gtk.org/gtk4/method.Box.append.html):

> The data is owned by the caller of the method.

Which means I as application developer still have to keep/store a reference to everything I create and give to GTK.

I have now mostly refactored my program to do so, and the crashes are mostly gone.

My apologies.
