### ISSUE TITLE
Compiling with custom gtk4 library

### ISSUE THREAD

**Issue by SamiSieranoja** [ruby-gnome/ruby-gnome#1608]
I have compiled gtk4 from sources and installed under /opt/gtk.  Is there a way to compile and run the ruby gtk4 gem using this alternative path instead of the system default? (running Ubuntu 22.04). e.g. /usr/lib/x86_64-linux-gnu/libgtk-4.so.1 => /opt/gtk/lib/x86_64-linux-gnu/libgtk-4.so.1

**Comment by kou** [comment]
`PKG_CONFIG_PATH=/opt/gtk/lib/pkgconfig gem install gtk4`

**Comment by kou** [comment]
You may need `LD_LIBRARY_PATH=/opt/gtk/lib ruby ...` too.

**Comment by SamiSieranoja** [comment]
Thanks for the help! 

To test if ruby is using the version from /opt/gtk4 (4.13.8), I'm running the following script:
ruby -e 'require "gtk4"; puts Gtk::Version::STRING; sleep 9999'

This still outputs 4.6.9 (system default)

Although `pldd 76196 | grep gtk` (76196 being the pid of the previous ruby command) shows that the right libraries are being used by that process, e.g.:
/opt/gtk4/lib/x86_64-linux-gnu/libgtk-4.so.1
/opt/gtk4/lib/x86_64-linux-gnu/libgirepository-1.0.so.1

(and libgtk-4.so.1 is a link to libgtk-4.so.1.1308.0)

I also checked that during the gem compilation the right include path was being used (e.g. -I /opt/gtk4/include/gtk-4.0).  

So, I can't figure out where the wrong version number comes from. 

I also tried installing gobject-introspection from sources and reinstalling all gems from scratch. 

Also had to do a hack to fix following error:
/home/samsam/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.1/lib/gobject-introspection/loader.rb:40:in `require': Typelib file for namespace 'GdkPixbuf' (any version) not found (GObjectIntrospection::RepositoryError::TypelibNotFound)

export GI_TYPELIB_PATH="/opt/gtk4/lib/x86_64-linux-gnu/girepository-1.0/"
cp -r /opt/gtk4/lib/x86_64-linux-gnu/girepository-1.0/ /opt/gtk4/lib/x86_64-linux-gnu/girepository-1.0_orig
cp /usr/lib/x86_64-linux-gnu/girepository-1.0/* /opt/gtk4/lib/x86_64-linux-gnu/girepository-1.0/
cp /opt/gtk4/lib/x86_64-linux-gnu/girepository-1.0_orig/* /opt/gtk4/lib/x86_64-linux-gnu/girepository-1.0/

I would like to avoid compiling all the stuff under /usr/lib/x86_64-linux-gnu/girepository-1.0/, and just compile gtk and gobject-introspection (not sure if gi is needed?), but I'm not sure if that's a right way to do it.

**Comment by kou** [comment]
You don't need to build GObject Introspection.
You can use `GI_TYPELIB_PATH=/opt/gtk4/lib/x86_64-linux-gnu/girepository-1.0:/usr/lib/x86_64-linux-gnu/girepository-1.0 ruby ...`.

Could you try the following?

```bash
LD_LIBRARY_PATH=/opt/gtk4/lib/x86_64-linux-gnu GI_TYPELIB_PATH=/opt/gtk4/lib/x86_64-linux-gnu/girepository-1.0:/usr/lib/x86_64-linux-gnu/girepository-1.0 ruby -r gtk4 -e 'p Gtk::Version::STRING'
```

**Comment by SamiSieranoja** [comment]
Thank you! I tried, but I'm still getting the wrong version number.

And what is strange, the Gtk::Version.or_later? seems to give the right info although Gtk::Version::STRING is wrong. 4.13.8 is the version I compiled. 

```

  irb(main):011:0> Gtk::Version.or_later?(4, 12, 7)
  => true
  irb(main):012:0> Gtk::Version.or_later?(4, 13, 8)
  => true
  irb(main):013:0> Gtk::Version.or_later?(4, 13, 9)
  => false
  irb(main):014:0>  Gtk::Version::STRING
  => "4.6.9"

```

And I also verified that the compiled source code is in use by adding a printf to g_application_new (gtk/gtkapplication.c).

I also got errors by running
```
provider = Gtk::CssProvider.new
provider.load(data: "...")
```
ib/gobject-introspection/loader.rb:700:in `invoke': Gtk::CssProvider#load_from_data: wrong number of arguments (2 for 1) (ArgumentError)

Might be because load_from_data is deprecated in 4.12?
https://docs.gtk.org/gtk4/method.CssProvider.load_from_data.html

**Comment by SamiSieranoja** [comment]
gtk-4.9.4 seems to work fine. I'm getting the wrong version number only with gtk-4.13.8.

**Comment by kou** [comment]
Could you show `grep _VERSION /opt/gtk4/share/gir-1.0/Gtk-4.0.gir` with gtk-4.13.8?

**Comment by SamiSieranoja** [comment]
> Could you show `grep _VERSION /opt/gtk4/share/gir-1.0/Gtk-4.0.gir` with gtk-4.13.8?

Unfortunately I could not replicate the issue. There was several problems with compiling the main gtk-4.0 library, and some of the workarounds I first used probably broke some things.

Anyway, I can now install the gtk4 gem also for 4.13.8.

The script that I used is here:
https://gist.github.com/SamiSieranoja/3fd12b30f801af154bbca46822d565fd
