### ISSUE TITLE
Many broken links to OSDN

### ISSUE THREAD

**Issue by znz** [ruby-gnome/ruby-gnome#1611]
There are many links to OSDN in README, hompage in gemspec, and website URL of this repository details.
But it is not accessible.

So I have a problem to reach to this repository from https://rubygems.org/gems/glib2 and other ruby-gnome2 gems at rubygems.org.

related: https://github.com/ruby-gnome/ruby-gnome/issues/1465

**Comment by kou** [comment]
Could you open a PR to update URLs?

**Comment by znz** [comment]
I don't know where the primary website is.
And I can't change website URL of this repository details.

**Comment by kou** [comment]
https://ruby-gnome.github.io/

You don't need to do everything. You can do what you can do.

I've updated the repository details.
