### ISSUE TITLE
TreeStore.new malfunctions if you pass GdkPixbuf::Pixbuf as a column type in WINDOWS

### ISSUE THREAD

**Issue by Beagle123** [ruby-gnome/ruby-gnome#1621]
Hi Kou 

Thanks for all your great work.

Im making a GtkTreeView in my windows/Ruby program and it refuses to allow a Pixbuf column:

test.rb:

require "gtk3"
Gtk::TreeStore.new(String,String,String)
puts "Passed Test with Strings"  #this shows
Gtk::TreeStore.new(String, GdkPixbuf::Pixbuf,String,String)
puts "Passed test with Pixbuf"  never gets here.

Using Windows 11
Ruby 3.2.5
gtk3 gem 4.2.4
 

This test.rb works perfectly in linux.  

Thanks,
Eric

C:\Users\Eric\vrp\vr3>ruby test.rb
Passed Test with Strings
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:81: [BUG] Segmentation fault
ruby 3.2.5 (2024-07-26 revision 31d0f1a2e7) [x64-mingw-ucrt]

-- Control frame information -----------------------------------------------
c:0025 p:---- s:0132 e:000131 CFUNC  :initialize
c:0024 p:---- s:0129 e:000128 CFUNC  :new
c:0023 p:---- s:0126 e:000125 CFUNC  :try_convert
c:0022 p:0006 s:0121 e:000120 METHOD C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:81
c:0021 p:0031 s:0115 e:000114 METHOD C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:22
c:0020 p:0008 s:0108 e:000107 METHOD C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-info.rb:20
c:0019 p:0013 s:0103 e:000102 BLOCK  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:120 [FINISH]
c:0018 p:---- s:0099 e:000098 CFUNC  :collect
c:0017 p:0028 s:0095 e:000094 METHOD C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:118
c:0016 p:0067 s:0088 e:000087 METHOD C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:146
c:0015 p:0031 s:0082 e:000081 METHOD C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:22
c:0014 p:0008 s:0075 e:000074 METHOD C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-info.rb:20
c:0013 p:0024 s:0070 e:000069 BLOCK  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:803 [FINISH]
c:0012 p:---- s:0063 e:000062 CFUNC  :times
c:0011 p:0007 s:0059 e:000058 METHOD C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:800
c:0010 p:0076 s:0053 e:000052 METHOD C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:705
c:0009 p:0015 s:0044 e:000043 BLOCK  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:366 [FINISH]
c:0008 p:---- s:0040 e:000039 CFUNC  :catch
c:0007 p:0005 s:0036 e:000035 BLOCK  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:365 [FINISH]
c:0006 p:---- s:0032 e:000031 CFUNC  :each
c:0005 p:0011 s:0028 e:000027 METHOD C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:364
c:0004 p:0005 s:0019 e:000018 METHOD C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gtk3-4.2.4/lib/gtk3/tree-store.rb:21 [FINISH]
c:0003 p:---- s:0014 e:000013 CFUNC  :new
c:0002 p:0035 s:0006 e:000005 EVAL   test.rb:9 [FINISH]
c:0001 p:0000 s:0003 E:0024a0 DUMMY  [FINISH]

-- Ruby level backtrace information ----------------------------------------
test.rb:9:in `<main>'
test.rb:9:in `new'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gtk3-4.2.4/lib/gtk3/tree-store.rb:21:in `initialize'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:364:in `initialize'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:364:in `each'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:365:in `block in initialize'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:365:in `catch'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:366:in `block (2 levels) in initialize'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:705:in `invoke'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:800:in `normalize_arguments!'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:800:in `times'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:803:in `block in normalize_arguments!'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-info.rb:20:in `try_convert'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:22:in `try_convert'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:146:in `try_convert_array'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:118:in `try_convert_array_like'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:118:in `collect'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:120:in `block in try_convert_array_like'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-info.rb:20:in `try_convert'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:22:in `try_convert'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:81:in `try_convert_gtype'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:81:in `try_convert'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:81:in `new'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/type-tag.rb:81:in `initialize'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0x14) [0x00007ffed8e6f3f4]
C:\WINDOWS\System32\KERNELBASE.dll(WaitForSingleObjectEx+0x8e) [0x00007ffed62644ee]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_bugreport+0x24e) [0x00007ffe877b8d5e]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_bug_for_fatal_signal+0x80) [0x00007ffe875a3800]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_shape_memsize+0x542) [0x00007ffe876fbfd2]
 [0x00007ff6114e1e42]
C:\WINDOWS\System32\ucrtbase.dll(_C_specific_handler+0xa0) [0x00007ffed68b7f30]
C:\WINDOWS\SYSTEM32\ntdll.dll(_chkstk+0x12f) [0x00007ffed8e7441f]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlFindCharInUnicodeString+0xa96) [0x00007ffed8dee466]
C:\WINDOWS\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x00007ffed8e7340e]
C:\Ruby32-x64\msys64\ucrt64\bin\libgobject-2.0-0.dll(g_type_name+0x44) [0x00007ffebd41b7d4]
C:\Ruby32-x64\lib\ruby\gems\3.2.0\gems\glib2-4.2.4\lib\glib2.so(rbgobj_signal_wrap+0xc50) [0x00007ffebfb76bd0]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_invoke_proc+0x1db) [0x00007ffe877a091b]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_check_funcall_with_hook+0x8e8) [0x00007ffe877a40d8]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_funcallv_kw+0x59) [0x00007ffe877a49b9]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_obj_call_init_kw+0x5e) [0x00007ffe875af8ee]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_class_new_instance_pass_kw+0x84) [0x00007ffe87653d84]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_invoke_proc+0x1db) [0x00007ffe877a091b]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_eval_cmd_kw+0x5b8) [0x00007ffe877a51a8]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_funcallv+0x11) [0x00007ffe877a53d1]
C:\Ruby32-x64\lib\ruby\gems\3.2.0\gems\glib2-4.2.4\lib\glib2.so(rbgobj_signal_wrap+0x145f) [0x00007ffebfb773df]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_error_arity+0x13c) [0x00007ffe8778deac]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_ec_obj_respond_to+0xba8) [0x00007ffe877aa898]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_exec+0x11c) [0x00007ffe8779aebc]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_yield+0x1f3) [0x00007ffe877b03c3]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_ary_diff+0x177e) [0x00007ffe8750d01e]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_error_arity+0x13c) [0x00007ffe8778deac]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_ec_obj_respond_to+0x1759) [0x00007ffe877ab449]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_exec+0x11c) [0x00007ffe8779aebc]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_yield_1+0x223) [0x00007ffe8779e8b3]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_int_ge+0x64b) [0x00007ffe87644efb]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_error_arity+0x13c) [0x00007ffe8778deac]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_ec_obj_respond_to+0x1759) [0x00007ffe877ab449]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_exec+0x11c) [0x00007ffe8779aebc]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_yield_1+0x513) [0x00007ffe8779eba3]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_block_call+0x1fb) [0x00007ffe87795a1b]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_catch+0xef) [0x00007ffe87795d5f]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_error_arity+0x13c) [0x00007ffe8778deac]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_ec_obj_respond_to+0x1759) [0x00007ffe877ab449]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_exec+0x11c) [0x00007ffe8779aebc]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_yield+0x1f3) [0x00007ffe877b03c3]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_ary_each+0x3d) [0x00007ffe87505dfd]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_error_arity+0x13c) [0x00007ffe8778deac]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_ec_obj_respond_to+0x1759) [0x00007ffe877ab449]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_exec+0x11c) [0x00007ffe8779aebc]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_check_funcall_with_hook+0x8e8) [0x00007ffe877a40d8]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_funcallv_kw+0x59) [0x00007ffe877a49b9]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_obj_call_init_kw+0x5e) [0x00007ffe875af8ee]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_class_new_instance_pass_kw+0x84) [0x00007ffe87653d84]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_error_arity+0x13c) [0x00007ffe8778deac]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_ec_obj_respond_to+0xba8) [0x00007ffe877aa898]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_exec+0x9ab) [0x00007ffe8779b74b]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_call_end_proc+0x330) [0x00007ffe875a8530]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(ruby_run_node+0x90) [0x00007ffe875ae2b0]
 [0x00007ff6114e2a5e]
 [0x00007ff6114e12ee]
 [0x00007ff6114e1406]
C:\WINDOWS\System32\KERNEL32.DLL(BaseThreadInitThunk+0x1d) [0x00007ffed6cf257d]

-- Other runtime information -----------------------------------------------

* Loaded script: test.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 fiber.so
    3 rational.so
    4 complex.so
    5 ruby2_keywords.rb
    6 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/enc/encdb.so
    7 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/enc/trans/transdb.so
    8 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/rbconfig.rb
    9 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/compatibility.rb
   10 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/defaults.rb
   11 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/deprecate.rb
   12 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/errors.rb

**Comment by kou** [comment]
Thanks for your report.
I've fixed it. I'll release new version in this week.
