### ISSUE TITLE
Installing Gtk3 Gem

### ISSUE THREAD

**Issue by Beagle123** [ruby-gnome/ruby-gnome#1622]
Hi Kou:

Im really happy that you found the problem with windows/TreeView.  Thanks!!!!!

I'm the guy who works on visualruby.  I hope I can contribute to getting the gtk3 gem 
running smoothly.  Just recently I started with a fresh install of Ubuntu, and it took me 
2 days to get the gtk3 gem running.

On the fresh computer, I installed ruby via the Ubuntu software center.  Then I ran:

gem install gtk3

and it crashed.

I tried using "sudo" and installing ruby-dev and ruby-gnome2 and everything kept crashing.

Finally, I had to install a ruby install manager, rbenv (RVM works too) then it finally worked.

Im not the only one who struggles with this.  Obviously, the gtk3 gem needs to be installed
using a ruby version manager, or it crashes.

Here's the problem as I see it.  There is a local version of ruby, and a system version of ruby:

eric@ec:~$ ruby -v
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
eric@ec:~$ sudo ruby -v
[sudo] password for eric: 
ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux-gnu]
eric@ec:~$ 

local = 3.3.5
system = 3.2.3

Each will have their own path to install the gtk3 gem.  This is a problem because parts of gtk3 are
installed with sudo permission, but if you install everything that way, you get locked out if you're not root user.

It was such a mess that I had to wipe out my computer several times.

The install official instructions are:

gem install gtk3

But that definitely won't work unless you're at least using the local version of ruby perhaps with a version manager.

Obviously, you know way more about this than I do, but I think most people will not be able to get it installed.

I would suggest adding this to your install instructions:

INSTALL INSTRUCTIONS
The gtk3 gem requires your ruby version to be run from under your home directory.  If you use a version manager like
rbenv or RVM they will automatically install your ruby versions under your home folder.  Do not install
gtk3 as the root user as this will likely fail because it lacks permissions.  So don't use the "sudo" command.

To test if gtk3 will install correctly, run this command:

which ruby

==> /home/eric/.rbenv/shims/ruby

It should show a folder under home this is correct.

If it shows something like:

/usr/bin/ruby

Then you need to install rbenv or RVM to use your ruby from under the home folder.

Thanks again for all your great work.  
I know you're an expert at this so you have no problem installing gtk3, but normal people
have very little hope of figuring it out.  I worked on it for 2 days.  Most people quit after 10 minutes.

Let me know if I can contribute.

Best wishes,
Eric

**Comment by kojix2** [comment]
Hello, I understand your concerns.

This issue should be addressed, but it’s part of a bigger problem.

On Linux, installing Ruby through the system package manager often causes issues with Gems like gtk3. The same goes for Python, where many packages might fail to install.

Changing permissions or adding options for headers and libraries can sometimes help, but it’s not a reliable solution.

System-installed Ruby and Python are mainly meant for system-level dependencies, not for personal use.

That’s why many Linux users avoid using the system package manager for development. Instead, they use version managers like rbenv or pyenv. I agree it’s not very beginner-friendly, though.

**Comment by kou** [comment]
Could you open a PR that adds how to install with rbenv?

But I don't want to remove how to install with system Ruby.

**Comment by Beagle123** [comment]
Hi Kou:

I would be happy to write install instructions.  What is a PR?

Also, I'd like to write a description for the your gtk3 gemfile describing what it is.  Right now it says:

"Ruby/GTK3 is a Ruby binding of GTK+-3.x."

Id like to expand on that to explain in normal language what that means.

So when people find you on rubygems.org, they'll want to download gtk3.  


![Screenshot from 2024-10-04 19-12-24](https://github.com/user-attachments/assets/4d230b7e-ffeb-4d7c-8cfd-2602f08cb52d)

**Comment by Beagle123** [comment]
I wrote these instructions to install gtk3.  I really wish I had them last week when I was floundering.

[Installing Gtk3 Gem.txt](https://github.com/user-attachments/files/17265017/Installing.Gtk3.Gem.txt)

**Comment by Beagle123** [comment]
I wrote a description for gtk3 gem.   If you copy it to your .gemspec file, it will update on rubygems.org.

I'm really looking forward to the next update.  Tha
[Ruby Gtk3 is a ruby binding.txt](https://github.com/user-attachments/files/17265105/Ruby.Gtk3.is.a.ruby.binding.txt)
nks for everything!

**Comment by kou** [comment]
> What is a PR?

Ah, sorry. "PR" is an abbreviation of "pull request".

Could you provide your suggestion as a pull request for each part? (A pull request for README update and a pull request for `.gemspec` update.)
See also: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by rubyFeedback** [comment]
> Obviously, the gtk3 gem needs to be installed
> using a ruby version manager, or it crashes.

For me it works without a ruby version manager; "gem install gtk3" works fine. I am currently
transitioning into gtk4 myself, even though gtk3 seems to have a lot more support e. g. from
examples + documentation and functionality. But it seems sooner or later we'll have to move
to gtk4. Even the webpage here has "gem install gtk4" as example and not "gem install gtk3"
anymore. :)

**Comment by rubyFeedback** [comment]
I think it may be easier to just add a subsection to the main README,
e. g. giving a few hints for rbenv; instructions for how to install rbenv
should be left to the rbenv homepage, and a link towards it could be
used instead. And the part about failing installation may probably be
better put into a separate file, or a FAQ. A general FAQ may be more
useful; it can also mention failures such as the one here in regards
to rbenv (or no rbenv). An entry such as "See also the FAQ for not only
additional information, but specifically information pertaining to
installation-related issues." - or something like that. That way the main
README still remains focused, and troubles in regards to installation
can be relegated to the FAQ page (or, a separate page, anyway).

**Comment by Beagle123** [comment]
Hi Kou:

I just installed gtk4, gtksourceview4 and gtksourceview5, and it went perfectly!!!!

On:
Ubuntu 24
rbenv

Great work!!!
Thanks

**Comment by kou** [comment]
OK. Let's close this.
