### ISSUE TITLE
ruby-gnome/gtk4/sample/demos/gtk-demo/main.rb: can we make opengl optional?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1629]
ruby-gnome/gtk4/sample/demos/gtk-demo/main.rb

I think this is this file here:

https://github.com/ruby-gnome/ruby-gnome/blob/main/gtk4/sample/demos/gtk-demo/main.rb

When trying to run it I get this error:

 <internal:/home/Programs/Ruby/3.3.5/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- opengl (LoadError)

Did you mean?  open
               openssl
               open3
        from <internal:/home/Programs/Ruby/3.3.5/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /depot/jjjj/ruby-gnome/gtk4/sample/demos/gtk-demo/glarea.rb:24:in `<top (required)>'
        from main.rb:53:in `require_relative'
        from main.rb:53:in `block in <main>'
        from <internal:dir>:411:in `glob'
        from main.rb:50:in `<main>'

But, do we really need opengl? Can we protect it via a begin/rescue clause, and just notify the user
that it is recommended to use opengl if possible? I'd like to make the default gtk4 bindings and examples more useful, right after the user did e. g. "gem install gtk4". Getting opengl to work may not be as easy, so having this optional is, IMO, the better approach, at the least for those code samples that could work on ruby-gtk4.

(Also, I am not quite finding the big overview example that we had in ruby-gtk3, perhaps it does not exist for ruby-gtk4 yet, but it would be nice to be able to see which widget sets work in ruby-gtk4, which came anew etc... anyway, let's go step by step in small steps for now.)

**Comment by kou** [comment]
Done.
