### ISSUE TITLE
Can't get Gio::ListStore.new() to work because I need a GObject.

### ISSUE THREAD

**Issue by Beagle123** [ruby-gnome/ruby-gnome#1635]
Hi Kou:

Im trying to switch to gtk4's new TreeView, ColumnView.

However, when I try this:

    store = Gio::ListStore.new(DataObject)

it gives an error because DataObject must be a subclass of GObject

So my class definition:

    class DataObject < GObject

does't find the Name GObject

How to I reference GOObject?  Where is it?

Do I need these:
```
      require "gio"
      require "gio2"
```
Then where is GObject?

Gio::GObject  (fails)
GObject::Gobject (fails)
GObject::Object (fails)

I've looked everytwhere.

please fix this line of code:

    class DataObject < GObject

Thanks, and I when I write a simple example for a TreeView, I will submit it to the samples directory.

Eric

**Comment by Beagle123** [comment]
I think I found the answer to this.  Its GLib::Object.

**Comment by kou** [comment]
Yes. It's `GLib::Object`.
