### ISSUE TITLE
Thanks for updating gtk3.  Its working in windows now!

### ISSUE THREAD

**Issue by Beagle123** [ruby-gnome/ruby-gnome#1640]
I installed gtk3 gem in windows.

It had two warnings:

warning: mingw-w64-ucrt-x86_64-harfbuzz will be installed before its mingw-w64-ucrt-x86_64-freetype dependency
warning: mingw-w64-ucrt-x86_64-libwebp will be installed before its mingw-w64-ucrt-x86_64-libtiff dependency

But it seems to work fine.  Thank you!!

Complete messages:

Successfully installed pkg-config-1.5.8
Successfully installed native-package-installer-1.1.9
Building native extensions. This could take a while...
Successfully installed glib2-4.2.5
Building native extensions. This could take a while...
Successfully installed gobject-introspection-4.2.5
Successfully installed red-colors-0.4.0
warning: dependency cycle detected:
warning: mingw-w64-ucrt-x86_64-harfbuzz will be installed before its mingw-w64-ucrt-x86_64-freetype dependency
Building native extensions. This could take a while...
Successfully installed cairo-1.17.13
Building native extensions. This could take a while...
Successfully installed cairo-gobject-4.2.5
Building native extensions. This could take a while...
Successfully installed pango-4.2.5
Building native extensions. This could take a while...
Successfully installed gio2-4.2.5
warning: dependency cycle detected:
warning: mingw-w64-ucrt-x86_64-libwebp will be installed before its mingw-w64-ucrt-x86_64-libtiff dependency
Building native extensions. This could take a while...
Successfully installed gdk_pixbuf2-4.2.5
Building native extensions. This could take a while...
Successfully installed gdk3-4.2.5
Building native extensions. This could take a while...
Successfully installed atk-4.2.5
Building native extensions. This could take a while...
Successfully installed gtk3-4.2.5
Building native extensions. This could take a while...
Successfully installed gtksourceview4-4.2.5
Successfully installed visualruby-3.6.13
Parsing documentation for pkg-config-1.5.8
Installing ri documentation for pkg-config-1.5.8
Parsing documentation for native-package-installer-1.1.9
Installing ri documentation for native-package-installer-1.1.9
Parsing documentation for glib2-4.2.5
Installing ri documentation for glib2-4.2.5
Parsing documentation for gobject-introspection-4.2.5
Installing ri documentation for gobject-introspection-4.2.5
Parsing documentation for red-colors-0.4.0
Installing ri documentation for red-colors-0.4.0
Parsing documentation for cairo-1.17.13
Installing ri documentation for cairo-1.17.13
Parsing documentation for cairo-gobject-4.2.5
Installing ri documentation for cairo-gobject-4.2.5
Parsing documentation for pango-4.2.5
Installing ri documentation for pango-4.2.5
Parsing documentation for gio2-4.2.5
Installing ri documentation for gio2-4.2.5
Parsing documentation for gdk_pixbuf2-4.2.5
Installing ri documentation for gdk_pixbuf2-4.2.5
Parsing documentation for gdk3-4.2.5
Installing ri documentation for gdk3-4.2.5
Parsing documentation for atk-4.2.5
Installing ri documentation for atk-4.2.5
Parsing documentation for gtk3-4.2.5
Installing ri documentation for gtk3-4.2.5
Parsing documentation for gtksourceview4-4.2.5
Installing ri documentation for gtksourceview4-4.2.5
Parsing documentation for visualruby-3.6.13
Installing ri documentation for visualruby-3.6.13
Done installing documentation for pkg-config, native-package-installer, glib2, gobject-introspection, red-colors, cairo, cairo-gobject, pango, gio2, gdk_pixbuf2, gdk3, atk, gtk3, gtksourceview4, visualruby after 8 seconds
15 gems installed

**Comment by kou** [comment]
Thanks for confirming!
