### ISSUE TITLE
Gtk::CellRenderer create custom renderer, something missing with 'render' function

### ISSUE THREAD

**Issue by gauteh** [ruby-gnome/ruby-gnome#220]
Hi,

I am trying to create a custom Gtk::CellRenderer by subclassing it and overriding get_size and render. I see that in gtk3/ext/gtk3/rbgtk-cell-renderer.c there are some TODO's. I tried changing the render function into the current gtk3 format and register it in Init_gtk_cellrenderer(). But, still I get errors like:

```
   Gtk-CRITICAL **:gtk_cell_renderer_render: assertion 'GTK_CELL_RENDERER_GET_CLASS (cell)->render != NULL' failed
```

when trying to use my CellRenderer.

**Comment by Beagle123** [comment]
Any updates on this?  THis might be the same problem that I'm experiencing.  I wish I could help you, but I don't really know C.
