### ISSUE TITLE
gtk3 not loading theme in MSWindows

### ISSUE THREAD

**Issue by tescorg** [ruby-gnome/ruby-gnome#235]
When running a gtk3 app in ms windows the windows theme is not applied. It is applied in gtk2 apps automatically.

**Comment by pioz** [comment]
Similar problem on Windows 10, but the trick `Gtk::Settings.default.gtk_theme_name = "gtk-win32"` does not work for me...
Here my screenshot:
GTK2 OK:
![gtk2](https://i.imgur.com/RgoWyoY.png)
GTK3 WRONG:
![gtk2](https://i.imgur.com/dw7KwFN.png)

Any idea?

**Comment by cedlemo** [comment]
It looks like the same problem than in the issue #750.
