### ISSUE TITLE
video-player.rb clutter-gst sample doesn't work

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome/ruby-gnome#554]
When I try to run the script, I have this error:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/clutter-gstreamer-3.0.4/lib/clutter-gst.rb:38:in `const_missing': uninitialized constant ClutterGst::VideoTexture (NameError)
    from video-player.rb:163:in `<main>'
```

Here are the gem I have : 

```
atk (3.0.4)
cairo-gobject (3.0.4)
clutter (3.0.4)
clutter-gstreamer (3.0.4)
gdk3 (3.0.4)
gdk_pixbuf2 (3.0.4)
gio2 (3.0.4)
glib2 (3.0.4)
gobject-introspection (3.0.4)
gstreamer (3.0.4)
gtk3 (3.0.4)
pango (3.0.4)
vte3 (3.0.4)
```

**Comment by kou** [comment]
The sample is created for Clutter Gst 1.x and 2.x. Clutter Gst 1.x and 2.x provide the object: https://developer.gnome.org/clutter-gst/2.0/ClutterGstVideoTexture.html

But Clutter Gst 3.x doesn't provide it. We need to use `ClutterGst::Playback` and `ClutterGst::Aspectratio` instead:

  * https://developer.gnome.org/clutter-gst/3.0/ClutterGstPlayback.html
  * https://developer.gnome.org/clutter-gst/3.0/ClutterGstAspectratio.html
  * https://git.gnome.org/browse/clutter-gst/tree/examples/video-player.c#n473

**Comment by Alanzote** [comment]
It is complicated to convert the C code into Ruby, since ruby is object oriented. I would be grateful if someone would provide a small example with streamed media video player.

**Comment by kou** [comment]
Implemented.
