### ISSUE TITLE
Zero-sized font triggers an OutOfMemory error

### ISSUE THREAD

**Issue by andymeneely** [ruby-gnome/ruby-gnome#603]
I don't know if this is an issue in Pango itself, but I thought I would start my reporting here. This code snippet causes an OutOfMemory error.

``` ruby
require 'cairo'
require 'pango'

cxt = Cairo::Context.new(Cairo::ImageSurface.new(100,100))
layout = cxt.create_pango_layout
font = Pango::FontDescription.new('Sans Bold 36')
layout.font_description = font

# This markup gives us space to render an image in the text flow and have it flow like words.
# It is a bit hacky, but I can't figure out how to get ruby+pango+cairo to create arbitrary space
layout.markup = 'x<span size="0">a<span letter_spacing="20000">a</span>a</span>y'

cxt.pango_layout_path(layout) # fails here

cxt.show_pango_layout layout
cxt.target.write_to_png('bug_103.png')
```

The error is NOT triggered if you do ANY of the following:
- Change the size from 0 to 1. This isn't an option for us because it makes the letter show and we're just trying to create space
- Comment out the `pango_layout_path`

Are zero-sized fonts allowed in Pango in the first place? 

I believe this is unrelated to #477. That one felt like a compiler upgrade issue with Mac. This one is probably related to `pango_layout_path` trying to do matrix math with zeros. 

I'm working on Windows, and I haven't test this on other OS's.

**Comment by cedlemo** [comment]
> I'm working on Windows, and I haven't test this on other OS's.

I tested the code snippet with the git version of ruby-gnome2 on Arch Linux x86_64 and it works.

**Comment by kou** [comment]
I hope that this was fixed in the latest Pango and cairo.
