### ISSUE TITLE
GTK3 Tutorials fail with  GLib-GIO-CRITICAL **: This application can not open files. 

### ISSUE THREAD

**Issue by casper** [ruby-gnome/ruby-gnome#721]
1) Installed Ruby 2.0.0 + gtk3 gem on Win32.
2) Downloaded the git source for ruby-gnome2 and went into `ruby-gnome2/gtk3/sample/tutorial`.
3) Run `ruby example-0.rb`

Result:

```
(ruby.exe:6472): GLib-GIO-CRITICAL **: This application can not open files.
1
```

How can I run the tutorials?

**Comment by cedlemo** [comment]
Is the *exampleapp1/exampleapp.rb* script doing the same ?

**Comment by casper** [comment]
Ok, the exampleapps seem to work, but `example-0/1/2.rb` all fail.

I tried googling this problem but did not really find a solution. If I add the `:handles_open` flag then the warning goes away, but the application just exits with `0` when run. So that wasn't really a solution either. 

Why it seems to expect to handle open when the `:flags_none` is given seems strange.

**Comment by cedlemo** [comment]
Well, I don't have any explanations (for now). Could you try the other flags (https://developer.gnome.org/gio/unstable/GApplication.html#GApplicationFlags).

 I am sorry I don't have any version of windows in order to test.

I continue to search informations about this problem.

**Comment by casper** [comment]
Ok thanks. I've never used Gtk before so I don't really know how to debug this either. Here's how I changed the sample to see what happens:

```
require "gtk3"
require "pp"

app = Gtk::Application.new("org.gtk.example", [ :handles_open ])

app.signal_connect("open") { |*args|
  pp args
}

app.signal_connect "activate" do |application|
  puts "Activate"
  window = Gtk::ApplicationWindow.new(application)
  window.set_title("Window")
  window.set_default_size(200, 200)
  window.show_all
end

puts app.run
```

Result:
```
[]
[#<Gtk::Application:060DD988 ptr=02D5A120>,
 [#<#<Class:0x60dd040>:060DCF20 ptr=06C4EC80>],
 ""]
0
```
If I read the docs correctly the `open` signal should not fire unless there are files to open. But it's firing in this instance, and `activate` is never called. 

Here's C sample I found implementing similar behavior, and I assume `activated` will always be printed here:

https://github.com/bratsche/glib/blob/master/gio/tests/gapplication-example-open.c

Weird..

**Comment by casper** [comment]
Here's a version that works:

```
require "gtk3"

app = Gtk::Application.new("org.gtk.example", [ :handles_command_line ])

app.signal_connect("command-line") { |app, *args| 
	app.activate
	0
}

app.signal_connect "activate" do |application|
  window = Gtk::ApplicationWindow.new(application)
  window.set_title("Window")
  window.set_default_size(200, 200)
  window.show_all
end

puts app.run
```

Still is a convoluted version, and I provided no command line args, yet `command-line` fired. However I am unclear if this is the way it's supposed to work or not.

**Comment by cedlemo** [comment]
Maybe : 
https://developer.gnome.org/gio/unstable/GApplication.html#g-application-run

> Note that on Windows, argc and argv are ignored, and g_win32_get_command_line() is called internally (for proper support of Unicode commandline arguments).

Maybe it is related (or not, I am not really sure).

**Comment by kou** [comment]
`GApplication` ignores arguments passed to `g_application_run()` on Windows. It always uses command line arguments even when we pass an empty array to `g_application_run()`.

Using `:handles_command_line` and `command-line` signal is correct.

**Comment by casper** [comment]
@kou So that means if developing cross-platform in a case like this you have to check for a Win32 environment and change the code accordingly, or will the `command-line` signal fire on an empty command line on Linux too?

**Comment by kou** [comment]
I recommend you that use `command-line` signal and `ARGV` to support cross-platform that includes Windows.
