### ISSUE TITLE
Gtk::RC.parse_string 

### ISSUE THREAD

**Issue by sphynx79** [ruby-gnome/ruby-gnome#901]
I created one menu to change theme in my application, but when i try:

``` Ruby
Gtk::RC.parse_string <<EndOfText
gtk-theme-name = "OSX-Arc-White"
EndOfText
```

in gtk 3.0.9 this method not exist but i see here
[ruby-gtk3](https://apt-browse.org/browse/ubuntu/trusty/universe/amd64/ruby-gtk3/2.1.0-1/file/usr/share/doc/ruby-gtk3/examples/testgtk/testgtk.rb)
that parse exist..

now i use 

``` Ruby
t = Gtk::Settings.default
t.gtk_theme_name = "OSX-Arc-White"
```

this work but if i want set other property for example gtk-font-name or gtk-xft-rgba, how i can set this property in settings.ini and parse this file.

Thanks

**Comment by cedlemo** [comment]
The bindings are done in the way that each properties for a Gtk object has a setter and a getter function. For example the for property "gtk-font-name":

https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-font-name
*   `Gtk::Settings#gtk_font_name`
*   `Gtk::Settings#gtk_font_name=`

```ruby
irb -r gtk3
irb(main):001:0> t = Gtk::Settings.default
=> #<Gtk::Settings:0x444d6b8 ptr=0x2e92300>
irb(main):002:0> t.gtk_font_name
=> "Cantarell 11"
irb(main):003:0> 
```

**Comment by cedlemo** [comment]
Maybe try this : 
https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html

and `GLib::KeyFile`.

**Comment by cedlemo** [comment]
@sphynx79 can I close this issue ?

**Comment by cedlemo** [comment]
@sphynx79 can I close this issue ?
