### ISSUE TITLE
Feedback from reddit about the name of the projet.

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome/ruby-gnome#959]
@kou,

I made the annoucement on different media including Reddit . 

A reddit user, in a previous annoucement, asked me why the name ruby-gnome2 for the project which he found misleading. Most of them are interested in Gtk and it seems that it was not clear for him that we support gtk3.

For the last annoucement, an user suggested that we change the name.

> Might be time to no longer call it ruby-gnome2. 

I really would like to know your opinion about it?

**Comment by kou** [comment]
"2" in "Ruby-GNOME2" means the next generation of "Ruby-GNOME". "Ruby-GNOME' is an old project name. http://ruby-gnome2.osdn.jp/hiki.cgi?History may help you.

http://ruby-gnome2.osdn.jp/ :

> Ruby-GNOME2 is a set of Ruby language bindings for the GNOME development environment. This is the next generation of Ruby-GNOME. 

Anyway, it may be a good time we use "Ruby-GNOME" again because we will support GNOME 4 by this project. :-)

**Comment by cedlemo** [comment]
> "2" in "Ruby-GNOME2" means the next generation of "Ruby-GNOME". "Ruby-GNOME' is an old project name. http://ruby-gnome2.osdn.jp/hiki.cgi?History may help you.

I knew about it and explained it too (https://www.reddit.com/r/ruby/comments/4dh8jn/new_version_for_the_gems_of_the_rubygnome2_project/d1rw2ec/), notheless I totally agree with you that it is time that we use "Ruby-GNOME".

> because we will support GNOME 4 by this project. :-)

:+1:

**Comment by kou** [comment]
> Do you plan to migrate/rename the ruby-GNOME2 to ruby-GNOME github organization?

I want to migrate project site ( http://ruby-gnome2.osdn.jp/ ) to GitHub pages before renaming project name.
I wan to work on it before the new release...

**Comment by cedlemo** [comment]
> I wan to work on it before the new release...

If you need help for some boring tasks or time consuming tasks, I would be happy to help.

**Comment by kou** [comment]
Thanks!

**Comment by kou** [comment]
Renamed.
