### ISSUE TITLE
Support for interfaces and virtual functions with `type_register`?

### ISSUE THREAD

**Issue by mvz** [ruby-gnome/ruby-gnome#985]
Currently type_register only supports deriving from a single GObject class. Are there any plans for supporting GObject interfaces? And what about vfuncs?

Support for this would allow, e.g., creating completion providers for GtkSourceview. For example, like so:

```ruby
class MyProvider < GLib::Object
  include GtkSource::CompletionProvider

  type_register

  # Somehow automatically link up vfuncs to methods ...
  def do_get_name
    'MyProvider'
  end
end
```

**Comment by kou** [comment]
We'll support them by using libffi (directly or via GObject Introspection).
But we don't work on it yet.

**Comment by kou** [comment]
Implemented.
The example you provided works with a minor change (`do_get_name` -> `virtual_do_get_name`):

```ruby
require "gtksourceview3"

class MyProvider < GLib::Object
  include GtkSource::CompletionProvider

  type_register

  # Somehow automatically link up vfuncs to methods ...
  def virtual_do_get_name
    'MyProvider'
  end
end

p MyProvider.new.name
```
